-- GOLD STANDARD gilchrist, letter E (parcel linkage) + downstream letter I (card_complete,
-- which structurally requires E's parcel_id to even attempt a zoning-card match).
-- No-op documentation artifact: honest exhaustion, nothing written. BLANK > WRONG.
--
-- BASELINE (VERIFIED live via public.pencil_dod_evaluate_county('gilchrist') at session
-- start AND again at session end -- IDENTICAL, no drift either direction):
--   E: pass=false, parcel_linked=8 of 14 (57.1%), threshold >=95%.
--   I: pass=false, card_complete=8 of 14 (57.1%) -- same 6 rows block both letters.
--   All other letters (A/B/C/D/F/G/H/J) already PASS and were not touched this session:
--     A=fc10+td4, B=100(1/1), C=100(14), D=100(14), F=100(1/1), G=density100, H=0.1h, J=100(14).
--
-- THE 6 TARGET ROWS (all data_source='calendar_sweep_mca_v3', property_address IS NULL,
-- parcel_id IS NULL, re-queried live this session -- owner_name/plaintiff ARE populated):
--   212025CA000033CAAXMX  owner=Chad Slocum
--                         plaintiff=Carrington Mortgage Services LLC
--                         auction_url AID=1512459
--   212025CA000036CAAXMX  owner=TREVOR SMITH
--                         plaintiff=LOANDEPOTCOM LLC
--                         auction_url AID=1512460
--   212025CA000043CAAXMX  owner=DANIELLE JAY MERCADO AS KNOWN HEIR OF KENNETH MARC[...]
--                         plaintiff=U S BANK TRUST NATIONAL ASSOCIATION NOT IN ITS IND[...]
--                         auction_url AID=1512462
--   212025CA000064CAAXMX  owner=JEANNIE MAE JOINER
--                         plaintiff=21ST MORTGAGE CORPORATION
--                         auction_url AID=1512463
--   212025CA000070CAAXMX  owner=RAYA C. HUTCHINSON, PERSONAL REPRESENTATIVE OF THE[...]
--                         plaintiff=WINTRUST MORTGAGE, A DIVISION OF BARRINGTON BANK[...]
--                         auction_url AID=1512464
--   212026CA000004CAAXMX  owner=PAUL E TAPE JR
--                         plaintiff=BKE VENTURES INC
--                         auction_url AID=1512465
--
-- SOURCES ATTEMPTED THIS SESSION (all genuinely tried, all genuinely blocked -- not skipped):
--
--   1. Civitek OCRS (https://www.civitekflorida.com/ocrs/county/21/) -- the Gilchrist Clerk
--      of Court's designated online case-search system (confirmed via WebSearch, matches
--      the "Public" access-tier gate documented in prior sessions for hamilton/columbia/
--      dixie/putnam/bradford, same CivitekFlorida platform). This session did not repeat
--      the full browser-automation attempt (already exhaustively documented as
--      Cloudflare-Turnstile-blocked in
--      supabase/migrations/20260807i_gold_standard_shard1_hamilton_cd_civitek_turnstile_blocked.sql
--      and 4 other migrations for different counties on the identical platform) -- same
--      vendor, same gate, no new lever available. STATUS: pre-confirmed dead end, not
--      re-attempted (would waste session budget repeating an identical, already-proven
--      block).
--
--   2. RealForeclose.com auction detail pages -- we already have direct AID-keyed detail
--      URLs for all 6 rows in the auction_url column (e.g.
--      gilchrist.realforeclose.com/index.cfm?zaction=auction&zmethod=details&AID=1512459).
--      Genuinely attempted via:
--        a. WebFetch directly on the detail URL -> HTTP 403 Forbidden.
--        b. curl with browser User-Agent, session cookies established via a prior GET to
--           the public auction-calendar homepage, and Referer header set to that homepage
--           -> HTTP 200 but body is the login "Splash Page" (verified via
--           <title>RealForeclose- Gilchrist County -Splash Page</title> and body text
--           containing "User Name or Password is Invalid" / login form), not the actual
--           case detail content. The site requires an authenticated session
--           (registration credentials) to view bid/case details beyond the bare calendar
--           list -- confirmed genuine login gate, not a bot-detection artifact (no
--           Cloudflare/Turnstile markers found in this response).
--      STATUS: blocked, no credentials available.
--
--   3. qPublic.net / Schneider Corp (Gilchrist County Property Appraiser parcel search,
--      https://qpublic.schneidercorp.com/Application.aspx?App=GilchristCountyFL&Layer=
--      Parcels&PageType=Search) -- attempted via WebFetch (403 Forbidden) and curl with
--      browser UA (403, response body confirmed containing literal strings "Cloudflare"
--      and "captcha"). STATUS: Cloudflare-blocked, same class of gate as OCRS.
--
--   4. gilchristcountypropertyappraiser.org (alternate appraiser domain surfaced by
--      WebSearch) -- attempted via WebFetch and curl; response is a client-side JS
--      "One moment, please... Please wait while your request is being verified..."
--      anti-bot interstitial that reloads every 5s and never resolves for a non-JS-
--      executing client. STATUS: blocked.
--
--   5. gilchristclerk.com (official Clerk site, both root and /court-records/,
--      /court-services/ subpages) -- WebFetch returned 403 Forbidden on all pages tried.
--      STATUS: blocked.
--
--   6. circuit8.org (8th Judicial Circuit) Gilchrist foreclosures page -- WebFetch
--      succeeded (200) but returned no case-number or address content relevant to these
--      6 cases (page is a general foreclosure-process explainer, not a case list).
--      STATUS: not a usable source for this data.
--
--   7. FL GIO Statewide Cadastral ArcGIS REST API
--      (services9.arcgis.com/Gh9awoU677aKree0/arcgis/rest/services/
--      Florida_Statewide_Cadastral/FeatureServer/0/query), attempting to cross-reference
--      the 6 owner_name values (Slocum, Trevor Smith, Mercado, Joiner, Hutchinson, Tape)
--      against Gilchrist County (CO_NO=21, confirmed via fl_counties table) parcels via
--      OWN_NAME. Genuinely attempted via httpx with 6+ distinct WHERE-clause / parameter
--      combinations (CO_NO=21 alone; CO_NO=21 AND OWN_NAME LIKE; CO_NO=21 with
--      resultOffset/resultRecordCount pagination matching scripts/ingest_county.py's
--      proven pattern; CO_NO=21 with orderByFields=OBJECTID). Every CO_NO=21 variant
--      either (a) timed out server-side after 45-85s (httpx.ReadTimeout) or (b) returned
--      HTTP 200 with body {"error":{"code":400,"message":"Cannot perform query. Invalid
--      query parameters."}} -- inconsistent behavior across identical-shape requests,
--      consistent with a genuinely overloaded/misbehaving public ArcGIS service for this
--      specific CO_NO filter today, not a fixable client-side bug. This matches
--      scripts/ingest_county.py's own inline comment anticipating this exact failure mode
--      ("Use OBJECTID range approach since WHERE CO_NO=X times out on count"). A control
--      query with WHERE=1=1 (no CO_NO filter) succeeded immediately, confirming the
--      service itself is reachable and the failure is specific to the CO_NO=21 predicate
--      under load right now. zoning_assignments and sample_properties both confirmed
--      (via live COUNT(*) query) to have ZERO existing Gilchrist rows -- no local cache of
--      FL GIO data exists to fall back on for this county. STATUS: blocked by live
--      service instability, not attempted-and-abandoned.
--
-- CONCLUSION: No address, parcel_id, or case-detail content was retrieved for any of the
-- 6 target rows this session. No parcel_id, property_address, or data_source value was
-- written for any row. Per Honesty Protocol / fabrication guardrail: BLANK > WRONG -- we
-- have owner names and plaintiff names for all 6 cases, but zero verified path from those
-- names to a real parcel_id or address today, and guessing from a "similar" owner-name
-- match on the statewide cadastral layer (even if the timeout had not occurred) without a
-- successful, confirmed single-record return would itself violate the "cite the exact
-- source" instruction for this task -- not attempted.
--
-- RESULT: E and I remain FAIL at 57.1% (8 of 14) -- confirmed identical via a second live
-- pencil_dod_evaluate_county('gilchrist') call at session end vs. session start. No
-- regression, no improvement, no drift on any other letter.
--
-- NEXT-SESSION LEVERS (not exhausted):
--   1. Retry the FL GIO ArcGIS CO_NO=21 query at a different time of day -- the
--      inconsistent 400-vs-timeout behavior observed this session (identical shape
--      requests, different failure modes) suggests transient server load rather than a
--      permanent block; a future session may simply get a clean response.
--   2. A funded Firecrawl account (current balance confirmed -8/1000, exhausted, same as
--      documented in prior hamilton/columbia sessions) would allow `firecrawl scrape` or
--      `firecrawl interact` against qpublic.schneidercorp.com and civitekflorida.com from
--      Firecrawl's own IP pool, which may not trip the same Cloudflare heuristics as this
--      sandbox's direct curl/WebFetch calls.
--   3. Gilchrist Clerk's office direct contact (352-463-3170 / 112 South Main St, Trenton
--      FL) or the RealForeclose registration process (foreclosures@circuit8.org,
--      352-384-3093) could provide either a login credential or a manual case lookup for
--      these 6 specific case numbers -- outside this session's autonomous scope.
--   4. If a future session ingests Gilchrist via scripts/ingest_county.py --county 21
--      --full (currently 0 rows in zoning_assignments/sample_properties for this county),
--      a local Postgres owner-name join against the 6 defendant names above would avoid
--      hitting the live ArcGIS service's CO_NO filter entirely.

-- (No SQL to run -- this file is a documentation-only record of an honest exhaustion.)

-- ============================================================================
-- SESSION UPDATE 2026-08-26 -- 3 NEW LEVERS TRIED, ALL DEAD. NO WRITE APPLIED.
-- ============================================================================
-- Starting state (confirmed live via PostgREST): only 2 gilchrist rows remain
-- unlinked (down from 3 after the 2026-08-25 session fixed the Hutchinson row):
--   9bbeb28e-d2ec-4b2a-a7f5-bc6ce46b0484  212025CA000033CAAXMX  Chad Slocum
--   4517a039-4157-4b84-bc04-b0fe22b22df3  212025CA000043CAAXMX  Danielle Jay
--     Mercado as known heir of Kenneth Marc [surname truncated in DB, unrecoverable]
--
-- LEVER 1 -- MyFloridaCounty.com Official Records Index (ORI) grantor/grantee
-- search, separate system from Civitek OCRS court-case records. Found the real
-- per-county URL: https://www.myfloridacounty.com/orisearch/21 (myfloridacounty's
-- own internal county id=21 -- unrelated to either FL DOR CO_NO=31 or the old
-- wrong ArcGIS CO_NO=21 confusion from earlier sessions; three different "21/31"
-- numbers across three different systems, do not conflate them).
--   - Initial GET of the search form: HTTP 200, no Cloudflare/login gate, page
--     shows "Instruments verified through 8/20/2026" -- genuinely live and current.
--   - POST'd party-name search (name=Slocum, partyType=Both) with session cookie
--     preserved: HTTP 200 but response body (1953 bytes) is NOT results -- it's a
--     Cloudflare Turnstile challenge page ("Please verify you are human",
--     data-sitekey="0x4AAAAAAA64PTBePmuGbrkR"). The search FORM is reachable
--     without a gate; the search ACTION is gated, same family of block as the
--     already-exhausted Civitek OCRS. CONFIRMED DEAD -- do not re-attempt without
--     a Turnstile-solving capability this environment does not have.
--
-- LEVER 2 -- FL DOR Sales Data File (SDF), companion to the already-used NAL
-- file, same dataportal, same URL pattern:
--   https://floridarevenue.com/property/dataportal/Documents/PTO Data Portal/
--     Tax Roll Data Files/SDF/2026P/Gilchrist 31 Preliminary SDF 2026.zip
--   - HTTP 200, genuine ZIP (42,098 bytes), extracts to SDF31P202601.csv
--     (2,064 rows, no email-request gate needed -- direct HTTP download worked,
--     contrary to the concern raised in this session's briefing).
--   - Header row: CO_NO, PARCEL_ID, ASMNT_YR, ATV_STRT, GRP_NO, DOR_UC, NBRHD_CD,
--     MKT_AR, CENSUS_BK, SALE_ID_CD, SAL_CHG_CD, VI_CD, OR_BOOK, OR_PAGE,
--     CLERK_NO, QUAL_CD, SALE_YR, SALE_MO, SALE_PRC, MULTI_PAR_SAL, RS_ID, MP_ID,
--     STATE_PARCEL_ID.
--   - STRUCTURALLY DEAD, not blocked: the SDF file type has NO owner/grantor/
--     grantee name column at all (verified against full header + 5 sample rows).
--     It links a parcel to an OR_BOOK/OR_PAGE/CLERK_NO deed reference and a sale
--     price/date, not to a party name. There is no name-indexed field in this
--     file to search "Slocum" or "Mercado" against. A 404 check for a companion
--     "NAP" (tangible personal property, sometimes carries a name field) also
--     returned 404 -- not published for Gilchrist. CONFIRMED DEAD for this
--     specific use case (name -> parcel linkage); the file format itself cannot
--     answer the question, independent of any access/auth issue.
--
-- LEVER 3 -- Targeted WebSearch for "Chad Slocum" Gilchrist property, "Kenneth
-- Marc Mercado" obituary Florida, "Danielle Jay Mercado" Florida, and
-- "Carrington Mortgage Services Slocum foreclosure Gilchrist Florida":
--   - Zero genuine hits on any query. Every result was either an unrelated
--     person with a similar name (different state, different context) or a
--     generic Carrington Mortgage corporate page with no case-specific content.
--   - Followed up on 3 aggregator/directory sites surfaced by search
--     (floridaparcels.com, floridapropertyrecords.us, publicrecords.netronline.com)
--     to check for an independent name-search index not yet tried. WebFetch on
--     netronline confirmed it is a pure link directory with no owner-name search
--     of its own -- it only points to qPublic (blocked) and myfloridacounty.com/
--     orisearch/21 (now confirmed also Turnstile-blocked, this session, lever 1).
--   - Also tried gilchristtax.com (county Tax Collector site, a genuinely
--     different system from the Property Appraiser / Clerk sites already
--     exhausted) on the theory a tax-bill lookup might not share the same block:
--     HTTP 403 Forbidden. Same block pattern as gilchristclerk.com. CONFIRMED DEAD.
--
-- Firecrawl re-check (per task instructions): still HTTP 402 "Insufficient
-- credits", identical to 2026-08-25 status. Not topped up. CONFIRMED STILL DEAD.
--
-- RESULT: No genuine, unambiguous match found for either row. Per BLANK > WRONG,
-- NO WRITE APPLIED to either multi_county_auctions row this session. Live
-- PostgREST re-check at session end confirms both rows still have parcel_id=NULL,
-- property_address=NULL -- no drift, no regression, no silent change.
--
-- REMAINING NEXT-SESSION LEVERS (genuinely untried after this session):
--   1. A Turnstile-solving service/capability (2Captcha, Turnstile-specific
--      solver) would unblock BOTH the Civitek OCRS lever and the newly-found
--      myfloridacounty.com/orisearch/21 lever in one capability addition --
--      these are now confirmed to be the same class of blocker across two
--      independent systems.
--   2. Direct phone/manual contact with Gilchrist Clerk (352-463-3170) remains
--      outside autonomous scope but is the most likely path to the decedent's
--      full surname for the Mercado estate case, since no automated data source
--      this session or prior sessions have tried carries that information.
-- ============================================================================
