-- GOLD STANDARD sumter, letters E (parcel linkage) + I (property card completeness)
-- + J (deal thesis) -- 3-row owner-name/address re-attempt, session 2026-08-27.
-- No-op documentation artifact: honest exhaustion, nothing written. BLANK > WRONG.
--
-- BASELINE (VERIFIED live via public.pencil_dod_evaluate_county('sumter') at session
-- start AND again at session end -- IDENTICAL, no drift either direction):
--   E: pass=false, parcel_linked=29 of 32 (90.6%), threshold >=95%.
--   I: pass=false, card_complete=28 of 32 (87.5%).
--   J: pass=false, deal_complete=29 of 32 (90.6%).
--   auctions_total=32. All other letters (A/B/C/D/F/G/H) already PASS.
--
-- THE 3 TARGET ROWS (all parity_status='PARITY_OK', parity_source=
-- 'sumter_clerk_foreclosure', property_address/parcel_id/latitude/longitude/
-- assessed_value/market_value/owner_name/data_source ALL NULL, re-queried live
-- via PostgREST this session):
--   2026-CA-000074  WILMINGTON SAVINGS FUND SOCIETY FSB -VS- MARC G. RATLIFF
--                   sale_date 09/17/2026, judgment $265,593.22
--   2026-CA-000090  WILMINGTON SAVINGS FUND SOCIETY FSB -VS- MARY MCLEAN
--                   sale_date 09/17/2026, judgment $509,135.13
--   2026-CA-000129  KENNETH STRONG -VS- JOHNATHON YOUNG
--                   sale_date 10/01/2026, judgment $249,174.17
--
-- [... full prior-session record of 5 exhausted levers (MyFloridaCounty ORI,
-- Sumter ArcGIS owner-search, FL DOR statewide cadastral attribute filter,
-- qPublic/Schneider Cloudflare, CiviTek OCRS Turnstile) preserved verbatim from
-- the earlier version of this file, all still CONFIRMED DEAD -- not repeated
-- here in full, see git history for the complete original text. ...]
--
-- ============================================================================
-- SESSION UPDATE 2026-08-27 (2nd firing, same day) -- Bright Data MCP lever
-- (mcp__brightdata__search_engine / search_engine_batch / scrape_as_markdown),
-- per the gilchrist_i_card_completeness_blocked_followup.sql precedent.
-- PARTIAL SUCCESS: E moved 29->30 (90.6%->93.8%), still FAIL. I and J unchanged.
-- ============================================================================
--
-- CASE-BY-CASE RESULTS:
--
--   2026-CA-000074 (RATLIFF) -- STILL DEAD. search_engine confirmed the live
--     sumterclerk.com page NOW carries an Address field for this row
--     ("316 SAN MARINO DRIVE, LADY LAKE, FL 32159-8657") that a prior same-
--     session re-scrape had (incorrectly, or due to page staleness) reported
--     as absent for all rows -- re-verified live via WebFetch, confirmed
--     present. However this is the SAME address the prior session already
--     geocoded to parcel D13D081, owner "WHEELER DALE N & SHARON R"
--     (independently re-confirmed this session: searchportal.information.com
--     shows this exact address belongs to "Dale Wheeler", and a Compass.com
--     listing search corroborates 316 San Marino Dr as a distinct, existing
--     residential parcel). Searched specifically for a court filing linking
--     "Marc G. Ratliff" to Dale Wheeler's property as an heir/co-defendant
--     (the exact pattern that resolved the McLean row below) via
--     site:trellis.law "Ratliff" Sumter Florida and "Wheeler" "Ratliff"
--     Sumter County Florida 2026-CA-000074 -- NO connecting document found.
--     A "WHEELER v. WILMINGTON SAVINGS FUND SOCIETY FSB PNC" 2019 FL 5th DCA
--     appeal surfaced but is a different Wheeler (Mary L. Wheeler, New Smyrna
--     Beach, pro se, Volusia-area case) -- coincidental party-name overlap
--     only (Wilmington Savings Fund Society FSB is a national plaintiff
--     appearing in thousands of unrelated cases), not evidence of a link.
--     CONCLUSION: genuine owner-name mismatch stands. NOT enriched.
--
--   2026-CA-000090 (MCLEAN) -- RESOLVED. mcp__brightdata__scrape_as_markdown
--     of https://trellis.law/doc/274533071/13-summons-summons-request-for-
--     issuance-unofficial returned the full unofficial-preview text of a
--     real Sumter County Circuit Court summons (Filing #241635312,
--     e-filed 02/12/2026, IN THE CIRCUIT COURT OF THE FIFTH JUDICIAL CIRCUIT
--     IN AND FOR SUMTER COUNTY, FLORIDA): "WILMINGTON SAVINGS FUND SOCIETY,
--     FSB, AS TRUSTEE OF SARLES MORTGAGE LOAN TRUST" (plaintiff, matches our
--     DB's "WILMINGTON SAVINGS FUND SOCIETY FSB") vs. "UNKNOWN HEIRS
--     BENEFICIARIES ... AGAINST, ROBERTA MULKEY FRISKE, DECEASED; et al."
--     The case's Parties block explicitly lists "Mary Catherine McLean a/k/a
--     Mary McLean" as a named Defendant, alongside John David Friske Jr.,
--     Mildred Ann Stoke, North Sumter County Utility Development District,
--     and Sumter Landing Community Development District (both CDDs --
--     confirming the property sits inside The Villages' special-district
--     footprint, not standard county zoning). The summons itself commands
--     service on "UNKNOWN TENANT #1 / 1697 Pennecamp Drive / The Villages,
--     FL 32162" -- EXACT match to the address independently scraped this
--     session (via WebFetch) from the live sumterclerk.com page for case
--     2026-CA-000090. This resolves the prior session's "name mismatch":
--     Roberta Mulkey Friske (deceased) is the record owner (DOR OWN_NAME
--     "FRISKE ROBERTA M", matching the prior session's D28E030 geocode);
--     Mary McLean is a genuine named heir-defendant at that exact property in
--     this exact case, not an unrelated person. Cross-confirmed via 2
--     independent sources (sumterclerk.com live address field + Trellis.law
--     court filing), consistent with this campaign's 2-source standard.
--     Re-geocoded 1697 PENNECAMP DRIVE, THE VILLAGES, FL 32162 via the free
--     US Census geocoder (geocoding.geo.census.gov, Public_AR_Current
--     benchmark): exact TIGER-line address-range match, coordinates
--     (28.89284657597, -82.010715164002).
--
--     WRITE APPLIED (via PostgREST PATCH to multi_county_auctions, verified
--     by re-SELECT immediately after -- no drift, re-confirmed again after a
--     transient Supabase 521 blip resolved):
--       id=548b963d-3ce1-457f-b75b-011c68f70ba0 (case 2026-CA-000090):
--         parcel_id='D28E030' (carried over from the prior session's own
--           geocode+point-in-polygon finding against Sumter County ArcGIS --
--           NOT re-derived from scratch, since the parcel itself was never in
--           question, only the owner-name attribution),
--         property_address='1697 PENNECAMP DRIVE, THE VILLAGES, FL 32162',
--         latitude=28.89284657597, longitude=-82.010715164002,
--         owner_name='FRISKE ROBERTA M (DECEASED) - MARY CATHERINE MCLEAN
--           A/K/A MARY MCLEAN, NAMED HEIR-DEFENDANT',
--         data_source='sumterclerk_address_field_2026-08-27 +
--           brightdata_trellis_summons_274533071_wilmington_v_unknown_heirs_
--           friske + sumter_arcgis_geocode_D28E030 + census_geocoder'
--       assessed_value / market_value: NOT written. Searched sumterpa.com,
--         taxnetusa.com, assessorsearch.com, flpropertyappraiser.org for a
--         Sumter PA tax-roll figure specific to this parcel/address -- none
--         surfaced (only Redfin/Homes.com AVM "estimated value" figures,
--         which are litmus-only under this campaign's own PropertyOnion-
--         analog guardrail and were correctly NOT written as assessed_value).
--         This is why J did not move for this row (J requires the value
--         triangle + two-arm CMA + ml_score + max_bid, not just parcel
--         linkage).
--
--   2026-CA-000129 (STRONG v. YOUNG) -- STILL DEAD, RE-CONFIRMED. An initial
--     search_engine Google snippet appeared to attach an address to this row
--     under a different case number (2025-CA-000475, Florida Credit Union v.
--     Larry Wilkinson) due to SERP snippet concatenation across adjacent grid
--     rows -- a false lead, caught by cross-checking against a direct
--     WebFetch of the live page. WebFetch confirmed, verbatim: "Row 1 -
--     KENNETH STRONG -VS- JOHNATHON YOUNG: Status scheduled, Sale Date
--     10/01/2026, Case Number 2026-CA-000129, Judgement Amount $249,174.17"
--     and explicitly "no address listed" -- this is a genuinely separate row
--     from 2025-CA-000475 (Wilkinson), which DOES have an address
--     (4578 COUNTY ROAD 116, WILDWOOD, FL) but is not our case. No Trellis.law
--     filing for "Johnathon Young" + Sumter, or "Kenneth Strong" as plaintiff,
--     surfaced any case document (search_engine_batch: 0 relevant Trellis
--     hits, only unrelated same-named individuals in Suwannee County news
--     archives and generic people-search noise). CONCLUSION: still no
--     independent lever reaches this row. NOT enriched.
--
-- RESULT (VERIFIED live, pencil_dod_evaluate_county('sumter'), before AND
-- after this session's write):
--   BEFORE: E=90.6% (29/32) FAIL, I=87.5% (28/32) FAIL, J=90.6% (29/32) FAIL.
--   AFTER:  E=93.8% (30/32) FAIL (still below >=95% threshold -- needs 31/32),
--           I=87.5% (28/32) FAIL (unchanged -- v_zoning_gold_standard_card has
--             no coverage for The Villages' CDD-governed parcels; Sumter
--             County's own DevelopmentServices/Development_Services MapServer
--             layers 5 and 10 (Unincorporated FLU / Unincorporated Zoning)
--             both returned zero features at the D28E030 centroid -- The
--             Villages is served by Community Development Districts, not
--             standard county unincorporated zoning, so this parcel has no
--             genuine zone_code to write, confirmed live via point-in-polygon
--             query, not assumed),
--           J=90.6% (29/32) FAIL (unchanged -- no authoritative assessed/
--             market value source found for the newly-linked parcel).
--
-- NEXT-SESSION LEVERS (genuinely untried after this session):
--   1. A Turnstile-solving capability would still unblock
--      civitekflorida.com/ocrs/county/60 and myfloridacounty.com/orisearch/60
--      for 2026-CA-000074 (Ratliff) and 2026-CA-000129 (Strong/Young) --
--      unchanged from the prior version of this file.
--   2. For 2026-CA-000090 (McLean/Friske), a Sumter County Property Appraiser
--      direct parcel-account lookup (sumterpa.com, currently Cloudflare-
--      gated per qPublic/Schneider block class) would supply the missing
--      assessed_value/market_value needed to move J. This is the SAME
--      Cloudflare block already documented, not a new lever -- flagging it
--      here only because the parcel is now confirmed and only the value
--      figure is missing.
--   3. Direct phone/manual contact with the Sumter Clerk's office for the
--      case caption/legal description on 2026-CA-000074 and 2026-CA-000129
--      remains outside this session's autonomous scope.
--
-- (No SQL to run -- this file is a documentation-only record. The one live
-- write this session was applied directly via PostgREST PATCH, not via this
-- file.)

SELECT 1;
