-- Gold Standard shard6 run5361 sarasota G+I zoning fix (2026-07-20)
--
-- Sources (VERIFIED live GIS point-in-polygon, run this session):
--   North Port (jurisdiction_id=941): npgis.northportfl.gov/cnpserver/rest/services/Hosted/Current_Zoning/FeatureServer/241
--     Fields used: zone_abbr, zone_des. Real per-parcel polygon query, inSR=4326 WGS84.
--   Sarasota County unincorporated (jurisdiction_id=824): ags3.scgov.net/server/rest/services/Hosted/CountyZoning/FeatureServer/0
--     Fields used: zoningcode, zoninggroup. Real per-parcel polygon query, inSR=4326 WGS84.
--     (This is the same countywide layer that also covers CS/CV/CNP/TLK municipal boundaries, but only
--      publishes real zone codes for municipality='SC' i.e. unincorporated county; incorporated cities'
--      zoningcode field there is a placeholder ("SARASOTA"/"VENICE"/"NORTH PORT") pointing at the city's
--      own layer instead.)
--
-- Venice (jurisdiction_id=933) explicitly SKIPPED this run: found a real MapServer
--   (geoport.venicefl.gov/server/rest/services/pz/Zoning/MapServer/1, fields LDR_Zoning/zoning_district/ACCOUNT)
--   and confirmed it returns real per-parcel zoning, but the only 2 Sarasota-county auction parcels whose
--   lat/lng fall inside Venice's city boundary both point-in-polygon matched to a DIFFERENT tax ACCOUNT than
--   their own parcel_id (condo/platted-lot centroid vs unit mismatch) -- one landed on a "RECREATION" parcel
--   for a residential condo unit, which is a clear geometry artifact, not a real zone assignment. Per the
--   BLANK > WRONG rule these 2 are left out rather than inserting a low-confidence/likely-wrong match.
--
-- zone_standards (max_far / max_density_du_acre / parking_per_1000sf) intentionally NOT populated this run.
--   Every attempted primary-source lookup for exact dimensional/density tables was blocked or unavailable
--   this session: library.municode.com (Angular SPA, static fetch only returns the app shell; direct page
--   also 403s), scgov.net and northportfl.gov (Akamai edge 403 on both curl and WebFetch, confirmed not
--   UA-based), sarasotacounty.elaws.us (503, service down, retried 3x), Firecrawl (402 insufficient
--   credits), Zoneomics (no extractable data). The only zone_standards numbers already in the DB for this
--   county (Venice jurisdiction_id=933, 28 rows) have NULL source_url on every row -- an explicit
--   fabrication red flag per this session's brief -- and no independent source could corroborate the
--   specific values (e.g. RSF-3 max_far=0.21), so they were NOT built on or trusted as a baseline.
--   G (zoning FAR/density/parking coverage) is therefore expected to remain FAIL or only partially improved
--   after this migration -- the KPI view needs max_density_du_acre populated for residential parcels, which
--   this migration does not supply. This is an honest partial fix: real zone_code coverage via parcel_zones
--   (feeds I / property card completeness) without fabricated numeric standards (which G additionally needs).
--
-- One additional Sarasota-unincorporated auction row (2206 HAMMOCK PL, lat/lng present) was excluded from
--   parcel_zones because multi_county_auctions.parcel_id is NULL for that row -- there is nothing to join
--   it back to, so a parcel_zones row for it would be an orphan. 46 of the original 47 SC matches are used.

-- North Port (jurisdiction_id=941) zoning_districts: real codes from npgis.northportfl.gov Current_Zoning FeatureServer
INSERT INTO zoning_districts (jurisdiction_id, code, name, category) VALUES (941, 'AC-1', 'Activity Center 1', 'mixed-use') ON CONFLICT (jurisdiction_id, code) DO NOTHING;
INSERT INTO zoning_districts (jurisdiction_id, code, name, category) VALUES (941, 'AC-10', 'Activity Center 10', 'mixed-use') ON CONFLICT (jurisdiction_id, code) DO NOTHING;
INSERT INTO zoning_districts (jurisdiction_id, code, name, category) VALUES (941, 'AC-4', 'Activity Center 4', 'mixed-use') ON CONFLICT (jurisdiction_id, code) DO NOTHING;
INSERT INTO zoning_districts (jurisdiction_id, code, name, category) VALUES (941, 'AC-6', 'Activity Center 6', 'mixed-use') ON CONFLICT (jurisdiction_id, code) DO NOTHING;
INSERT INTO zoning_districts (jurisdiction_id, code, name, category) VALUES (941, 'AG', 'Agriculture', 'agricultural') ON CONFLICT (jurisdiction_id, code) DO NOTHING;
INSERT INTO zoning_districts (jurisdiction_id, code, name, category) VALUES (941, 'R-1', 'Residential, Low', 'residential') ON CONFLICT (jurisdiction_id, code) DO NOTHING;
INSERT INTO zoning_districts (jurisdiction_id, code, name, category) VALUES (941, 'R-2', 'Residential, Medium', 'residential') ON CONFLICT (jurisdiction_id, code) DO NOTHING;
INSERT INTO zoning_districts (jurisdiction_id, code, name, category) VALUES (941, 'V', 'Village', 'mixed-use') ON CONFLICT (jurisdiction_id, code) DO NOTHING;

-- Sarasota County unincorporated (jurisdiction_id=824) zoning_districts: real codes from ags3.scgov.net CountyZoning FeatureServer
INSERT INTO zoning_districts (jurisdiction_id, code, name, category) VALUES (824, 'CG', 'Commercial', 'commercial') ON CONFLICT (jurisdiction_id, code) DO NOTHING;
INSERT INTO zoning_districts (jurisdiction_id, code, name, category) VALUES (824, 'CSC', 'Commercial', 'commercial') ON CONFLICT (jurisdiction_id, code) DO NOTHING;
INSERT INTO zoning_districts (jurisdiction_id, code, name, category) VALUES (824, 'PID', 'Planned Commerce, Economic or Industrial Development', 'industrial') ON CONFLICT (jurisdiction_id, code) DO NOTHING;
INSERT INTO zoning_districts (jurisdiction_id, code, name, category) VALUES (824, 'RC', 'Residential Conservation, Estate, Planned Unit Development', 'residential') ON CONFLICT (jurisdiction_id, code) DO NOTHING;
INSERT INTO zoning_districts (jurisdiction_id, code, name, category) VALUES (824, 'RE-2/PUD', 'Residential Conservation, Estate, Planned Unit Development', 'residential') ON CONFLICT (jurisdiction_id, code) DO NOTHING;
INSERT INTO zoning_districts (jurisdiction_id, code, name, category) VALUES (824, 'RMF-1', 'Residential Multi-Family', 'residential') ON CONFLICT (jurisdiction_id, code) DO NOTHING;
INSERT INTO zoning_districts (jurisdiction_id, code, name, category) VALUES (824, 'RMF-2', 'Residential Multi-Family', 'residential') ON CONFLICT (jurisdiction_id, code) DO NOTHING;
INSERT INTO zoning_districts (jurisdiction_id, code, name, category) VALUES (824, 'RMF-2/PUD', 'Residential Multi-Family', 'residential') ON CONFLICT (jurisdiction_id, code) DO NOTHING;
INSERT INTO zoning_districts (jurisdiction_id, code, name, category) VALUES (824, 'RMF-2/SKOD', 'Residential Multi-Family', 'residential') ON CONFLICT (jurisdiction_id, code) DO NOTHING;
INSERT INTO zoning_districts (jurisdiction_id, code, name, category) VALUES (824, 'RMF-3/SKOD', 'Residential Multi-Family', 'residential') ON CONFLICT (jurisdiction_id, code) DO NOTHING;
INSERT INTO zoning_districts (jurisdiction_id, code, name, category) VALUES (824, 'RMH', 'Residential Mobile Home', 'residential') ON CONFLICT (jurisdiction_id, code) DO NOTHING;
INSERT INTO zoning_districts (jurisdiction_id, code, name, category) VALUES (824, 'RSF-1/PUD', 'Residential Single Family', 'residential') ON CONFLICT (jurisdiction_id, code) DO NOTHING;
INSERT INTO zoning_districts (jurisdiction_id, code, name, category) VALUES (824, 'RSF-2', 'Residential Single Family', 'residential') ON CONFLICT (jurisdiction_id, code) DO NOTHING;
INSERT INTO zoning_districts (jurisdiction_id, code, name, category) VALUES (824, 'RSF-2/PUD', 'Residential Single Family', 'residential') ON CONFLICT (jurisdiction_id, code) DO NOTHING;
INSERT INTO zoning_districts (jurisdiction_id, code, name, category) VALUES (824, 'RSF-2/SKOD', 'Residential Single Family', 'residential') ON CONFLICT (jurisdiction_id, code) DO NOTHING;
INSERT INTO zoning_districts (jurisdiction_id, code, name, category) VALUES (824, 'RSF-3', 'Residential Single Family', 'residential') ON CONFLICT (jurisdiction_id, code) DO NOTHING;
INSERT INTO zoning_districts (jurisdiction_id, code, name, category) VALUES (824, 'RSF-3/PUD', 'Residential Single Family', 'residential') ON CONFLICT (jurisdiction_id, code) DO NOTHING;-- parcel_zones: North Port (941) — real point-in-polygon match vs npgis.northportfl.gov Current_Zoning FeatureServer
INSERT INTO parcel_zones (parcel_id, tax_account, jurisdiction_id, zone_code, zone_name, source) VALUES ('1003019502', '1003019502', 941, 'AC-10', 'Activity Center 10', 'northport_gis_arcgis') ON CONFLICT (tax_account, jurisdiction_id) DO NOTHING;
INSERT INTO parcel_zones (parcel_id, tax_account, jurisdiction_id, zone_code, zone_name, source) VALUES ('1149213411', '1149213411', 941, 'AC-10', 'Activity Center 10', 'northport_gis_arcgis') ON CONFLICT (tax_account, jurisdiction_id) DO NOTHING;
INSERT INTO parcel_zones (parcel_id, tax_account, jurisdiction_id, zone_code, zone_name, source) VALUES ('1150234105', '1150234105', 941, 'AC-10', 'Activity Center 10', 'northport_gis_arcgis') ON CONFLICT (tax_account, jurisdiction_id) DO NOTHING;
INSERT INTO parcel_zones (parcel_id, tax_account, jurisdiction_id, zone_code, zone_name, source) VALUES ('0937013811', '0937013811', 941, 'AG', 'Agriculture', 'northport_gis_arcgis') ON CONFLICT (tax_account, jurisdiction_id) DO NOTHING;
INSERT INTO parcel_zones (parcel_id, tax_account, jurisdiction_id, zone_code, zone_name, source) VALUES ('1150234026', '1150234026', 941, 'AC-10', 'Activity Center 10', 'northport_gis_arcgis') ON CONFLICT (tax_account, jurisdiction_id) DO NOTHING;
INSERT INTO parcel_zones (parcel_id, tax_account, jurisdiction_id, zone_code, zone_name, source) VALUES ('1134209638', '1134209638', 941, 'AC-10', 'Activity Center 10', 'northport_gis_arcgis') ON CONFLICT (tax_account, jurisdiction_id) DO NOTHING;
INSERT INTO parcel_zones (parcel_id, tax_account, jurisdiction_id, zone_code, zone_name, source) VALUES ('1149216639', '1149216639', 941, 'AC-6', 'Activity Center 6', 'northport_gis_arcgis') ON CONFLICT (tax_account, jurisdiction_id) DO NOTHING;
INSERT INTO parcel_zones (parcel_id, tax_account, jurisdiction_id, zone_code, zone_name, source) VALUES ('0963079330', '0963079330', 941, 'R-1', 'Residential, Low', 'northport_gis_arcgis') ON CONFLICT (tax_account, jurisdiction_id) DO NOTHING;
INSERT INTO parcel_zones (parcel_id, tax_account, jurisdiction_id, zone_code, zone_name, source) VALUES ('0952125015', '0952125015', 941, 'R-1', 'Residential, Low', 'northport_gis_arcgis') ON CONFLICT (tax_account, jurisdiction_id) DO NOTHING;
INSERT INTO parcel_zones (parcel_id, tax_account, jurisdiction_id, zone_code, zone_name, source) VALUES ('1149216566', '1149216566', 941, 'AC-10', 'Activity Center 10', 'northport_gis_arcgis') ON CONFLICT (tax_account, jurisdiction_id) DO NOTHING;
INSERT INTO parcel_zones (parcel_id, tax_account, jurisdiction_id, zone_code, zone_name, source) VALUES ('1125229529', '1125229529', 941, 'AC-10', 'Activity Center 10', 'northport_gis_arcgis') ON CONFLICT (tax_account, jurisdiction_id) DO NOTHING;
INSERT INTO parcel_zones (parcel_id, tax_account, jurisdiction_id, zone_code, zone_name, source) VALUES ('1150206209', '1150206209', 941, 'AC-10', 'Activity Center 10', 'northport_gis_arcgis') ON CONFLICT (tax_account, jurisdiction_id) DO NOTHING;
INSERT INTO parcel_zones (parcel_id, tax_account, jurisdiction_id, zone_code, zone_name, source) VALUES ('1150206515', '1150206515', 941, 'AC-10', 'Activity Center 10', 'northport_gis_arcgis') ON CONFLICT (tax_account, jurisdiction_id) DO NOTHING;
INSERT INTO parcel_zones (parcel_id, tax_account, jurisdiction_id, zone_code, zone_name, source) VALUES ('1132211612', '1132211612', 941, 'AC-6', 'Activity Center 6', 'northport_gis_arcgis') ON CONFLICT (tax_account, jurisdiction_id) DO NOTHING;
INSERT INTO parcel_zones (parcel_id, tax_account, jurisdiction_id, zone_code, zone_name, source) VALUES ('1150234602', '1150234602', 941, 'V', 'Village', 'northport_gis_arcgis') ON CONFLICT (tax_account, jurisdiction_id) DO NOTHING;
INSERT INTO parcel_zones (parcel_id, tax_account, jurisdiction_id, zone_code, zone_name, source) VALUES ('1130219229', '1130219229', 941, 'AC-10', 'Activity Center 10', 'northport_gis_arcgis') ON CONFLICT (tax_account, jurisdiction_id) DO NOTHING;
INSERT INTO parcel_zones (parcel_id, tax_account, jurisdiction_id, zone_code, zone_name, source) VALUES ('1148203825', '1148203825', 941, 'R-1', 'Residential, Low', 'northport_gis_arcgis') ON CONFLICT (tax_account, jurisdiction_id) DO NOTHING;
INSERT INTO parcel_zones (parcel_id, tax_account, jurisdiction_id, zone_code, zone_name, source) VALUES ('1003008015', '1003008015', 941, 'AC-10', 'Activity Center 10', 'northport_gis_arcgis') ON CONFLICT (tax_account, jurisdiction_id) DO NOTHING;
INSERT INTO parcel_zones (parcel_id, tax_account, jurisdiction_id, zone_code, zone_name, source) VALUES ('1147203410', '1147203410', 941, 'R-1', 'Residential, Low', 'northport_gis_arcgis') ON CONFLICT (tax_account, jurisdiction_id) DO NOTHING;
INSERT INTO parcel_zones (parcel_id, tax_account, jurisdiction_id, zone_code, zone_name, source) VALUES ('1150233804', '1150233804', 941, 'AC-10', 'Activity Center 10', 'northport_gis_arcgis') ON CONFLICT (tax_account, jurisdiction_id) DO NOTHING;
INSERT INTO parcel_zones (parcel_id, tax_account, jurisdiction_id, zone_code, zone_name, source) VALUES ('1149216520', '1149216520', 941, 'AC-6', 'Activity Center 6', 'northport_gis_arcgis') ON CONFLICT (tax_account, jurisdiction_id) DO NOTHING;
INSERT INTO parcel_zones (parcel_id, tax_account, jurisdiction_id, zone_code, zone_name, source) VALUES ('1142257306', '1142257306', 941, 'R-1', 'Residential, Low', 'northport_gis_arcgis') ON CONFLICT (tax_account, jurisdiction_id) DO NOTHING;
INSERT INTO parcel_zones (parcel_id, tax_account, jurisdiction_id, zone_code, zone_name, source) VALUES ('0965092918', '0965092918', 941, 'R-2', 'Residential, Medium', 'northport_gis_arcgis') ON CONFLICT (tax_account, jurisdiction_id) DO NOTHING;
INSERT INTO parcel_zones (parcel_id, tax_account, jurisdiction_id, zone_code, zone_name, source) VALUES ('1128224503', '1128224503', 941, 'R-1', 'Residential, Low', 'northport_gis_arcgis') ON CONFLICT (tax_account, jurisdiction_id) DO NOTHING;
INSERT INTO parcel_zones (parcel_id, tax_account, jurisdiction_id, zone_code, zone_name, source) VALUES ('0106031050', '0106031050', 941, 'R-1', 'Residential, Low', 'northport_gis_arcgis') ON CONFLICT (tax_account, jurisdiction_id) DO NOTHING;
INSERT INTO parcel_zones (parcel_id, tax_account, jurisdiction_id, zone_code, zone_name, source) VALUES ('0970061808', '0970061808', 941, 'R-1', 'Residential, Low', 'northport_gis_arcgis') ON CONFLICT (tax_account, jurisdiction_id) DO NOTHING;
INSERT INTO parcel_zones (parcel_id, tax_account, jurisdiction_id, zone_code, zone_name, source) VALUES ('0443061145', '0443061145', 941, 'R-1', 'Residential, Low', 'northport_gis_arcgis') ON CONFLICT (tax_account, jurisdiction_id) DO NOTHING;
INSERT INTO parcel_zones (parcel_id, tax_account, jurisdiction_id, zone_code, zone_name, source) VALUES ('0849160008', '0849160008', 941, 'R-1', 'Residential, Low', 'northport_gis_arcgis') ON CONFLICT (tax_account, jurisdiction_id) DO NOTHING;
INSERT INTO parcel_zones (parcel_id, tax_account, jurisdiction_id, zone_code, zone_name, source) VALUES ('1149211742', '1149211742', 941, 'R-1', 'Residential, Low', 'northport_gis_arcgis') ON CONFLICT (tax_account, jurisdiction_id) DO NOTHING;
INSERT INTO parcel_zones (parcel_id, tax_account, jurisdiction_id, zone_code, zone_name, source) VALUES ('1150234503', '1150234503', 941, 'AC-10', 'Activity Center 10', 'northport_gis_arcgis') ON CONFLICT (tax_account, jurisdiction_id) DO NOTHING;
INSERT INTO parcel_zones (parcel_id, tax_account, jurisdiction_id, zone_code, zone_name, source) VALUES ('0443141031', '0443141031', 941, 'AC-1', 'Activity Center 1', 'northport_gis_arcgis') ON CONFLICT (tax_account, jurisdiction_id) DO NOTHING;
INSERT INTO parcel_zones (parcel_id, tax_account, jurisdiction_id, zone_code, zone_name, source) VALUES ('1149216412', '1149216412', 941, 'AC-10', 'Activity Center 10', 'northport_gis_arcgis') ON CONFLICT (tax_account, jurisdiction_id) DO NOTHING;
INSERT INTO parcel_zones (parcel_id, tax_account, jurisdiction_id, zone_code, zone_name, source) VALUES ('0956144909', '0956144909', 941, 'R-1', 'Residential, Low', 'northport_gis_arcgis') ON CONFLICT (tax_account, jurisdiction_id) DO NOTHING;
INSERT INTO parcel_zones (parcel_id, tax_account, jurisdiction_id, zone_code, zone_name, source) VALUES ('1132213428', '1132213428', 941, 'AC-6', 'Activity Center 6', 'northport_gis_arcgis') ON CONFLICT (tax_account, jurisdiction_id) DO NOTHING;
INSERT INTO parcel_zones (parcel_id, tax_account, jurisdiction_id, zone_code, zone_name, source) VALUES ('1152236614', '1152236614', 941, 'AC-10', 'Activity Center 10', 'northport_gis_arcgis') ON CONFLICT (tax_account, jurisdiction_id) DO NOTHING;
INSERT INTO parcel_zones (parcel_id, tax_account, jurisdiction_id, zone_code, zone_name, source) VALUES ('0961089204', '0961089204', 941, 'R-1', 'Residential, Low', 'northport_gis_arcgis') ON CONFLICT (tax_account, jurisdiction_id) DO NOTHING;
INSERT INTO parcel_zones (parcel_id, tax_account, jurisdiction_id, zone_code, zone_name, source) VALUES ('1132211317', '1132211317', 941, 'R-1', 'Residential, Low', 'northport_gis_arcgis') ON CONFLICT (tax_account, jurisdiction_id) DO NOTHING;
INSERT INTO parcel_zones (parcel_id, tax_account, jurisdiction_id, zone_code, zone_name, source) VALUES ('1147201309', '1147201309', 941, 'AC-10', 'Activity Center 10', 'northport_gis_arcgis') ON CONFLICT (tax_account, jurisdiction_id) DO NOTHING;
INSERT INTO parcel_zones (parcel_id, tax_account, jurisdiction_id, zone_code, zone_name, source) VALUES ('1125230916', '1125230916', 941, 'R-1', 'Residential, Low', 'northport_gis_arcgis') ON CONFLICT (tax_account, jurisdiction_id) DO NOTHING;
INSERT INTO parcel_zones (parcel_id, tax_account, jurisdiction_id, zone_code, zone_name, source) VALUES ('1147203816', '1147203816', 941, 'AC-6', 'Activity Center 6', 'northport_gis_arcgis') ON CONFLICT (tax_account, jurisdiction_id) DO NOTHING;
INSERT INTO parcel_zones (parcel_id, tax_account, jurisdiction_id, zone_code, zone_name, source) VALUES ('1149213639', '1149213639', 941, 'AC-10', 'Activity Center 10', 'northport_gis_arcgis') ON CONFLICT (tax_account, jurisdiction_id) DO NOTHING;
INSERT INTO parcel_zones (parcel_id, tax_account, jurisdiction_id, zone_code, zone_name, source) VALUES ('1132212422', '1132212422', 941, 'R-1', 'Residential, Low', 'northport_gis_arcgis') ON CONFLICT (tax_account, jurisdiction_id) DO NOTHING;
INSERT INTO parcel_zones (parcel_id, tax_account, jurisdiction_id, zone_code, zone_name, source) VALUES ('0953152423', '0953152423', 941, 'R-1', 'Residential, Low', 'northport_gis_arcgis') ON CONFLICT (tax_account, jurisdiction_id) DO NOTHING;
INSERT INTO parcel_zones (parcel_id, tax_account, jurisdiction_id, zone_code, zone_name, source) VALUES ('1152236618', '1152236618', 941, 'AC-10', 'Activity Center 10', 'northport_gis_arcgis') ON CONFLICT (tax_account, jurisdiction_id) DO NOTHING;
INSERT INTO parcel_zones (parcel_id, tax_account, jurisdiction_id, zone_code, zone_name, source) VALUES ('1123232219', '1123232219', 941, 'R-2', 'Residential, Medium', 'northport_gis_arcgis') ON CONFLICT (tax_account, jurisdiction_id) DO NOTHING;
INSERT INTO parcel_zones (parcel_id, tax_account, jurisdiction_id, zone_code, zone_name, source) VALUES ('1126207431', '1126207431', 941, 'R-1', 'Residential, Low', 'northport_gis_arcgis') ON CONFLICT (tax_account, jurisdiction_id) DO NOTHING;
INSERT INTO parcel_zones (parcel_id, tax_account, jurisdiction_id, zone_code, zone_name, source) VALUES ('1152235711', '1152235711', 941, 'AC-10', 'Activity Center 10', 'northport_gis_arcgis') ON CONFLICT (tax_account, jurisdiction_id) DO NOTHING;
INSERT INTO parcel_zones (parcel_id, tax_account, jurisdiction_id, zone_code, zone_name, source) VALUES ('0955071148', '0955071148', 941, 'R-1', 'Residential, Low', 'northport_gis_arcgis') ON CONFLICT (tax_account, jurisdiction_id) DO NOTHING;
INSERT INTO parcel_zones (parcel_id, tax_account, jurisdiction_id, zone_code, zone_name, source) VALUES ('0953151403', '0953151403', 941, 'R-1', 'Residential, Low', 'northport_gis_arcgis') ON CONFLICT (tax_account, jurisdiction_id) DO NOTHING;
INSERT INTO parcel_zones (parcel_id, tax_account, jurisdiction_id, zone_code, zone_name, source) VALUES ('0770160007', '0770160007', 941, 'AC-10', 'Activity Center 10', 'northport_gis_arcgis') ON CONFLICT (tax_account, jurisdiction_id) DO NOTHING;
INSERT INTO parcel_zones (parcel_id, tax_account, jurisdiction_id, zone_code, zone_name, source) VALUES ('1145098309', '1145098309', 941, 'R-1', 'Residential, Low', 'northport_gis_arcgis') ON CONFLICT (tax_account, jurisdiction_id) DO NOTHING;
INSERT INTO parcel_zones (parcel_id, tax_account, jurisdiction_id, zone_code, zone_name, source) VALUES ('1147110010', '1147110010', 941, 'R-1', 'Residential, Low', 'northport_gis_arcgis') ON CONFLICT (tax_account, jurisdiction_id) DO NOTHING;
INSERT INTO parcel_zones (parcel_id, tax_account, jurisdiction_id, zone_code, zone_name, source) VALUES ('1147203012', '1147203012', 941, 'AC-10', 'Activity Center 10', 'northport_gis_arcgis') ON CONFLICT (tax_account, jurisdiction_id) DO NOTHING;
INSERT INTO parcel_zones (parcel_id, tax_account, jurisdiction_id, zone_code, zone_name, source) VALUES ('1150206206', '1150206206', 941, 'AC-6', 'Activity Center 6', 'northport_gis_arcgis') ON CONFLICT (tax_account, jurisdiction_id) DO NOTHING;
INSERT INTO parcel_zones (parcel_id, tax_account, jurisdiction_id, zone_code, zone_name, source) VALUES ('1147200501', '1147200501', 941, 'R-1', 'Residential, Low', 'northport_gis_arcgis') ON CONFLICT (tax_account, jurisdiction_id) DO NOTHING;
INSERT INTO parcel_zones (parcel_id, tax_account, jurisdiction_id, zone_code, zone_name, source) VALUES ('0970062021', '0970062021', 941, 'R-1', 'Residential, Low', 'northport_gis_arcgis') ON CONFLICT (tax_account, jurisdiction_id) DO NOTHING;
INSERT INTO parcel_zones (parcel_id, tax_account, jurisdiction_id, zone_code, zone_name, source) VALUES ('1149214302', '1149214302', 941, 'AC-6', 'Activity Center 6', 'northport_gis_arcgis') ON CONFLICT (tax_account, jurisdiction_id) DO NOTHING;
INSERT INTO parcel_zones (parcel_id, tax_account, jurisdiction_id, zone_code, zone_name, source) VALUES ('0957070114', '0957070114', 941, 'AC-10', 'Activity Center 10', 'northport_gis_arcgis') ON CONFLICT (tax_account, jurisdiction_id) DO NOTHING;
INSERT INTO parcel_zones (parcel_id, tax_account, jurisdiction_id, zone_code, zone_name, source) VALUES ('0021080007', '0021080007', 941, 'R-1', 'Residential, Low', 'northport_gis_arcgis') ON CONFLICT (tax_account, jurisdiction_id) DO NOTHING;
INSERT INTO parcel_zones (parcel_id, tax_account, jurisdiction_id, zone_code, zone_name, source) VALUES ('0970063416', '0970063416', 941, 'R-1', 'Residential, Low', 'northport_gis_arcgis') ON CONFLICT (tax_account, jurisdiction_id) DO NOTHING;
INSERT INTO parcel_zones (parcel_id, tax_account, jurisdiction_id, zone_code, zone_name, source) VALUES ('1150234315', '1150234315', 941, 'AC-10', 'Activity Center 10', 'northport_gis_arcgis') ON CONFLICT (tax_account, jurisdiction_id) DO NOTHING;
INSERT INTO parcel_zones (parcel_id, tax_account, jurisdiction_id, zone_code, zone_name, source) VALUES ('1133209241', '1133209241', 941, 'R-1', 'Residential, Low', 'northport_gis_arcgis') ON CONFLICT (tax_account, jurisdiction_id) DO NOTHING;
INSERT INTO parcel_zones (parcel_id, tax_account, jurisdiction_id, zone_code, zone_name, source) VALUES ('0958067119', '0958067119', 941, 'R-1', 'Residential, Low', 'northport_gis_arcgis') ON CONFLICT (tax_account, jurisdiction_id) DO NOTHING;
INSERT INTO parcel_zones (parcel_id, tax_account, jurisdiction_id, zone_code, zone_name, source) VALUES ('1148204807', '1148204807', 941, 'AC-10', 'Activity Center 10', 'northport_gis_arcgis') ON CONFLICT (tax_account, jurisdiction_id) DO NOTHING;
INSERT INTO parcel_zones (parcel_id, tax_account, jurisdiction_id, zone_code, zone_name, source) VALUES ('0960114604', '0960114604', 941, 'AG', 'Agriculture', 'northport_gis_arcgis') ON CONFLICT (tax_account, jurisdiction_id) DO NOTHING;
INSERT INTO parcel_zones (parcel_id, tax_account, jurisdiction_id, zone_code, zone_name, source) VALUES ('1149216506', '1149216506', 941, 'AC-10', 'Activity Center 10', 'northport_gis_arcgis') ON CONFLICT (tax_account, jurisdiction_id) DO NOTHING;
INSERT INTO parcel_zones (parcel_id, tax_account, jurisdiction_id, zone_code, zone_name, source) VALUES ('0959117001', '0959117001', 941, 'AC-6', 'Activity Center 6', 'northport_gis_arcgis') ON CONFLICT (tax_account, jurisdiction_id) DO NOTHING;
INSERT INTO parcel_zones (parcel_id, tax_account, jurisdiction_id, zone_code, zone_name, source) VALUES ('1116070136', '1116070136', 941, 'AC-4', 'Activity Center 4', 'northport_gis_arcgis') ON CONFLICT (tax_account, jurisdiction_id) DO NOTHING;
INSERT INTO parcel_zones (parcel_id, tax_account, jurisdiction_id, zone_code, zone_name, source) VALUES ('0969062005', '0969062005', 941, 'R-1', 'Residential, Low', 'northport_gis_arcgis') ON CONFLICT (tax_account, jurisdiction_id) DO NOTHING;
INSERT INTO parcel_zones (parcel_id, tax_account, jurisdiction_id, zone_code, zone_name, source) VALUES ('1131208715', '1131208715', 941, 'AC-6', 'Activity Center 6', 'northport_gis_arcgis') ON CONFLICT (tax_account, jurisdiction_id) DO NOTHING;
INSERT INTO parcel_zones (parcel_id, tax_account, jurisdiction_id, zone_code, zone_name, source) VALUES ('1149213208', '1149213208', 941, 'AC-10', 'Activity Center 10', 'northport_gis_arcgis') ON CONFLICT (tax_account, jurisdiction_id) DO NOTHING;
INSERT INTO parcel_zones (parcel_id, tax_account, jurisdiction_id, zone_code, zone_name, source) VALUES ('1148203702', '1148203702', 941, 'R-1', 'Residential, Low', 'northport_gis_arcgis') ON CONFLICT (tax_account, jurisdiction_id) DO NOTHING;
INSERT INTO parcel_zones (parcel_id, tax_account, jurisdiction_id, zone_code, zone_name, source) VALUES ('1132212210', '1132212210', 941, 'R-1', 'Residential, Low', 'northport_gis_arcgis') ON CONFLICT (tax_account, jurisdiction_id) DO NOTHING;
INSERT INTO parcel_zones (parcel_id, tax_account, jurisdiction_id, zone_code, zone_name, source) VALUES ('1147201415', '1147201415', 941, 'AC-6', 'Activity Center 6', 'northport_gis_arcgis') ON CONFLICT (tax_account, jurisdiction_id) DO NOTHING;
INSERT INTO parcel_zones (parcel_id, tax_account, jurisdiction_id, zone_code, zone_name, source) VALUES ('0079121032', '0079121032', 941, 'AC-4', 'Activity Center 4', 'northport_gis_arcgis') ON CONFLICT (tax_account, jurisdiction_id) DO NOTHING;
INSERT INTO parcel_zones (parcel_id, tax_account, jurisdiction_id, zone_code, zone_name, source) VALUES ('1130222114', '1130222114', 941, 'AC-6', 'Activity Center 6', 'northport_gis_arcgis') ON CONFLICT (tax_account, jurisdiction_id) DO NOTHING;
INSERT INTO parcel_zones (parcel_id, tax_account, jurisdiction_id, zone_code, zone_name, source) VALUES ('1128227311', '1128227311', 941, 'R-1', 'Residential, Low', 'northport_gis_arcgis') ON CONFLICT (tax_account, jurisdiction_id) DO NOTHING;
INSERT INTO parcel_zones (parcel_id, tax_account, jurisdiction_id, zone_code, zone_name, source) VALUES ('1147205623', '1147205623', 941, 'R-1', 'Residential, Low', 'northport_gis_arcgis') ON CONFLICT (tax_account, jurisdiction_id) DO NOTHING;
INSERT INTO parcel_zones (parcel_id, tax_account, jurisdiction_id, zone_code, zone_name, source) VALUES ('0361001005', '0361001005', 941, 'R-1', 'Residential, Low', 'northport_gis_arcgis') ON CONFLICT (tax_account, jurisdiction_id) DO NOTHING;
INSERT INTO parcel_zones (parcel_id, tax_account, jurisdiction_id, zone_code, zone_name, source) VALUES ('1124106725', '1124106725', 941, 'AC-10', 'Activity Center 10', 'northport_gis_arcgis') ON CONFLICT (tax_account, jurisdiction_id) DO NOTHING;
INSERT INTO parcel_zones (parcel_id, tax_account, jurisdiction_id, zone_code, zone_name, source) VALUES ('0969062025', '0969062025', 941, 'AC-10', 'Activity Center 10', 'northport_gis_arcgis') ON CONFLICT (tax_account, jurisdiction_id) DO NOTHING;
INSERT INTO parcel_zones (parcel_id, tax_account, jurisdiction_id, zone_code, zone_name, source) VALUES ('1147205624', '1147205624', 941, 'AC-10', 'Activity Center 10', 'northport_gis_arcgis') ON CONFLICT (tax_account, jurisdiction_id) DO NOTHING;
INSERT INTO parcel_zones (parcel_id, tax_account, jurisdiction_id, zone_code, zone_name, source) VALUES ('1128226805', '1128226805', 941, 'AC-1', 'Activity Center 1', 'northport_gis_arcgis') ON CONFLICT (tax_account, jurisdiction_id) DO NOTHING;
INSERT INTO parcel_zones (parcel_id, tax_account, jurisdiction_id, zone_code, zone_name, source) VALUES ('1133207214', '1133207214', 941, 'AC-6', 'Activity Center 6', 'northport_gis_arcgis') ON CONFLICT (tax_account, jurisdiction_id) DO NOTHING;
INSERT INTO parcel_zones (parcel_id, tax_account, jurisdiction_id, zone_code, zone_name, source) VALUES ('1124106917', '1124106917', 941, 'R-1', 'Residential, Low', 'northport_gis_arcgis') ON CONFLICT (tax_account, jurisdiction_id) DO NOTHING;
INSERT INTO parcel_zones (parcel_id, tax_account, jurisdiction_id, zone_code, zone_name, source) VALUES ('1129221838', '1129221838', 941, 'AC-6', 'Activity Center 6', 'northport_gis_arcgis') ON CONFLICT (tax_account, jurisdiction_id) DO NOTHING;
INSERT INTO parcel_zones (parcel_id, tax_account, jurisdiction_id, zone_code, zone_name, source) VALUES ('0384100027', '0384100027', 941, 'AC-6', 'Activity Center 6', 'northport_gis_arcgis') ON CONFLICT (tax_account, jurisdiction_id) DO NOTHING;
INSERT INTO parcel_zones (parcel_id, tax_account, jurisdiction_id, zone_code, zone_name, source) VALUES ('0952123303', '0952123303', 941, 'R-1', 'Residential, Low', 'northport_gis_arcgis') ON CONFLICT (tax_account, jurisdiction_id) DO NOTHING;
INSERT INTO parcel_zones (parcel_id, tax_account, jurisdiction_id, zone_code, zone_name, source) VALUES ('1134201445', '1134201445', 941, 'R-1', 'Residential, Low', 'northport_gis_arcgis') ON CONFLICT (tax_account, jurisdiction_id) DO NOTHING;
INSERT INTO parcel_zones (parcel_id, tax_account, jurisdiction_id, zone_code, zone_name, source) VALUES ('1130219420', '1130219420', 941, 'AC-6', 'Activity Center 6', 'northport_gis_arcgis') ON CONFLICT (tax_account, jurisdiction_id) DO NOTHING;
INSERT INTO parcel_zones (parcel_id, tax_account, jurisdiction_id, zone_code, zone_name, source) VALUES ('0975061109', '0975061109', 941, 'R-1', 'Residential, Low', 'northport_gis_arcgis') ON CONFLICT (tax_account, jurisdiction_id) DO NOTHING;
INSERT INTO parcel_zones (parcel_id, tax_account, jurisdiction_id, zone_code, zone_name, source) VALUES ('1004019623', '1004019623', 941, 'R-1', 'Residential, Low', 'northport_gis_arcgis') ON CONFLICT (tax_account, jurisdiction_id) DO NOTHING;
INSERT INTO parcel_zones (parcel_id, tax_account, jurisdiction_id, zone_code, zone_name, source) VALUES ('1116070135', '1116070135', 941, 'R-1', 'Residential, Low', 'northport_gis_arcgis') ON CONFLICT (tax_account, jurisdiction_id) DO NOTHING;
INSERT INTO parcel_zones (parcel_id, tax_account, jurisdiction_id, zone_code, zone_name, source) VALUES ('1129221512', '1129221512', 941, 'AC-10', 'Activity Center 10', 'northport_gis_arcgis') ON CONFLICT (tax_account, jurisdiction_id) DO NOTHING;
INSERT INTO parcel_zones (parcel_id, tax_account, jurisdiction_id, zone_code, zone_name, source) VALUES ('0970061807', '0970061807', 941, 'AC-10', 'Activity Center 10', 'northport_gis_arcgis') ON CONFLICT (tax_account, jurisdiction_id) DO NOTHING;
INSERT INTO parcel_zones (parcel_id, tax_account, jurisdiction_id, zone_code, zone_name, source) VALUES ('1149216707', '1149216707', 941, 'R-1', 'Residential, Low', 'northport_gis_arcgis') ON CONFLICT (tax_account, jurisdiction_id) DO NOTHING;
INSERT INTO parcel_zones (parcel_id, tax_account, jurisdiction_id, zone_code, zone_name, source) VALUES ('1150214802', '1150214802', 941, 'AC-10', 'Activity Center 10', 'northport_gis_arcgis') ON CONFLICT (tax_account, jurisdiction_id) DO NOTHING;

-- parcel_zones: Sarasota County unincorporated (824) — real point-in-polygon match vs ags3.scgov.net CountyZoning FeatureServer
INSERT INTO parcel_zones (parcel_id, tax_account, jurisdiction_id, zone_code, zone_name, source) VALUES ('0143020007', '0143020007', 824, 'RSF-2/SKOD', 'Residential Single Family', 'scgov_arcgis') ON CONFLICT (tax_account, jurisdiction_id) DO NOTHING;
INSERT INTO parcel_zones (parcel_id, tax_account, jurisdiction_id, zone_code, zone_name, source) VALUES ('0485101094', '0485101094', 824, 'RSF-1/PUD', 'Residential Single Family', 'scgov_arcgis') ON CONFLICT (tax_account, jurisdiction_id) DO NOTHING;
INSERT INTO parcel_zones (parcel_id, tax_account, jurisdiction_id, zone_code, zone_name, source) VALUES ('0854150011', '0854150011', 824, 'RSF-2', 'Residential Single Family', 'scgov_arcgis') ON CONFLICT (tax_account, jurisdiction_id) DO NOTHING;
INSERT INTO parcel_zones (parcel_id, tax_account, jurisdiction_id, zone_code, zone_name, source) VALUES ('0087040024', '0087040024', 824, 'RSF-3/PUD', 'Residential Single Family', 'scgov_arcgis') ON CONFLICT (tax_account, jurisdiction_id) DO NOTHING;
INSERT INTO parcel_zones (parcel_id, tax_account, jurisdiction_id, zone_code, zone_name, source) VALUES ('0982044420', '0982044420', 824, 'RMH', 'Residential Mobile Home', 'scgov_arcgis') ON CONFLICT (tax_account, jurisdiction_id) DO NOTHING;
INSERT INTO parcel_zones (parcel_id, tax_account, jurisdiction_id, zone_code, zone_name, source) VALUES ('0101042009', '0101042009', 824, 'CSC', 'Commercial', 'scgov_arcgis') ON CONFLICT (tax_account, jurisdiction_id) DO NOTHING;
INSERT INTO parcel_zones (parcel_id, tax_account, jurisdiction_id, zone_code, zone_name, source) VALUES ('2019140065', '2019140065', 824, 'RMF-2', 'Residential Multi-Family', 'scgov_arcgis') ON CONFLICT (tax_account, jurisdiction_id) DO NOTHING;
INSERT INTO parcel_zones (parcel_id, tax_account, jurisdiction_id, zone_code, zone_name, source) VALUES ('0132013318', '0132013318', 824, 'RSF-2/PUD', 'Residential Single Family', 'scgov_arcgis') ON CONFLICT (tax_account, jurisdiction_id) DO NOTHING;
INSERT INTO parcel_zones (parcel_id, tax_account, jurisdiction_id, zone_code, zone_name, source) VALUES ('0036121025', '0036121025', 824, 'RSF-2/PUD', 'Residential Single Family', 'scgov_arcgis') ON CONFLICT (tax_account, jurisdiction_id) DO NOTHING;
INSERT INTO parcel_zones (parcel_id, tax_account, jurisdiction_id, zone_code, zone_name, source) VALUES ('0086012004', '0086012004', 824, 'RSF-3', 'Residential Single Family', 'scgov_arcgis') ON CONFLICT (tax_account, jurisdiction_id) DO NOTHING;
INSERT INTO parcel_zones (parcel_id, tax_account, jurisdiction_id, zone_code, zone_name, source) VALUES ('0966053955', '0966053955', 824, 'RE-2/PUD', 'Residential Conservation, Estate, Planned Unit Development', 'scgov_arcgis') ON CONFLICT (tax_account, jurisdiction_id) DO NOTHING;
INSERT INTO parcel_zones (parcel_id, tax_account, jurisdiction_id, zone_code, zone_name, source) VALUES ('0974181228', '0974181228', 824, 'RSF-3', 'Residential Single Family', 'scgov_arcgis') ON CONFLICT (tax_account, jurisdiction_id) DO NOTHING;
INSERT INTO parcel_zones (parcel_id, tax_account, jurisdiction_id, zone_code, zone_name, source) VALUES ('0066151003', '0066151003', 824, 'RSF-3', 'Residential Single Family', 'scgov_arcgis') ON CONFLICT (tax_account, jurisdiction_id) DO NOTHING;
INSERT INTO parcel_zones (parcel_id, tax_account, jurisdiction_id, zone_code, zone_name, source) VALUES ('0095121041', '0095121041', 824, 'RSF-2/PUD', 'Residential Single Family', 'scgov_arcgis') ON CONFLICT (tax_account, jurisdiction_id) DO NOTHING;
INSERT INTO parcel_zones (parcel_id, tax_account, jurisdiction_id, zone_code, zone_name, source) VALUES ('0060050007', '0060050007', 824, 'RSF-2/SKOD', 'Residential Single Family', 'scgov_arcgis') ON CONFLICT (tax_account, jurisdiction_id) DO NOTHING;
INSERT INTO parcel_zones (parcel_id, tax_account, jurisdiction_id, zone_code, zone_name, source) VALUES ('0082122004', '0082122004', 824, 'CG', 'Commercial', 'scgov_arcgis') ON CONFLICT (tax_account, jurisdiction_id) DO NOTHING;
INSERT INTO parcel_zones (parcel_id, tax_account, jurisdiction_id, zone_code, zone_name, source) VALUES ('0790013372', '0790013372', 824, 'CG', 'Commercial', 'scgov_arcgis') ON CONFLICT (tax_account, jurisdiction_id) DO NOTHING;
INSERT INTO parcel_zones (parcel_id, tax_account, jurisdiction_id, zone_code, zone_name, source) VALUES ('0087040024', '0087040024', 824, 'RSF-3', 'Residential Single Family', 'scgov_arcgis') ON CONFLICT (tax_account, jurisdiction_id) DO NOTHING;
INSERT INTO parcel_zones (parcel_id, tax_account, jurisdiction_id, zone_code, zone_name, source) VALUES ('0082090030', '0082090030', 824, 'RMF-2', 'Residential Multi-Family', 'scgov_arcgis') ON CONFLICT (tax_account, jurisdiction_id) DO NOTHING;
INSERT INTO parcel_zones (parcel_id, tax_account, jurisdiction_id, zone_code, zone_name, source) VALUES ('0429111012', '0429111012', 824, 'RMF-2/SKOD', 'Residential Multi-Family', 'scgov_arcgis') ON CONFLICT (tax_account, jurisdiction_id) DO NOTHING;
INSERT INTO parcel_zones (parcel_id, tax_account, jurisdiction_id, zone_code, zone_name, source) VALUES ('0105041013', '0105041013', 824, 'CG', 'Commercial', 'scgov_arcgis') ON CONFLICT (tax_account, jurisdiction_id) DO NOTHING;
INSERT INTO parcel_zones (parcel_id, tax_account, jurisdiction_id, zone_code, zone_name, source) VALUES ('0124021214', '0124021214', 824, 'RSF-2/PUD', 'Residential Single Family', 'scgov_arcgis') ON CONFLICT (tax_account, jurisdiction_id) DO NOTHING;
INSERT INTO parcel_zones (parcel_id, tax_account, jurisdiction_id, zone_code, zone_name, source) VALUES ('1149215003', '1149215003', 824, 'RC', 'Residential Conservation, Estate, Planned Unit Development', 'scgov_arcgis') ON CONFLICT (tax_account, jurisdiction_id) DO NOTHING;
INSERT INTO parcel_zones (parcel_id, tax_account, jurisdiction_id, zone_code, zone_name, source) VALUES ('1148199807', '1148199807', 824, 'RSF-3', 'Residential Single Family', 'scgov_arcgis') ON CONFLICT (tax_account, jurisdiction_id) DO NOTHING;
INSERT INTO parcel_zones (parcel_id, tax_account, jurisdiction_id, zone_code, zone_name, source) VALUES ('0143020015', '0143020015', 824, 'RSF-3', 'Residential Single Family', 'scgov_arcgis') ON CONFLICT (tax_account, jurisdiction_id) DO NOTHING;
INSERT INTO parcel_zones (parcel_id, tax_account, jurisdiction_id, zone_code, zone_name, source) VALUES ('0997034950', '0997034950', 824, 'PID', 'Planned Commerce, Economic or Industrial Development', 'scgov_arcgis') ON CONFLICT (tax_account, jurisdiction_id) DO NOTHING;
INSERT INTO parcel_zones (parcel_id, tax_account, jurisdiction_id, zone_code, zone_name, source) VALUES ('0008143067', '0008143067', 824, 'RSF-2', 'Residential Single Family', 'scgov_arcgis') ON CONFLICT (tax_account, jurisdiction_id) DO NOTHING;
INSERT INTO parcel_zones (parcel_id, tax_account, jurisdiction_id, zone_code, zone_name, source) VALUES ('0036130005', '0036130005', 824, 'RSF-2/PUD', 'Residential Single Family', 'scgov_arcgis') ON CONFLICT (tax_account, jurisdiction_id) DO NOTHING;
INSERT INTO parcel_zones (parcel_id, tax_account, jurisdiction_id, zone_code, zone_name, source) VALUES ('0054140086', '0054140086', 824, 'RSF-3', 'Residential Single Family', 'scgov_arcgis') ON CONFLICT (tax_account, jurisdiction_id) DO NOTHING;
INSERT INTO parcel_zones (parcel_id, tax_account, jurisdiction_id, zone_code, zone_name, source) VALUES ('0061121016', '0061121016', 824, 'RSF-3', 'Residential Single Family', 'scgov_arcgis') ON CONFLICT (tax_account, jurisdiction_id) DO NOTHING;
INSERT INTO parcel_zones (parcel_id, tax_account, jurisdiction_id, zone_code, zone_name, source) VALUES ('0081050035', '0081050035', 824, 'RSF-2', 'Residential Single Family', 'scgov_arcgis') ON CONFLICT (tax_account, jurisdiction_id) DO NOTHING;
INSERT INTO parcel_zones (parcel_id, tax_account, jurisdiction_id, zone_code, zone_name, source) VALUES ('0850012004', '0850012004', 824, 'RMH', 'Residential Mobile Home', 'scgov_arcgis') ON CONFLICT (tax_account, jurisdiction_id) DO NOTHING;
INSERT INTO parcel_zones (parcel_id, tax_account, jurisdiction_id, zone_code, zone_name, source) VALUES ('1004021513', '1004021513', 824, 'RSF-2', 'Residential Single Family', 'scgov_arcgis') ON CONFLICT (tax_account, jurisdiction_id) DO NOTHING;
INSERT INTO parcel_zones (parcel_id, tax_account, jurisdiction_id, zone_code, zone_name, source) VALUES ('0106075611', '0106075611', 824, 'RMF-3/SKOD', 'Residential Multi-Family', 'scgov_arcgis') ON CONFLICT (tax_account, jurisdiction_id) DO NOTHING;
INSERT INTO parcel_zones (parcel_id, tax_account, jurisdiction_id, zone_code, zone_name, source) VALUES ('0789041302', '0789041302', 824, 'RMH', 'Residential Mobile Home', 'scgov_arcgis') ON CONFLICT (tax_account, jurisdiction_id) DO NOTHING;
INSERT INTO parcel_zones (parcel_id, tax_account, jurisdiction_id, zone_code, zone_name, source) VALUES ('0755021381', '0755021381', 824, 'RSF-1/PUD', 'Residential Single Family', 'scgov_arcgis') ON CONFLICT (tax_account, jurisdiction_id) DO NOTHING;
INSERT INTO parcel_zones (parcel_id, tax_account, jurisdiction_id, zone_code, zone_name, source) VALUES ('0069110028', '0069110028', 824, 'RMH', 'Residential Mobile Home', 'scgov_arcgis') ON CONFLICT (tax_account, jurisdiction_id) DO NOTHING;
INSERT INTO parcel_zones (parcel_id, tax_account, jurisdiction_id, zone_code, zone_name, source) VALUES ('0461092050', '0461092050', 824, 'RMF-2/PUD', 'Residential Multi-Family', 'scgov_arcgis') ON CONFLICT (tax_account, jurisdiction_id) DO NOTHING;
INSERT INTO parcel_zones (parcel_id, tax_account, jurisdiction_id, zone_code, zone_name, source) VALUES ('0070082013', '0070082013', 824, 'RSF-3', 'Residential Single Family', 'scgov_arcgis') ON CONFLICT (tax_account, jurisdiction_id) DO NOTHING;
INSERT INTO parcel_zones (parcel_id, tax_account, jurisdiction_id, zone_code, zone_name, source) VALUES ('0430050010', '0430050010', 824, 'RMF-3/SKOD', 'Residential Multi-Family', 'scgov_arcgis') ON CONFLICT (tax_account, jurisdiction_id) DO NOTHING;
INSERT INTO parcel_zones (parcel_id, tax_account, jurisdiction_id, zone_code, zone_name, source) VALUES ('0176111073', '0176111073', 824, 'RMF-3/SKOD', 'Residential Multi-Family', 'scgov_arcgis') ON CONFLICT (tax_account, jurisdiction_id) DO NOTHING;
INSERT INTO parcel_zones (parcel_id, tax_account, jurisdiction_id, zone_code, zone_name, source) VALUES ('0406040035', '0406040035', 824, 'RSF-3', 'Residential Single Family', 'scgov_arcgis') ON CONFLICT (tax_account, jurisdiction_id) DO NOTHING;
INSERT INTO parcel_zones (parcel_id, tax_account, jurisdiction_id, zone_code, zone_name, source) VALUES ('0485101166', '0485101166', 824, 'RSF-2', 'Residential Single Family', 'scgov_arcgis') ON CONFLICT (tax_account, jurisdiction_id) DO NOTHING;
INSERT INTO parcel_zones (parcel_id, tax_account, jurisdiction_id, zone_code, zone_name, source) VALUES ('0061052075', '0061052075', 824, 'RMF-1', 'Residential Multi-Family', 'scgov_arcgis') ON CONFLICT (tax_account, jurisdiction_id) DO NOTHING;
INSERT INTO parcel_zones (parcel_id, tax_account, jurisdiction_id, zone_code, zone_name, source) VALUES ('0035032028', '0035032028', 824, 'RSF-2/PUD', 'Residential Single Family', 'scgov_arcgis') ON CONFLICT (tax_account, jurisdiction_id) DO NOTHING;
INSERT INTO parcel_zones (parcel_id, tax_account, jurisdiction_id, zone_code, zone_name, source) VALUES ('0057091026', '0057091026', 824, 'RSF-2', 'Residential Single Family', 'scgov_arcgis') ON CONFLICT (tax_account, jurisdiction_id) DO NOTHING;