-- Gold Standard shard-8 (run3534, dispatch 0a395517): dixie REAL tax deed outcome harvest.
--
-- Root cause of dixie C/D=0%% (and the honest B/F=0%% after the fabrication revert in
-- migrations/20260710_gold_standard_shard8_dixie_fabrication_revert_completion.sql): the
-- committed scraper (scripts/shard6_dixie_scraper.py) parses dixieclerk.com via a
-- text/div BeautifulSoup approach, but the live tax-deed-sales page actually embeds its
-- data as a Vue component attribute (<tax-deed-sales :taxdeeds="[...]">), HTML-entity-
-- encoded JSON -- the div-text parser matches nothing against that structure. VERIFIED
-- live 2026-07-10: fetched https://dixieclerk.com/departments-services/court-services/
-- tax-deed-sales/ directly and decoded the embedded JSON: 31 real records with real cert
-- numbers, real distinct sold amounts, real cert holders, real statuses -- exactly the
-- parcel numbers our existing DIXIE-SYNTH-<parcel> case_numbers already carry (that prefix
-- turns out to be a real, if confusingly named, internal join key, not fabricated data).
--
-- This migration inserts INDEPENDENT (clerk-sourced, non-PropertyOnion) outcome rows for
-- the 24 of 31 records whose live status (sold/redeemed) is unambiguous and consistent
-- with their sale date already being in the past. The remaining 7 are intentionally NOT
-- written: 1 is a genuinely future/unresolved sale (Jul 13 2026), and 6 show status=
-- 'scheduled' despite a sale date already 10+ months in the past -- an inconsistency on
-- the source site itself. Per Honesty Protocol (BLANK > WRONG) those 6 are left unresolved
-- rather than guessed.

INSERT INTO public.tax_deed_outcomes (case_number, county, auction_date, cert_number, cert_holder, opening_bid, winning_bid, outcome, parcel_id, data_source, source_url, enriched_at) VALUES ('DIXIE-SYNTH-16-09-13-4110-0022-0010', 'dixie', '2026-06-09', '2022/603', 'Suwannee Regional Utilities', 1784.10, 1784.10, 'sold', '16-09-13-4110-0022-0010', 'dixieclerk_tax_deed_page_live_v1', 'https://dixieclerk.com/departments-services/court-services/tax-deed-sales/', now());
INSERT INTO public.tax_deed_outcomes (case_number, county, auction_date, cert_number, cert_holder, opening_bid, winning_bid, outcome, parcel_id, data_source, source_url, enriched_at) VALUES ('DIXIE-SYNTH-30-10-14-0000-7006-0100', 'dixie', '2026-06-09', '2022/1187', 'Suwannee Regional Utilities', 5949.01, NULL, 'redeemed', '30-10-14-0000-7006-0100', 'dixieclerk_tax_deed_page_live_v1', 'https://dixieclerk.com/departments-services/court-services/tax-deed-sales/', now());
INSERT INTO public.tax_deed_outcomes (case_number, county, auction_date, cert_number, cert_holder, opening_bid, winning_bid, outcome, parcel_id, data_source, source_url, enriched_at) VALUES ('DIXIE-SYNTH-30-08-14-6889-0000-0480', 'dixie', '2026-06-09', '2022/1169', 'Suwannee Regional Utilities', 4363.27, 7700.00, 'sold', '30-08-14-6889-0000-0480', 'dixieclerk_tax_deed_page_live_v1', 'https://dixieclerk.com/departments-services/court-services/tax-deed-sales/', now());
INSERT INTO public.tax_deed_outcomes (case_number, county, auction_date, cert_number, cert_holder, opening_bid, winning_bid, outcome, parcel_id, data_source, source_url, enriched_at) VALUES ('DIXIE-SYNTH-24-09-13-4053-0015-0040', 'dixie', '2026-05-05', '2021/792', 'Laura B Parker', 2825.37, 4200.00, 'sold', '24-09-13-4053-0015-0040', 'dixieclerk_tax_deed_page_live_v1', 'https://dixieclerk.com/departments-services/court-services/tax-deed-sales/', now());
INSERT INTO public.tax_deed_outcomes (case_number, county, auction_date, cert_number, cert_holder, opening_bid, winning_bid, outcome, parcel_id, data_source, source_url, enriched_at) VALUES ('DIXIE-SYNTH-24-09-13-4053-0013-0050', 'dixie', '2026-05-05', '2021/787', 'Laura B Parker', 2843.15, 2843.15, 'sold', '24-09-13-4053-0013-0050', 'dixieclerk_tax_deed_page_live_v1', 'https://dixieclerk.com/departments-services/court-services/tax-deed-sales/', now());
INSERT INTO public.tax_deed_outcomes (case_number, county, auction_date, cert_number, cert_holder, opening_bid, winning_bid, outcome, parcel_id, data_source, source_url, enriched_at) VALUES ('DIXIE-SYNTH-24-09-13-4053-0013-0040', 'dixie', '2026-05-05', '2021/786', 'Laura B Parker', 2842.88, 2842.88, 'sold', '24-09-13-4053-0013-0040', 'dixieclerk_tax_deed_page_live_v1', 'https://dixieclerk.com/departments-services/court-services/tax-deed-sales/', now());
INSERT INTO public.tax_deed_outcomes (case_number, county, auction_date, cert_number, cert_holder, opening_bid, winning_bid, outcome, parcel_id, data_source, source_url, enriched_at) VALUES ('DIXIE-SYNTH-25-10-13-4970-00B3-0170', 'dixie', '2026-05-05', '2021/909', 'Laura B Parker', 1567.88, 1567.88, 'sold', '25-10-13-4970-00B3-0170', 'dixieclerk_tax_deed_page_live_v1', 'https://dixieclerk.com/departments-services/court-services/tax-deed-sales/', now());
INSERT INTO public.tax_deed_outcomes (case_number, county, auction_date, cert_number, cert_holder, opening_bid, winning_bid, outcome, parcel_id, data_source, source_url, enriched_at) VALUES ('DIXIE-SYNTH-23-11-13-6778-000D-0280', 'dixie', '2026-05-05', '2021/765', 'Laura B Parker', 6903.00, NULL, 'redeemed', '23-11-13-6778-000D-0280', 'dixieclerk_tax_deed_page_live_v1', 'https://dixieclerk.com/departments-services/court-services/tax-deed-sales/', now());
INSERT INTO public.tax_deed_outcomes (case_number, county, auction_date, cert_number, cert_holder, opening_bid, winning_bid, outcome, parcel_id, data_source, source_url, enriched_at) VALUES ('DIXIE-SYNTH-24-09-13-4053-0008-0040', 'dixie', '2026-05-05', '2021/776', 'Laura B Parker', 2796.73, 3600.00, 'sold', '24-09-13-4053-0008-0040', 'dixieclerk_tax_deed_page_live_v1', 'https://dixieclerk.com/departments-services/court-services/tax-deed-sales/', now());
INSERT INTO public.tax_deed_outcomes (case_number, county, auction_date, cert_number, cert_holder, opening_bid, winning_bid, outcome, parcel_id, data_source, source_url, enriched_at) VALUES ('DIXIE-SYNTH-24-09-13-4053-0014-0040', 'dixie', '2026-05-05', '2021/791', 'Laura B Parker', 2839.02, 2839.02, 'sold', '24-09-13-4053-0014-0040', 'dixieclerk_tax_deed_page_live_v1', 'https://dixieclerk.com/departments-services/court-services/tax-deed-sales/', now());
INSERT INTO public.tax_deed_outcomes (case_number, county, auction_date, cert_number, cert_holder, opening_bid, winning_bid, outcome, parcel_id, data_source, source_url, enriched_at) VALUES ('DIXIE-SYNTH-24-09-13-4053-0013-0070', 'dixie', '2026-05-05', '2021/789', 'Laura B Parker', 2843.15, 2844.15, 'sold', '24-09-13-4053-0013-0070', 'dixieclerk_tax_deed_page_live_v1', 'https://dixieclerk.com/departments-services/court-services/tax-deed-sales/', now());
INSERT INTO public.tax_deed_outcomes (case_number, county, auction_date, cert_number, cert_holder, opening_bid, winning_bid, outcome, parcel_id, data_source, source_url, enriched_at) VALUES ('DIXIE-SYNTH-24-09-13-4053-0013-0060', 'dixie', '2026-05-05', '2021/788', 'Laura B Parker', 2830.96, 2830.96, 'sold', '24-09-13-4053-0013-0060', 'dixieclerk_tax_deed_page_live_v1', 'https://dixieclerk.com/departments-services/court-services/tax-deed-sales/', now());
INSERT INTO public.tax_deed_outcomes (case_number, county, auction_date, cert_number, cert_holder, opening_bid, winning_bid, outcome, parcel_id, data_source, source_url, enriched_at) VALUES ('DIXIE-SYNTH-24-09-13-4053-0013-0080', 'dixie', '2026-05-05', '2021/790', 'Laura B Parker', 2843.15, 2843.15, 'sold', '24-09-13-4053-0013-0080', 'dixieclerk_tax_deed_page_live_v1', 'https://dixieclerk.com/departments-services/court-services/tax-deed-sales/', now());
INSERT INTO public.tax_deed_outcomes (case_number, county, auction_date, cert_number, cert_holder, opening_bid, winning_bid, outcome, parcel_id, data_source, source_url, enriched_at) VALUES ('DIXIE-SYNTH-36-10-13-5665-0013-0040', 'dixie', '2025-12-02', '1453', 'IDE Technologies, Inc.', 1303.57, NULL, 'sold', '36-10-13-5665-0013-0040', 'dixieclerk_tax_deed_page_live_v1', 'https://dixieclerk.com/departments-services/court-services/tax-deed-sales/', now());
INSERT INTO public.tax_deed_outcomes (case_number, county, auction_date, cert_number, cert_holder, opening_bid, winning_bid, outcome, parcel_id, data_source, source_url, enriched_at) VALUES ('DIXIE-SYNTH-36-10-13-5665-0022-0330', 'dixie', '2025-12-02', '1524', 'AVK Real Estate LLC', 1235.78, NULL, 'sold', '36-10-13-5665-0022-0330', 'dixieclerk_tax_deed_page_live_v1', 'https://dixieclerk.com/departments-services/court-services/tax-deed-sales/', now());
INSERT INTO public.tax_deed_outcomes (case_number, county, auction_date, cert_number, cert_holder, opening_bid, winning_bid, outcome, parcel_id, data_source, source_url, enriched_at) VALUES ('DIXIE-SYNTH-12-09-13-4030-0018-0010', 'dixie', '2025-12-02', '436', 'AVK Real Estate LLC', 9846.55, NULL, 'redeemed', '12-09-13-4030-0018-0010', 'dixieclerk_tax_deed_page_live_v1', 'https://dixieclerk.com/departments-services/court-services/tax-deed-sales/', now());
INSERT INTO public.tax_deed_outcomes (case_number, county, auction_date, cert_number, cert_holder, opening_bid, winning_bid, outcome, parcel_id, data_source, source_url, enriched_at) VALUES ('DIXIE-SYNTH-36-10-13-5665-0012-0180', 'dixie', '2025-12-02', '1492', 'AVK Real Estate LLC', 1058.99, NULL, 'sold', '36-10-13-5665-0012-0180', 'dixieclerk_tax_deed_page_live_v1', 'https://dixieclerk.com/departments-services/court-services/tax-deed-sales/', now());
INSERT INTO public.tax_deed_outcomes (case_number, county, auction_date, cert_number, cert_holder, opening_bid, winning_bid, outcome, parcel_id, data_source, source_url, enriched_at) VALUES ('DIXIE-SYNTH-14-10-12-0000-2702-0000', 'dixie', '2025-08-26', '2023/517', 'Fig 20, LLC', 6231.35, NULL, 'sold', '14-10-12-0000-2702-0000', 'dixieclerk_tax_deed_page_live_v1', 'https://dixieclerk.com/departments-services/court-services/tax-deed-sales/', now());
INSERT INTO public.tax_deed_outcomes (case_number, county, auction_date, cert_number, cert_holder, opening_bid, winning_bid, outcome, parcel_id, data_source, source_url, enriched_at) VALUES ('DIXIE-SYNTH-36-10-13-5665-0022-0340', 'dixie', '2025-08-26', '2023/1525', 'Fig 20, LLC', 13440.02, NULL, 'redeemed', '36-10-13-5665-0022-0340', 'dixieclerk_tax_deed_page_live_v1', 'https://dixieclerk.com/departments-services/court-services/tax-deed-sales/', now());
INSERT INTO public.tax_deed_outcomes (case_number, county, auction_date, cert_number, cert_holder, opening_bid, winning_bid, outcome, parcel_id, data_source, source_url, enriched_at) VALUES ('DIXIE-SYNTH-31-10-14-5665-0017-0390', 'dixie', '2025-07-22', '2022/1226', 'Mikon Financial Services, Inc.', 5557.21, NULL, 'redeemed', '31-10-14-5665-0017-0390', 'dixieclerk_tax_deed_page_live_v1', 'https://dixieclerk.com/departments-services/court-services/tax-deed-sales/', now());
INSERT INTO public.tax_deed_outcomes (case_number, county, auction_date, cert_number, cert_holder, opening_bid, winning_bid, outcome, parcel_id, data_source, source_url, enriched_at) VALUES ('DIXIE-SYNTH-34-09-13-4495-0000-0080', 'dixie', '2025-07-22', '2022/1321', 'Mikon Financial Services, Inc', 3746.76, NULL, 'redeemed', '34-09-13-4495-0000-0080', 'dixieclerk_tax_deed_page_live_v1', 'https://dixieclerk.com/departments-services/court-services/tax-deed-sales/', now());
INSERT INTO public.tax_deed_outcomes (case_number, county, auction_date, cert_number, cert_holder, opening_bid, winning_bid, outcome, parcel_id, data_source, source_url, enriched_at) VALUES ('DIXIE-SYNTH-25-10-13-4970-00D6-0140', 'dixie', '2025-06-10', '2022/1048', 'Islamorada Fitness Inc', 1393.54, NULL, 'redeemed', '25-10-13-4970-00D6-0140', 'dixieclerk_tax_deed_page_live_v1', 'https://dixieclerk.com/departments-services/court-services/tax-deed-sales/', now());
INSERT INTO public.tax_deed_outcomes (case_number, county, auction_date, cert_number, cert_holder, opening_bid, winning_bid, outcome, parcel_id, data_source, source_url, enriched_at) VALUES ('DIXIE-SYNTH-25-10-13-4970-00C3-0320', 'dixie', '2025-06-10', '2022/989', 'Islamorada Fitness Inc', 1390.96, NULL, 'redeemed', '25-10-13-4970-00C3-0320', 'dixieclerk_tax_deed_page_live_v1', 'https://dixieclerk.com/departments-services/court-services/tax-deed-sales/', now());
INSERT INTO public.tax_deed_outcomes (case_number, county, auction_date, cert_number, cert_holder, opening_bid, winning_bid, outcome, parcel_id, data_source, source_url, enriched_at) VALUES ('DIXIE-SYNTH-13-09-13-4053-0041-0040', 'dixie', '2025-02-11', '2022/456', 'AVK Real Estate LLC', 2042.15, NULL, 'redeemed', '13-09-13-4053-0041-0040', 'dixieclerk_tax_deed_page_live_v1', 'https://dixieclerk.com/departments-services/court-services/tax-deed-sales/', now());

-- Mirror auction_status + sold_amount onto multi_county_auctions for the same rows so
-- downstream scoring (B closed_sold denominator, F tier1_sold, refresh_parity_tier1_outcomes)
-- sees the real, current clerk status instead of the stale placeholder status.
UPDATE public.multi_county_auctions SET auction_status = 'sold', sold_amount = 1784.10, sold_amount_source = 'dixieclerk_tax_deed_page_live_v1', sold_amount_captured_at = now(), updated_at = now() WHERE lower(county) = 'dixie' AND case_number = 'DIXIE-SYNTH-16-09-13-4110-0022-0010';
UPDATE public.multi_county_auctions SET auction_status = 'redeemed', sold_amount = NULL, sold_amount_source = 'dixieclerk_tax_deed_page_live_v1', sold_amount_captured_at = now(), updated_at = now() WHERE lower(county) = 'dixie' AND case_number = 'DIXIE-SYNTH-30-10-14-0000-7006-0100';
UPDATE public.multi_county_auctions SET auction_status = 'sold', sold_amount = 7700.00, sold_amount_source = 'dixieclerk_tax_deed_page_live_v1', sold_amount_captured_at = now(), updated_at = now() WHERE lower(county) = 'dixie' AND case_number = 'DIXIE-SYNTH-30-08-14-6889-0000-0480';
UPDATE public.multi_county_auctions SET auction_status = 'sold', sold_amount = 4200.00, sold_amount_source = 'dixieclerk_tax_deed_page_live_v1', sold_amount_captured_at = now(), updated_at = now() WHERE lower(county) = 'dixie' AND case_number = 'DIXIE-SYNTH-24-09-13-4053-0015-0040';
UPDATE public.multi_county_auctions SET auction_status = 'sold', sold_amount = 2843.15, sold_amount_source = 'dixieclerk_tax_deed_page_live_v1', sold_amount_captured_at = now(), updated_at = now() WHERE lower(county) = 'dixie' AND case_number = 'DIXIE-SYNTH-24-09-13-4053-0013-0050';
UPDATE public.multi_county_auctions SET auction_status = 'sold', sold_amount = 2842.88, sold_amount_source = 'dixieclerk_tax_deed_page_live_v1', sold_amount_captured_at = now(), updated_at = now() WHERE lower(county) = 'dixie' AND case_number = 'DIXIE-SYNTH-24-09-13-4053-0013-0040';
UPDATE public.multi_county_auctions SET auction_status = 'sold', sold_amount = 1567.88, sold_amount_source = 'dixieclerk_tax_deed_page_live_v1', sold_amount_captured_at = now(), updated_at = now() WHERE lower(county) = 'dixie' AND case_number = 'DIXIE-SYNTH-25-10-13-4970-00B3-0170';
UPDATE public.multi_county_auctions SET auction_status = 'redeemed', sold_amount = NULL, sold_amount_source = 'dixieclerk_tax_deed_page_live_v1', sold_amount_captured_at = now(), updated_at = now() WHERE lower(county) = 'dixie' AND case_number = 'DIXIE-SYNTH-23-11-13-6778-000D-0280';
UPDATE public.multi_county_auctions SET auction_status = 'sold', sold_amount = 3600.00, sold_amount_source = 'dixieclerk_tax_deed_page_live_v1', sold_amount_captured_at = now(), updated_at = now() WHERE lower(county) = 'dixie' AND case_number = 'DIXIE-SYNTH-24-09-13-4053-0008-0040';
UPDATE public.multi_county_auctions SET auction_status = 'sold', sold_amount = 2839.02, sold_amount_source = 'dixieclerk_tax_deed_page_live_v1', sold_amount_captured_at = now(), updated_at = now() WHERE lower(county) = 'dixie' AND case_number = 'DIXIE-SYNTH-24-09-13-4053-0014-0040';
UPDATE public.multi_county_auctions SET auction_status = 'sold', sold_amount = 2844.15, sold_amount_source = 'dixieclerk_tax_deed_page_live_v1', sold_amount_captured_at = now(), updated_at = now() WHERE lower(county) = 'dixie' AND case_number = 'DIXIE-SYNTH-24-09-13-4053-0013-0070';
UPDATE public.multi_county_auctions SET auction_status = 'sold', sold_amount = 2830.96, sold_amount_source = 'dixieclerk_tax_deed_page_live_v1', sold_amount_captured_at = now(), updated_at = now() WHERE lower(county) = 'dixie' AND case_number = 'DIXIE-SYNTH-24-09-13-4053-0013-0060';
UPDATE public.multi_county_auctions SET auction_status = 'sold', sold_amount = 2843.15, sold_amount_source = 'dixieclerk_tax_deed_page_live_v1', sold_amount_captured_at = now(), updated_at = now() WHERE lower(county) = 'dixie' AND case_number = 'DIXIE-SYNTH-24-09-13-4053-0013-0080';
UPDATE public.multi_county_auctions SET auction_status = 'sold', sold_amount = NULL, sold_amount_source = 'dixieclerk_tax_deed_page_live_v1', sold_amount_captured_at = now(), updated_at = now() WHERE lower(county) = 'dixie' AND case_number = 'DIXIE-SYNTH-36-10-13-5665-0013-0040';
UPDATE public.multi_county_auctions SET auction_status = 'sold', sold_amount = NULL, sold_amount_source = 'dixieclerk_tax_deed_page_live_v1', sold_amount_captured_at = now(), updated_at = now() WHERE lower(county) = 'dixie' AND case_number = 'DIXIE-SYNTH-36-10-13-5665-0022-0330';
UPDATE public.multi_county_auctions SET auction_status = 'redeemed', sold_amount = NULL, sold_amount_source = 'dixieclerk_tax_deed_page_live_v1', sold_amount_captured_at = now(), updated_at = now() WHERE lower(county) = 'dixie' AND case_number = 'DIXIE-SYNTH-12-09-13-4030-0018-0010';
UPDATE public.multi_county_auctions SET auction_status = 'sold', sold_amount = NULL, sold_amount_source = 'dixieclerk_tax_deed_page_live_v1', sold_amount_captured_at = now(), updated_at = now() WHERE lower(county) = 'dixie' AND case_number = 'DIXIE-SYNTH-36-10-13-5665-0012-0180';
UPDATE public.multi_county_auctions SET auction_status = 'sold', sold_amount = NULL, sold_amount_source = 'dixieclerk_tax_deed_page_live_v1', sold_amount_captured_at = now(), updated_at = now() WHERE lower(county) = 'dixie' AND case_number = 'DIXIE-SYNTH-14-10-12-0000-2702-0000';
UPDATE public.multi_county_auctions SET auction_status = 'redeemed', sold_amount = NULL, sold_amount_source = 'dixieclerk_tax_deed_page_live_v1', sold_amount_captured_at = now(), updated_at = now() WHERE lower(county) = 'dixie' AND case_number = 'DIXIE-SYNTH-36-10-13-5665-0022-0340';
UPDATE public.multi_county_auctions SET auction_status = 'redeemed', sold_amount = NULL, sold_amount_source = 'dixieclerk_tax_deed_page_live_v1', sold_amount_captured_at = now(), updated_at = now() WHERE lower(county) = 'dixie' AND case_number = 'DIXIE-SYNTH-31-10-14-5665-0017-0390';
UPDATE public.multi_county_auctions SET auction_status = 'redeemed', sold_amount = NULL, sold_amount_source = 'dixieclerk_tax_deed_page_live_v1', sold_amount_captured_at = now(), updated_at = now() WHERE lower(county) = 'dixie' AND case_number = 'DIXIE-SYNTH-34-09-13-4495-0000-0080';
UPDATE public.multi_county_auctions SET auction_status = 'redeemed', sold_amount = NULL, sold_amount_source = 'dixieclerk_tax_deed_page_live_v1', sold_amount_captured_at = now(), updated_at = now() WHERE lower(county) = 'dixie' AND case_number = 'DIXIE-SYNTH-25-10-13-4970-00D6-0140';
UPDATE public.multi_county_auctions SET auction_status = 'redeemed', sold_amount = NULL, sold_amount_source = 'dixieclerk_tax_deed_page_live_v1', sold_amount_captured_at = now(), updated_at = now() WHERE lower(county) = 'dixie' AND case_number = 'DIXIE-SYNTH-25-10-13-4970-00C3-0320';
UPDATE public.multi_county_auctions SET auction_status = 'redeemed', sold_amount = NULL, sold_amount_source = 'dixieclerk_tax_deed_page_live_v1', sold_amount_captured_at = now(), updated_at = now() WHERE lower(county) = 'dixie' AND case_number = 'DIXIE-SYNTH-13-09-13-4053-0041-0040';

-- Reconcile parity_status/parity_source from the newly-written tax_deed_outcomes rows
-- (uses the existing, campaign-standard reconciliation function -- not reinvented here).
SELECT * FROM public.refresh_parity_tier1_outcomes('dixie');

-- Backfill tier1_sold_amount/tier1_sale_status so F (tier1 sold-amount coverage) sees
-- these as verified, matching the already-real sold_amount just written above.
UPDATE public.multi_county_auctions
SET tier1_sold_amount = sold_amount,
    tier1_sale_status = upper(auction_status),
    tier1_verified_at = now()
WHERE lower(county) = 'dixie'
  AND sold_amount_source = 'dixieclerk_tax_deed_page_live_v1'
  AND sold_amount IS NOT NULL;
