-- DIXIE: C/D 56.3%->90.6% via canonical parity matcher re-invocation
-- Session: continuation of shard6_dixie diagnosis (2026-07-03)
--
-- ROOT CAUSE (VERIFIED live 2026-07-03 via REST queries): a 2026-07-02 tier1
-- sync batch inserted/updated tax_deed_outcomes rows for dixie and stamped 11
-- multi_county_auctions rows directly with parity_status IN ('tier1_only') plus
-- 3 with 'mca_only', but public.refresh_parity_tier1_outcomes('dixie') (the
-- existing canonical matcher, most recent def in
-- 20260703_shard5_refresh_parity_case_before_parcel_crosslink_fix.sql) was
-- never re-invoked afterward to reconcile them. All 11 tier1_only case_numbers
-- were confirmed present in tax_deed_outcomes with outcome='sold' matching
-- auction_status='sold' -- a direct case-number match the function resolves
-- to matched_clean on invocation.
--
-- BEFORE (pencil_dod_evaluate_county('dixie'), live 2026-07-03):
--   C matched_clean=18 (56.3%) FAIL | D matched_any=18 (56.3%) FAIL
--   (A/B/E/F/G/H/I/J all PASS, unaffected)
--
-- APPLIED LIVE via PostgREST RPC 2026-07-03:
--   SELECT * FROM public.refresh_parity_tier1_outcomes('dixie');
--   -> [{"pass":"case","matched_clean":21,"matched_divergent":0},
--       {"pass":"parcel","matched_clean":0,"matched_divergent":0}]
--
-- REGRESSION FOUND + CORRECTED: the function's blind reset step
-- (parity_status=NULL, parity_source=NULL for ALL in-scope auction_status IN
-- (...,'cancelled',...) rows) cleared 9 'cancelled' dixie rows that had no
-- corresponding row in tax_deed_outcomes/foreclosure_outcomes (dixie's outcomes
-- table only carries outcome='sold' rows, no 'cancelled' outcomes were ever
-- scraped) -- so those 9 could not be re-matched and were left at
-- parity_status=NULL, worse than their prior state. 7 of the 9 had been
-- genuine matched_clean rows (parity_source='tier1_dixie_clerk_scrape_shard6',
-- a real tier1-prefixed source per 20260627_shard1_miami_dade_cd_tier1_stamp.sql
-- precedent -- "dixie: already 10/10 ... no action needed"); the other 2 had
-- been mca_only. All 9 were restored to their pre-invocation
-- parity_status/parity_source via targeted PATCH by id (no blind UPDATE),
-- since this is legitimate prior tier1 provenance that the shared function's
-- reset step cannot preserve when an outcome row is absent for that status.
--
-- AFTER restore (pencil_dod_evaluate_county('dixie'), live 2026-07-03):
--   C matched_clean=29 (90.6%) FAIL (below 95% threshold, but +34.3pp gain)
--   D matched_any=29   (90.6%) FAIL (same)
--   A/B/E/F/G/H/I/J confirmed unchanged (still PASS, no regression).
--
-- RESIDUAL GAP (3 of 32, not closed this session -- genuine, not a further bug):
--   - 1 row auction_status='scheduled' (case 15... upcoming, not yet closed,
--     cannot be matched against a closed outcome yet)
--   - 2 rows auction_status='cancelled' with case_numbers
--     DIXIE-SYNTH-30-10-14-0000-7006-0100 and DIXIE-SYNTH-23-11-13-6778-000D-0280,
--     which have NO corresponding row in tax_deed_outcomes or
--     foreclosure_outcomes at all (dixie's outcomes table only has 'sold' rows).
--     Investigated dixieclerk.com directly (clerk_url pointed at
--     https://dixieclerk.com/taxdeeds/2188/, a generic listing page, HTTP 200)
--     -- case_numbers are DIXIE-SYNTH-prefixed synthetic identifiers that do not
--     key into that live page at per-case granularity, so further scraping
--     would not produce a reliable independent outcome and risks fabricating
--     data. Left as mca_only (their pre-existing honest state) rather than
--     forcing a fragile match. Genuine backfill/litmus-source gap, flagged for
--     a future session with real clerk case-number crosswalk.
--
-- No DDL/schema change this session -- this migration documents the RPC call
-- plus the by-id PATCH restore, per repo convention (see
-- 20260703_shard10b_taylor_cd_canonical_matcher.sql).

SELECT 1; -- no-op placeholder: documents an RPC call + targeted restore, already applied live above.
