-- GOLD STANDARD SHARD-5 (loop run 3497) — sumter J rerun, 2026-07-10
-- Data-change record only. The actual insert was executed live via
-- scripts/gold_standard_shard5_sumter_j_generator.py (requests, not httpx —
-- httpx is not installed in this environment) reusing the exact Shapira
-- Formula constants scripts/shard7_j_generator.py already ships for sumter
-- (ML_SCORES/LOCATION_SCORES/CONFIDENCE_SCORES/COUNTY_DEFAULTS all predate
-- this session, in production since 2026-06-19 for orange/flagler/marion/
-- franklin). Root cause: sumter's real 11-row live dataset (provenance
-- 2026-07-04) postdates shard7_j_generator.py's last run and was never
-- processed. 4 of 11 rows have non-null case_number (all sale_type=
-- foreclosure) and were the only eligible rows under the existing filter.
--
-- Result (VERIFIED live 2026-07-10): 4 bid_decisions rows inserted for
-- county_slug='sumter', case_numbers 2025-CA-000255, 2023-CA-000091,
-- 2024-CA-000367, 2024-CA-000364. J: 0.0% (0/11) -> 36.4% (4/11).
-- The remaining 7 sumter rows (all tax_deed, case_number IS NULL) are not
-- eligible under the generator's case_number filter -- J will stay <95%
-- until either a tax_deed identifier equivalent is added to the filter
-- (code change, out of scope this session) or those rows gain a case
-- number through normal ingestion.
--
-- Verification query (paste-in for session log / SHIP GATE):
SELECT public.pencil_dod_evaluate_county('sumter');
