-- SHARD-8: bay/jefferson/st_lucie/lee — canonical parity matcher re-run + jefferson
-- fabrication purge (no schema change)
-- dispatch_id: 966d999c-39ab-4aae-9431-7a5925e1d08d
-- Session: architect-20260703T080000
--
-- 1) Ran the case-fixed public.refresh_parity_tier1_outcomes(p_county) (fixed live 2026-07-03
--    in shard-6, see 20260703_shard6_refresh_parity_case_sensitivity_fix.sql) for the four
--    real-data counties in this shard:
--      SELECT * FROM public.refresh_parity_tier1_outcomes('bay');
--      SELECT * FROM public.refresh_parity_tier1_outcomes('jefferson');
--      SELECT * FROM public.refresh_parity_tier1_outcomes('st_lucie');
--      SELECT * FROM public.refresh_parity_tier1_outcomes('lee');
--
--    bay:      matched_clean 69 -> 66. NOT a regression: all 3 newly-unmatched rows are
--               auction_status='cancelled' cases with ZERO corresponding row in
--               foreclosure_outcomes/tax_deed_outcomes (verified live, no case_number/parcel_id
--               match exists anywhere) -- their prior 'matched_clean' status was ghost-success,
--               never independently backed. The drop is a correction. Real fix requires
--               harvesting independent cancellation confirmations for these 4 cases from an
--               official Bay County source (see fan-out workflow findings below).
--    st_lucie: matched_clean unchanged at 2 of 72 -- confirmed (again, independently) as a
--               genuine data-volume ceiling: only 2 of 72 auctions have ever closed_sold.
--    lee:      matched_clean 160 -> 148, same ghost-success pattern as bay, 12 cancelled
--               cases with no independent outcome record.
--    jefferson: matched_clean 0 -> 1 -- INITIALLY treated as a possible gain, but investigated
--               before committing (per the bradford precedent in honesty_violations) and found
--               to be matching one fabricated multi_county_auctions row against one fabricated
--               foreclosure_outcomes row. See item 2.
--
-- 2) JEFFERSON FABRICATION (CRITICAL, honesty_violations id add80a91-84e0-46ec-b744-a73396bff9ed):
--    jefferson's entire dataset -- both of its 2 multi_county_auctions rows (case_number
--    2025-CA-000001 foreclosure, 2025-TD-000001 tax_deed) plus the matching foreclosure_outcomes
--    row -- was 100% fabricated placeholder data. Source: scripts/shard13_run581_lane_setup.py's
--    JEFFERSON_SYNTHETIC_SEEDS constant ("used if live scrape returns 0") plus
--    scripts/shard3_jefferson_bootstrap.py's enrichment pass (its own docstring says "HONESTY
--    MARKERS: ... INFERRED" but that disclosure never reached a queryable column -- same failure
--    mode previously found in the lake/columbia precedent). Tells: parcel_id
--    '1200650000CA2025001'/'1200650000TD2025001' (constructed, not a real parcel format),
--    property_address literally "Unknown Property, Monticello FL 32344", identical centroid
--    lat/lon on both rows, round dollar amounts, sequential case numbers, and
--    parity_source containing the literal string "jefferson_synthetic_platform".
--
--    VERIFIED LIVE: jefferson.realforeclose.com and jefferson.realtaxdeed.com both resolve and
--    return HTTP 403 (bot wall, same shared RealAuction ELB as other real counties) -- so the
--    "live scrape returns 0" premise was actually "live scrape got blocked", silently
--    misreported as an empty calendar and papered over with fake data.
--
--    CORRECTIVE ACTION (applied live before this migration was written):
--      DELETE FROM foreclosure_outcomes WHERE case_number = '2025-CA-000001' AND county = 'jefferson';
--      DELETE FROM multi_county_auctions WHERE county = 'jefferson' AND case_number IN ('2025-CA-000001', '2025-TD-000001');
--    Re-verified via pencil_dod_evaluate_county('jefferson'): auctions_total now 0, all letters
--    FAIL/null except G (fleet-wide zoning view artifact, unaffected by this county's data).
--    Honest floor is 1/10, not the brief's reported 8/10.
--
--    Quarantined both source scripts (scripts/shard3_jefferson_bootstrap.py now refuses to run;
--    scripts/shard13_run581_lane_setup.py's synthetic-seed fallback removed, replaced with a
--    loud ERROR log) so this cannot silently re-fabricate. No C/D (or any other letter) gain is
--    being claimed for jefferson. Real jefferson data requires an authenticated or
--    firecrawl-capable scrape past the 403 wall -- flagged as next-session work, not attempted
--    this session (out of remaining budget).
--
-- No regression introduced on any other shard-8 county by this migration; bay/st_lucie/lee
-- changes are corrections/reconfirmations only, verified via fresh pencil_dod_evaluate_county
-- calls before and after.

SELECT 1; -- no-op placeholder: this migration documents live RPC calls, a live DELETE
          -- correction, and a live honesty_violations INSERT, already applied via Supabase
          -- REST API at the timestamps described above (not DDL/DML in this file).
