-- SHARD: wakulla C/D real gains via canonical matcher (ghost-success family)
-- Session: 2026-07-03, single-county assignment (wakulla only)
--
-- CONTEXT: wakulla had 5 auctions total (3 auction_status='completed', 2 'upcoming').
-- All 5 rows carried parity_status='mca_only' with parity_source=
-- 'tier1_matched_clean_bootstrap' -- the same ghost-success label family already
-- purged today for desoto/jackson/orange/volusia via
-- 20260703_shard10_desoto_jackson_orange_volusia_cd_ghost_success_purge.sql (see
-- that file for full precedent/investigation). The label name implies a clean tier-1
-- match but parity_status='mca_only' means "no independent outcome found" --
-- inconsistent and untraceable. Unlike the shard10 counties, wakulla's canonical
-- rerun did NOT surface any additional divergent/fabricated rows beyond the
-- pre-existing bootstrap label -- this shard is a straightforward re-match, not an
-- additional-fabrication discovery.
--
-- STRUCTURAL CEILING (stated BEFORE running anything, confirmed after):
-- the canonical matcher (refresh_parity_tier1_outcomes) only ever matches rows with
-- closed auction_status (redeemed/completed/sold/cancelled/canceled) against
-- tax_deed_outcomes/foreclosure_outcomes. wakulla has 3 closed rows out of 5 total.
-- Ceiling for C and D = 3/5 = 60.0%, which is BELOW the 95% pass threshold. A PASS
-- was never achievable this session and none is claimed here.
--
-- STEP 1 (BEFORE, live query):
--   SELECT public.pencil_dod_evaluate_county('wakulla');
--   C: pass=false matched_clean=0 metric=0.0
--   D: pass=false matched_any=0   metric=0.0
--   (A/B/E/F/G/H/I/J unaffected, all already pass=true)
--
-- STEP 2 (ACTION, live, this session): invoked the existing shared canonical matcher,
-- unmodified:
--   SELECT * FROM public.refresh_parity_tier1_outcomes('wakulla');
--   Raw output:
--     [{"pass":"case","matched_clean":3,"matched_divergent":0},
--      {"pass":"parcel","matched_clean":0,"matched_divergent":0}]
--   All 3 matches came via the case-number pass (case_number normalized match against
--   tax_deed_outcomes/foreclosure_outcomes), 0 via parcel_id pass, 0 divergent in
--   either pass. Resulting row-level state (verified via direct SELECT):
--     WAK-FC-2026-001      completed  matched_clean  tier1_foreclosure_outcome
--     WAKULLA-FC-2026-001  completed  matched_clean  tier1_foreclosure_outcome
--     WAKULLA-TD-2026-001  completed  matched_clean  tier1_tax_deed_outcome
--     WAK-TD-2026-001      upcoming   mca_only       tier1_matched_clean_bootstrap  (untouched)
--     WAKULLA-TD-2026-002  upcoming   mca_only       tier1_matched_clean_bootstrap  (untouched)
--   The 2 upcoming rows are correctly left alone -- matcher's WHERE clause never
--   touches non-closed auction_status, matching the documented structural ceiling.
--
-- STEP 3 (AFTER, live query):
--   SELECT public.pencil_dod_evaluate_county('wakulla');
--   C: pass=false matched_clean=3 metric=60.0
--   D: pass=false matched_any=3   metric=60.0
--   Exactly matches the pre-stated ceiling of 3/5 = 60.0%. Still pass=false (< 95%
--   threshold) -- no false PASS claimed, gains are real and fully backed by
--   tier1_foreclosure_outcome / tier1_tax_deed_outcome joins against live
--   foreclosure_outcomes (2 wakulla rows) and tax_deed_outcomes (1 wakulla row).
--
-- NEXT STEPS (not done this session, flagged honestly): the 2 remaining upcoming
-- rows (WAK-TD-2026-001, WAKULLA-TD-2026-002) cannot reach matched status until they
-- close (auction occurs, status flips to completed/sold/redeemed/cancelled) and an
-- outcome record is scraped/entered. No further action possible on this county this
-- session without fabricating outcomes -- refused per Honesty Protocol.
--
-- No other county touched. gold_standard_loop()/gold_standard_certify() NOT invoked
-- (other shards may be running concurrently, per instructions).

SELECT 1; -- no-op placeholder: documents the live refresh_parity_tier1_outcomes('wakulla')
          -- call already applied via the Supabase Management API SQL endpoint
          -- (api.supabase.com/v1/projects/mocerqjnksmhcjzxrewo/database/query with
          -- SUPABASE_ACCESS_TOKEN) in this session.
