-- SHARD-11 (dispatch_id d0b9d16b-4554-4e5a-ae0f-5247fe6abe4d): miami_dade E/I audit.
-- Applied live via Supabase Management API SQL endpoint (api.supabase.com/v1/projects/
-- mocerqjnksmhcjzxrewo/database/query with SUPABASE_ACCESS_TOKEN) -- direct psql/pooler
-- auth unavailable in this runner, same limitation documented in prior shard migrations.
--
-- ============================================================================
-- STEP 1 (BEFORE, live query): SELECT public.pencil_dod_evaluate_county('miami_dade');
-- ============================================================================
--   E: pass=true  parcel_linked=348 of 356  metric=97.8
--   I: pass=false card_complete=338 of 356  metric=94.9
--
-- ============================================================================
-- ROOT CAUSE (E): ghost-success via scraper-captured UI label instead of folio
-- ============================================================================
-- 10 miami_dade rows carried parcel_id set to a literal UI field/label string
-- captured by the scraper instead of a real Miami-Dade folio (folio format:
-- NN-NNNN-NNN-NNNN). Full scope confirmed via regex sweep (not just the 3
-- values spotted in the initial finding) -- exactly 10 rows total contain any
-- letters in parcel_id, and all 10 match one of three garbage values:
--   'Property Appraiser'          x5
--   'MULTIPLE PARCELS'            x4
--   'ALCOHOLIC BEVERAGE LICENSE'  x1
-- These rows counted toward E's has_parcel numerator (parcel_id IS NOT NULL)
-- despite carrying no real parcel identity -- same ghost-success pattern
-- already purged in this repo for hillsborough/madison/wakulla/desoto/jackson/
-- orange/volusia (see 20260703_shard6_hillsborough_cd_ghost_success_purge.sql
-- and 20260703_shard10_desoto_jackson_orange_volusia_cd_ghost_success_purge.sql).
--
-- Affected case_numbers (all auction_status='upcoming'):
--   2025-095290-CC-05 (realforeclose)      -> 'ALCOHOLIC BEVERAGE LICENSE'
--   2021-002908-CA-01 (realtaxdeed)        -> 'MULTIPLE PARCELS'
--   2025-001562-CA-01 (realtaxdeed)        -> 'MULTIPLE PARCELS'
--   2025-004900-CA-01 (realtaxdeed)        -> 'MULTIPLE PARCELS'
--   2025-009489-CA-01 (realtaxdeed)        -> 'MULTIPLE PARCELS'
--   2022-010471-CA-01 (realtaxdeed)        -> 'Property Appraiser'
--   2023-025492-CA-01 (realtaxdeed)        -> 'Property Appraiser'
--   2024-000006-CA-01 (realtaxdeed)        -> 'Property Appraiser'
--   2025-001356-CA-01 (realtaxdeed)        -> 'Property Appraiser'
--   2025-022077-CA-01 (realtaxdeed)        -> 'Property Appraiser'
--
-- ============================================================================
-- STEP 2 (ACTION, live, this session):
-- ============================================================================
--   UPDATE multi_county_auctions
--   SET parcel_id = NULL, updated_at = now()
--   WHERE county = 'miami_dade'
--     AND parcel_id IN ('Property Appraiser', 'MULTIPLE PARCELS', 'ALCOHOLIC BEVERAGE LICENSE')
--   RETURNING case_number, parcel_id;
--   -- 10 rows purged, confirmed via RETURNING (all now NULL). Row NOT deleted,
--   -- no fabricated replacement folio invented -- row simply loses its false
--   -- parcel identity, matching the mandated "NULL out, never fabricate" pattern.
--
-- No other county touched. gold_standard_loop()/gold_standard_certify() NOT
-- invoked (other shards run concurrently). Cron jobs 109/111/115 untouched.
--
-- ============================================================================
-- STEP 3 (AFTER, live query): SELECT public.pencil_dod_evaluate_county('miami_dade');
-- ============================================================================
--   E: pass=false parcel_linked=338 of 356  metric=94.9  (HONEST, down from
--      ghost-inflated 97.8 -- purging the 10 garbage rows drops E BELOW the
--      95% threshold, flipping it from PASS to FAIL. This is the real number.
--      Reported honestly per task instructions: "if it drops E below 95%,
--      report that honestly as the real (lower, correct) number; do NOT skip
--      the purge just to protect the metric.")
--   I: pass=false card_complete=335 of 356  metric=94.1  (down from 94.9,
--      still failing -- see analysis below; the drop is NOT a regression from
--      this purge, it is the correction of a SECOND, independent ghost-match
--      this purge incidentally exposed)
--
-- ============================================================================
-- SECONDARY FINDING (I): upstream ghost-match in v_zoning_gold_standard_card
-- ============================================================================
-- 3 of the 10 purged case_numbers (2022-010471-CA-01, 2024-000006-CA-01,
-- 2025-022077-CA-01) had real property_address values and were PASSING I's
-- card_complete test BEFORE the purge -- not because of a real zoning match,
-- but because v_zoning_gold_standard_card ITSELF contains the identical
-- garbage placeholder string 'Property Appraiser' as a parcel_id value for
-- county='miami dade' (zone_code='RU-1'), plus 'MULTIPLE PARCELS' and
-- 'ALCOHOLIC BEVERAGE LICENSE' also present there for miami dade, and the
-- same three garbage strings recur across ~20 OTHER counties in that view
-- (volusia, sarasota, orange, broward, pinellas, escambia, marion, st lucie,
-- nassau, walton, clay, putnam, charlotte, citrus, seminole, polk,
-- hillsborough (13x), santa rosa, gilchrist, palm beach, duval). This means
-- our garbage-string parcel_id was accidentally STRING-MATCHING an equally
-- garbage entry in the zoning card view, producing a false-positive
-- card_complete pass. Purging our side's garbage parcel_id correctly closes
-- this ghost-match (verified: these 3 rows now correctly evaluate has_zone
-- as NULL/false rather than an accidental true). v_zoning_gold_standard_card
-- itself is OUT OF SCOPE for this migration (cross-county, not owned by
-- miami_dade shard) -- flagged here for a future dedicated cleanup shard.
--
-- ============================================================================
-- I's REAL, NON-FABRICATABLE GAP (21 rows = 356 - 335), verified live:
-- ============================================================================
-- Group 1 -- 9 rows: property_address IS NULL (parcel_id also NULL, either
-- pre-existing or post-purge). No property-appraiser/folio ingestion table
-- exists for Miami-Dade in this DB to join against for address recovery
-- (checked information_schema.tables for %miami%/%property_appraiser%/
-- %folio% -- only brevard_folio_pin_bridge [wrong county] and
-- v_miami_dade_auction_dor [DOR value/PID join, has no address column to
-- backfill FROM] exist). Genuine structural gap requiring a future re-scrape
-- of the source court filings. Case numbers: 2021-002908-CA-01,
-- 2023-025492-CA-01, 2024-002728-CA-01 (dup row), 2025-001356-CA-01,
-- 2025-001562-CA-01, 2025-004900-CA-01, 2025-009489-CA-01, 2025-095290-CC-05.
--
-- Group 2 -- 9 rows: property_address present, parcel_id NULL (no folio to
-- join against v_zoning_gold_standard_card at all). 3 are the newly-purged
-- rows above; 6 are pre-existing (independent of this purge): 2016-031005-
-- CA-01 (dup), 2025-016575-CA-01 (dup), 2026-007470-CA-01 (dup).
--
-- Group 3 -- 3 rows: real folio-format parcel_id + real address, but NO
-- match in v_zoning_gold_standard_card for miami_dade (zoning-intelligence
-- coverage gap, not an auction-data defect): 04-3106-036-0020 (3672 W 2 AVE,
-- HIALEAH), 02-4203-004-0810 (601 WASHINGTON AVE, MIAMI BEACH), 30-4927-036-
-- 0200 (13701 KENDALE LAKES CIR B-405, MIAMI).
--
-- None of these 21 rows can be closed today without fabricating an address,
-- geocode, value, or zone code -- explicitly banned. Reported as a genuine
-- structural ceiling, NOT gamed. I remains FAILING (94.1%, down from a
-- ghost-inflated 94.9%) -- this is the honest number.
--
-- Adversarially self-checked: confirmed no other garbage parcel_id patterns
-- exist beyond the 3 known values (regex sweep for any letter in parcel_id
-- returned exactly 10 rows, all accounted for above). Confirmed denominator
-- (auctions_total / card_rows = 356) unchanged before/after. Confirmed
-- SEPARATELY that latitude=25.7617/longitude=-80.1918 (Miami city centroid)
-- is repeated across 340 of 356 miami_dade rows -- a likely fabricated-
-- fallback geocode pattern predating this session. This is OUT OF SCOPE for
-- the E/I garbage-parcel task assigned here (touches G's density metric and
-- a much larger population than the 10-row purge target) and was NOT altered
-- -- flagged as a finding for a future dedicated audit, not silently fixed
-- or silently ignored.

SELECT 1; -- no-op placeholder: documents the live UPDATE already applied via
          -- the Supabase Management API SQL endpoint in this session.
