-- SHARD-5: hendry C/D — run canonical parity matcher (no schema change)
-- dispatch_id: bec9a9b3-ce1c-4a46-b7e0-a861096f5ffb
-- Session: architect-20260702T160000
--
-- ROOT CAUSE (VERIFIED live 2026-07-02 via ULTRALOOP audit workflow wf_63692fb6-dbb):
-- hendry's single ad-hoc row (parity_source='tier1_supplementary:shard3:2026-06-25') was
-- written by a bypass process that never ran the canonical matcher, leaving
-- parity_status='mca_only' despite tax_deed_outcomes carrying a real matching case.
-- The correct fix is to invoke the existing canonical function, not hand-write an UPDATE.
--
-- Applied live 2026-07-02: SELECT * FROM public.refresh_parity_tier1_outcomes('hendry');
--
-- VERIFIED via pencil_dod_evaluate_county('hendry') before/after:
--   C: 0.0% (matched_clean=0 of 19) -> 5.3% (matched_clean=1 of 19)
--   D: 0.0% (matched_any=0 of 19)   -> 5.3% (matched_any=1 of 19)
--   A/B/E/F/G/H/I/J unaffected (confirmed no regression)
-- Structural ceiling: only 1 of hendry's 19 auctions has ever closed (fc=2 td=17, the
-- rest are still scheduled) so C/D cannot reach 95% until more cases close and are
-- independently harvested -- this is a genuine data-volume gap, not a further bug.
--
-- Audit also flagged (NOT deleted, insufficient evidence of fabrication vs franklin's
-- unambiguous SYN- marker): foreclosure_outcomes row case_number='HENDRY-FC-2026-001'
-- (data_source='clerk_fc:SHARD3-HENDRY-V1') follows the same suspicious single-row
-- "SHARD3-<COUNTY>-V1" pattern seen fleet-wide in several counties. Flagged for a future
-- session's honesty audit with real clerk-site cross-check before any deletion.

SELECT 1; -- no-op placeholder: this migration documents a function CALL (not DDL/DML),
          -- already applied live via Supabase Management API at the timestamp above.
