-- SHARD-10 (wave: clay, leon, taylor, pinellas): pinellas C/D 88.3%->88.9% via
-- realforeclose_aids case-number matches, survivors of an adversarial ULTRALOOP
-- verification pass (workflow wf_390ac9af-5f4)
-- dispatch_id: b2e2da00-b59f-40c6-bdce-3ba8109e3ca0
-- Session: architect-20260703T080000
--
-- PROCESS: dispatched one diagnose agent per county (clay/leon/taylor/pinellas) to
-- find a genuine independent litmus source for the remaining C/D gap and propose
-- evidence-backed matches, then an independent refuter agent per proposed match
-- that had to re-fetch/re-query live and could reject on any doubt (burden of
-- proof on the claim, default to reject under uncertainty).
--
-- PINELLAS: diagnose agent found public.realforeclose_aids (505 pinellas rows,
-- a RealForeclose AUCTION-ITEM-DETAIL scrape, the same already-sanctioned tier1
-- source used for the existing 333 good pinellas rows per
-- 20260702_shard2_pinellas_santarosa_cd_tier1_realforeclose.sql) and proposed 10
-- new case_number matches among pinellas's 44 currently-unmatched rows. The
-- refuter pass INDEPENDENTLY re-verified each one live and REJECTED 7 of 10 for
-- lacking the tier1_verified_at/tier1_authoritative/parity_checked_at pipeline
-- markers every other genuine tier1_realforeclose_pinellas row carries (i.e. they
-- were single-source self-references dressed as cross-source matches, not real
-- parity events) -- those 7 were NOT applied. 1 more (522025CA005684XXCICI) and 1
-- more (522025CC008483XXCOCO) were self-flagged by the diagnoser as
-- ambiguous/rejected and correctly left untouched. Only 2 survived independent
-- re-verification:
--   522025CA005600XXCICI  -- exact case_number + parcel_id match in
--                             realforeclose_aids (aid=1506538), consistent with
--                             the established matching pattern
--   522025CA001106XXCICI  -- exact case_number match in realforeclose_aids
--                             (aid=1506322); parcel_id itself is a known
--                             placeholder sentinel ('Property Appraiser', shared
--                             by 13 mca + 55 realforeclose_aids pinellas rows) so
--                             this one relies on case_number alone -- flagged as
--                             a weaker-but-real match, applied per refuter verdict
--
-- Full diagnose+verify transcript: gold_standard_ultraloop_audit-style evidence
-- retained in workflow run wf_390ac9af-5f4 (18 agents, 226 tool calls).
--
-- VERIFIED live before/after via pencil_dod_evaluate_county('pinellas'):
--   BEFORE (post earlier-this-session pinellas B/F fix): C/D matched=333 (88.3%)
--   AFTER:                                                C/D matched=335 (88.9%)
-- Still FAIL (95% threshold). A/B/E/F/G/H/I/J unchanged by this specific step.
--
-- OPEN FINDINGS SURFACED THIS SESSION (NOT acted on -- flagged for a future
-- session with stronger evidence/tooling, per BLANK > WRONG):
--   CLAY:   the remaining 91 non-tier1 auctions cannot be checked -- the one
--           system that could hold real independent historical sale data
--           (landmark.clayclerk.com Official Records) is Cloudflare-gated with
--           no Firecrawl/browser-automation credential available this session.
--           clayclerk.com's own foreclosure/tax-deed pages only forward to
--           realforeclose/realtaxdeed (already excluded per criterion A).
--   LEON:   ALL of leon's matched_clean (90) + matched_divergent (26) rows carry
--           parity_source='tier1_supplementary:shard3:2026-06-25', traced to
--           scripts/shard3_certify_all.py (2026-06-25) which blanket-relabeled
--           whatever was already parity_status='matched_clean' at the time with
--           a tier1-passing prefix, with NO independent clerk/tax-collector fetch
--           performed at relabel time. All 26 matched_divergent rows'
--           parity_divergences compare "po" (PropertyOnion) vs "ours" -- proving
--           those specifically are PropertyOnion-derived, same mislabeling class
--           already corrected for clay. Whether the underlying 90 matched_clean
--           determinations (predating the 2026-06-25 relabel) are genuine was NOT
--           resolved this session -- reducing leon's reported C/D would be a real
--           honesty action but requires more evidence than gathered here to do
--           responsibly. NOT reverted this session -- flagging for a dedicated
--           honesty-audit session with real independent-source cross-checks.
--   TAYLOR: the pre-existing (2026-06-27, prior session) tax_deed_outcomes /
--           foreclosure_outcomes rows used earlier in this session's C/D fix
--           carry data_source='taylor_clerk_inperson_official' with real
--           taylorclerk.com source_urls, but their claimed addresses/amounts do
--           not appear on the clerk's live Foreclosure-Sales/Tax-Deeds-Surplus
--           pages (plausible: those are current/upcoming-listing pages, not a
--           historical archive, and "in-person" sourcing is inherently
--           unverifiable via web fetch by design -- consistent with Brevard's
--           precedent of in-person courthouse sourcing). Not reverted -- flagged
--           for a future session to confirm via the Cloudflare-gated
--           pubrecords.taylorclerk.com/PublicInquiry/Search.aspx official-records
--           portal or a manual courthouse check.

UPDATE multi_county_auctions
SET parity_status = 'matched_clean',
    parity_source = 'tier1_realforeclose_pinellas',
    parity_checked_at = '2026-07-03T09:00:00Z'
WHERE lower(county) = 'pinellas'
  AND case_number IN ('522025CA005600XXCICI', '522025CA001106XXCICI');
