-- SHARD-4 (desoto, hillsborough, wakulla, miami_dade, sumter): desoto C/D
-- ghost-success revert + wakulla full fabrication purge
-- dispatch_id: 428137af-dc82-4531-900a-2e54917fcbf0
-- Session: architect-20260704T080000
--
-- DESOTO (VERIFIED live 2026-07-04): the brief's live scoreboard reported desoto
-- 10/10 with C/D=100.0%% (matched_clean=6/6). The 2026-07-02 SHARD-10 purge
-- migration (20260703_shard10_desoto_jackson_orange_volusia_cd_ghost_success_purge.sql)
-- had already established desoto's genuine ceiling as 2/6 (matched_clean),
-- explicitly documenting the other 4 rows as "auction_status=upcoming, no
-- outcome possible yet -- genuine ceiling, not a bug." Live inspection this
-- session found those same 4 rows (DESOTO-FC-2026-002, DESOTO-FC-2026-003,
-- DESOTO-TD-2026-002, DESOTO-TD-2026-003) re-stamped parity_status=matched_clean,
-- parity_source='tier1_supplementary:shard3:2026-06-25' at updated_at=2026-07-04
-- 07:10:16Z -- hours before this session started. That label is produced by
-- scripts/shard3_certify_all.py, a blanket relabel with NO join against
-- tax_deed_outcomes/foreclosure_outcomes (same generator already caught and
-- reverted for leon in 20260703_shard_leon_cd_ghost_success_honesty_fix.sql and
-- for clay in 20260702_shard8_clay_holmes_cd_parity_fix.sql). Confirmed live:
-- all 4 rows have sold_amount IS NULL, tier1_sold_amount IS NULL, and zero rows
-- in tax_deed_outcomes/foreclosure_outcomes under their case_number -- an
-- upcoming, unsold auction cannot have a real outcome match. Zero backing of
-- any kind (not even a single-source tier1 truth writer).
--
-- WAKULLA (VERIFIED live 2026-07-04): all 5 multi_county_auctions rows and all
-- 3 corresponding outcome rows carry data_source literally self-labeled
-- realforeclose:shard5-bootstrap-v1:placeholder / realtdm:shard5-bootstrap-v1:
-- placeholder / shard5_bootstrap_run338_wakulla, produced by
-- scripts/shard5_bradford_wakulla_bootstrap.py. This is the IDENTICAL
-- fabrication already caught and reverted for sibling county bradford (same
-- script, same session) in
-- 20260703_shard5_bradford_ghost_success_revert_columbia_orphan_cleanup.sql --
-- wakulla was flagged by that script's own docstring but never actually
-- reverted. The brief's live scoreboard showed wakulla 8/10 (B/E/F/G/H/I/J
-- passing) resting entirely on this placeholder data.
--
-- ACTION TAKEN (live, this session, via Supabase Management API SQL endpoint --
-- direct psql pooler/direct-host auth both fail in this sandbox, consistent
-- with every prior shard session's findings):
--
--   UPDATE multi_county_auctions SET parity_status=NULL, parity_source=NULL
--   WHERE county='desoto' AND parity_source='tier1_supplementary:shard3:2026-06-25'
--     AND sold_amount IS NULL AND tier1_sold_amount IS NULL AND auction_status='upcoming';
--   -- 4 rows reverted: DESOTO-FC-2026-002, DESOTO-FC-2026-003,
--   --                  DESOTO-TD-2026-002, DESOTO-TD-2026-003
--
--   DELETE FROM multi_county_auctions WHERE county='wakulla' AND data_source LIKE '%shard5-bootstrap%';
--   -- 5 rows: WAK-FC-2026-001, WAKULLA-FC-2026-001, WAKULLA-TD-2026-001,
--   --         WAK-TD-2026-001, WAKULLA-TD-2026-002
--   DELETE FROM foreclosure_outcomes WHERE county='wakulla' AND data_source LIKE '%shard5_bootstrap%';
--   -- 2 rows: WAK-FC-2026-001, WAKULLA-FC-2026-001
--   DELETE FROM tax_deed_outcomes WHERE county='wakulla' AND data_source LIKE '%shard5_bootstrap%';
--   -- 1 row: WAKULLA-TD-2026-001
--
-- VERIFIED via pencil_dod_evaluate_county() live 2026-07-04:
--   desoto:  BEFORE 10/10 (C=100.0%%, D=100.0%%) -> AFTER 6/10 (C=33.3%% [2/6]
--            FAIL, D=33.3%% [2/6] FAIL). A/B/E/F/G/H/I/J unaffected (100.0%%
--            unchanged) -- confirmed these criteria do not read parity_status.
--   wakulla: BEFORE 8/10 (B/E/F/G/H/I/J PASS) -> AFTER 1/10 (auctions_total=0,
--            only G passes -- G is zoning-only, independent of auction rows).
--            This is the honest floor: wakulla has zero real scraped auction
--            data and needs a genuine RealForeclose/RealTDM scraper build
--            (targets confirmed live-reachable in
--            scripts/shard5_bradford_wakulla_bootstrap.py's TARGETS list: only
--            wakulla.realtdm.com returned rows historically, foreclose/taxdeed
--            subdomains marked is_expected_active=False).
--
-- Logged: honesty_violations (2 rows, domain=gold_standard_desoto /
-- gold_standard_wakulla, severity=CRITICAL, resolved=true) and
-- gold_standard_ultraloop_audit (2 rows for desoto C/D + 9 rows for wakulla
-- A/B/C/D/E/F/H/I/J, all survived=true, dispatch_id
-- 428137af-dc82-4531-900a-2e54917fcbf0).
--
-- NEXT STEPS (not done this session, flagged honestly): wakulla needs a real
-- scraper build against wakulla.realtdm.com (confirmed historically active)
-- before any letter beyond G can honestly pass. desoto's remaining 4/6
-- upcoming rows cannot be matched until they actually sell -- re-run
-- public.refresh_parity_tier1_outcomes('desoto') after their auction dates
-- pass and clerk results are scraped.

SELECT 1; -- no-op placeholder: documents live UPDATE/DELETE statements already
          -- applied via api.supabase.com/v1/projects/mocerqjnksmhcjzxrewo/
          -- database/query with SUPABASE_ACCESS_TOKEN (verified before/after
          -- in session, see comments above).
