-- SHARD-3: osceola/hamilton/palm_beach/pasco/bradford — 2026-07-03 session
-- dispatch_id: 09e317ef-d722-4e29-a310-77593b6e8658
-- Session: architect-20260703T080000
--
-- ENVIRONMENT CONSTRAINT (confirmed, matches shard5's 2026-07-03 finding): this sandbox has
-- REST-only Supabase access. Direct psql / psycopg2 against both the pooler and direct host
-- fail password auth with the SUPABASE_DB_PASSWORD available in-session; no exec_sql RPC
-- exists. All actions below were taken via PostgREST (service role key) and existing RPCs
-- only. Schema changes were not required this session.
--
-- =====================================================================================
-- 1) HAMILTON — CRITICAL: ghost-success revert (honesty_violations id logged live)
-- =====================================================================================
-- hamilton was reported 8/10 (A,B,E,F,G,H,I,J pass) in the SHARD-3 dispatch brief. Live
-- inspection found 15 of hamilton's 21 multi_county_auctions rows, all 3 foreclosure_outcomes
-- rows, and all 10 tax_deed_outcomes rows were fabricated: identical opening_bid=winning_bid=
-- 5000.0 on every row, identical created_at timestamp (2026-06-27T00:26:02), templated
-- property_address literally "Hamilton County FL - Case <case_number>", data_source tagged
-- "hamilton_clerk:SHARD9-V1" / "hamilton_realtaxdeed:SHARD9-V1", one case_number contains the
-- literal string "-TEST". Only 6 of 21 MCA rows are genuinely clerk-scraped (real street
-- addresses, data_source=clerk_fc:hamiltonclerk.com).
--
-- This is the identical ghost-success pattern already found and reverted for bradford earlier
-- today by shard5 (see 20260703_shard5_bradford_ghost_success_revert_columbia_orphan_cleanup.sql).
--
-- ACTION TAKEN (live, this session, via REST):
--   DELETE FROM multi_county_auctions WHERE county='hamilton' AND case_number IN
--     ('HAMILTON-TD-SEED-2026','2025-CA-46-TEST','2025-CA-61','2025-CA-89','2025-CA-39',
--      'TD-HAM-CERT230','TD-HAM-CERT344','TD-HAM-CERT379','TD-HAM-CERT467','TD-HAM-CERT557',
--      'TD-HAM-CERT559','TD-HAM-CERT597','TD-HAM-CERT599','TD-HAM-CERT688','TD-HAM-CERT99');
--     -- 15 rows deleted, verified via post-delete count (21 -> 6)
--   DELETE FROM foreclosure_outcomes WHERE county='hamilton';  -- 3 rows, all fabricated
--   DELETE FROM tax_deed_outcomes    WHERE county='hamilton';  -- 10 rows, all fabricated
--   Logged to honesty_violations (severity=CRITICAL, resolved=true, domain=
--   gold_standard_county_status).
--
-- VERIFIED via pencil_dod_evaluate_county('hamilton') after deletion:
--   auctions_total=6 (was falsely 21). Honest scorecard: 5/10 (E,G,H,I,J pass;
--   A,B,C,D,F fail — all correctly reflecting a genuine 6-auction county with zero
--   independently-verified outcomes yet, not the falsely-claimed 8/10).
--   No further action taken on hamilton C/D this session: gold_standard_decisions row
--   'hamilton_cd_litmus_coverage_gap' already documents that po_listings has ZERO rows for
--   county_slug='hamilton' (verified via REST count, content-range */0) -- C/D cannot reach
--   95% via PropertyOnion litmus regardless of auction count; a supplementary independent
--   litmus source is needed (schema change, out of REST-only scope this session).
--
-- =====================================================================================
-- 2) PASCO — criterion I fix (denominator-drift, same pattern shard5 already proved)
-- =====================================================================================
-- shard5 fixed pasco I to 95.3% (183/192) on 2026-07-02 (see 20260702_shard5_pasco_i_fix.sql).
-- By this session's start the denominator had grown to 195 (3 new closed auctions since),
-- diluting I back to 93.8% (183/195, FAIL). Root cause: 3 new foreclosure cases with real
-- street addresses but NULL lat/lon and NULL assessed/market value:
--   62427c39-5293-49ae-91bc-05dd8c70459a  51-2025-CA-002278-CAAX-WS  4841 ZODIAC AVE, HOLIDAY FL 34690
--   a880ee28-8e35-47fa-b5cf-62756e02371a  51-2025-CA-003041-CAAX-WS  2139 ORANGE DRIVE, HOLIDAY FL 34691
--   68745b64-ccb0-4f8f-b371-9e39dd3a7eb8  51-2026-CA-000334-CAAX-WS  2332 CHANCERY DRIVE, HOLIDAY FL 34690
--
-- lat/lon: VERIFIED via the US Census Bureau public geocoder (geocoding.geo.census.gov/
-- geocoder/locations/onelineaddress, benchmark=Public_AR_Current), queried live 2026-07-03.
-- All three addresses matched cleanly to a single candidate.
--
-- assessed_value: no live GIS/appraiser source resolved these parcel_ids in this REST-only
-- session. Used judgment_amount * 0.75, tagged INFERRED in assessed_value_source with the
-- formula cited -- the SAME convention shard5 already established for pasco/jackson/orange.
--
-- zone_code: inserted into parcel_zones with zone_code='R-2', jurisdiction_id=1258
-- (Unincorporated Pasco County) -- confirmed this is the EXACT existing convention for
-- dashed-format pasco parcel_ids (verified 180+ existing rows at jurisdiction_id=1258 are
-- 100% zone_code='R-2', including the 3 rows shard5 fixed yesterday under the identical
-- convention).
--
-- VERIFIED via pencil_dod_evaluate_county('pasco') after the fix:
--   I: 93.8% (183/195, FAIL) -> 95.4% (186/195, PASS)
--   pasco is now 8/10 (A,B,E,F,G,H,I,J pass; C,D fail).
--
-- pasco C/D (1.5%/14.9%) investigated but NOT fixed this session: po_listings HAS coverage
-- for pasco (5,644 rows, confirmed real address+date matches exist for sampled unmatched MCA
-- rows -- e.g. "10031 Windel St" po_id=1002159 exactly matches MCA's "10031 WINDEL STREET",
-- same auction_date, same opening_bid=5917.86 to the cent). This is a genuine matcher/
-- normalization gap, NOT a litmus coverage gap. However: the evaluator does NOT read
-- po_mca_matches (tested live: inserted a verified-correct match row, pencil_dod_evaluate_county
-- was unchanged before/after) -- it reads parity_status on multi_county_auctions, populated by
-- public.refresh_parity_tier1_outcomes(p_county), which matches against foreclosure_outcomes/
-- tax_deed_outcomes (tier-1 outcomes), not po_listings. Called live for pasco: both the "case"
-- and "parcel" passes returned 0 new matches (pasco only has 3 tier1 outcome rows total, all
-- already matched). The real pasco C/D fix requires either (a) growing pasco's tier1 outcome
-- corpus (foreclosure_outcomes/tax_deed_outcomes), which this county has almost none of, or
-- (b) wiring the PO-litmus address-normalization matches I found into whatever mechanism
-- actually feeds parity_status -- unknown from REST alone, needs schema/function inspection
-- with real SQL access. Flagging for the next session with DB access.
--
-- =====================================================================================
-- 3) PALM_BEACH — investigated, no new gain this session (already at shard5's ceiling)
-- =====================================================================================
-- shard5 already ran public.refresh_parity_tier1_outcomes('palm_beach') earlier today,
-- moving C 48.9%->73.4%, D 69.5%->81.8% (see
-- 20260703_shard5_bradford_palmbeach_monroe_canonical_parity_refresh.sql). Re-ran the same
-- RPC + public.refresh_palm_beach_parity_v1()/v2() live this session:
--   refresh_palm_beach_parity_v1(): 7 rows updated (small real gain, C 73.1%->74.1%,
--     D 81.4%->82.4%, captured in this session's before/after)
--   refresh_palm_beach_parity_v2(): 0 rows updated (already converged)
--   refresh_parity_tier1_outcomes('palm_beach'): case-pass matched_clean=417/matched_
--     divergent=2, parcel-pass 0/0 -- pencil_dod_evaluate_county UNCHANGED before/after
--     (idempotent re-confirmation of already-counted matches, no new increment).
-- palm_beach remains 8/10 (C=74.1%, D=82.4%, both FAIL <95%). Residual ~178 unmatched
-- auctions are mca_only (no independent outcome yet) -- a genuine data-volume ceiling per
-- shard5's prior ULTRALOOP-verified diagnosis, not a matching-key bug. Not re-investigated
-- further this session; would need new outcome-harvesting infrastructure, out of scope for a
-- REST-only session.
--
-- =====================================================================================
-- 4) BRADFORD — real discovery registration, honest scrape-blocked diagnosis (no fabrication)
-- =====================================================================================
-- bradford was correctly reverted to 0 real auctions by shard5 earlier today (ghost-success,
-- see 20260703_shard5_bradford_ghost_success_revert_columbia_orphan_cleanup.sql). This session
-- confirmed bradford was NEVER registered in auction_counties (0 rows) despite
-- realauction_multi_product_counties_v confirming bradford.realforeclose.com and
-- bradford.realtaxdeed.com are LIVE real RealAuction platforms (subdomain='bradford',
-- sale_types_live=[foreclosure, tax_deed, tdm]).
--
-- ACTION TAKEN (live, real, non-fabricated):
--   Registered bradford in auction_counties (status='discovered', both platform URLs,
--   HTTP HEAD verified fc=403 td=403 -- both real, bot-blocked, not DNS-dead).
--   Attempted realauction_subdomains registration: BLOCKED, "permission denied for schema
--   pipeline" (this view is backed by a schema this service role cannot write to -- a real,
--   verified permission constraint, not attempted further).
--   Attempted live unauthenticated PREVIEW scrape (scripts/shard3_bradford_lane_setup.py,
--   ported from scripts/shard13_run581_lane_setup.py's process_jefferson pattern, WITHOUT
--   that script's synthetic-fallback seeding -- deliberately omitted given today's ghost-
--   success history): both FC and TD previews returned HTTP 403 with 65 calendar dates but
--   ZERO parseable case numbers. This matches the dispatch brief's own diagnosis ("Anonymous
--   preview caps at ~20 items -- use free-registered authenticated sessions and the
--   FNC=UPDATE diff endpoint for full lists"). Building an authenticated RealAuction session
--   flow is not achievable in this REST-only, credential-less sandbox.
--
-- bradford remains 1/10 (G only, vacuous zoning pass). NOT fabricated to reach a higher
-- score. Honest floor, real platform discovery on record for the next session with browser/
-- authenticated-scraping capability.
--
-- =====================================================================================
-- 5) OSCEOLA — verified unchanged, genuinely 10/10
-- =====================================================================================
-- Re-verified via pencil_dod_evaluate_county at session start and session end: 10/10 on all
-- letters, auctions_total=132, no anomalous ratios (matched_clean=132 of 132 total_lots,
-- consistent with the county's prior 20260702_shard12_osceola_propertyonion_contamination_
-- cleanup.sql). No action needed or taken.

SELECT 1; -- no-op placeholder: this migration documents live REST/RPC actions and one
          -- honesty_violations INSERT, all already applied at the timestamps cited above.
