-- SHARD-10: nassau parcel_id "Property Appraiser" placeholder fix + ULTRALOOP
-- audit coverage backfill for criteria E and H
-- dispatch_id: c2b52cf8-afaf-423a-9817-d84c762924d7
-- Session: architect-20260702T080000 (gold standard shard-10: okaloosa, nassau)
--
-- CONTEXT: this dispatch's brief (generated at session start) showed nassau at
-- 7/10 (C/D/I failing at 79.4%). Live re-check at session resume showed nassau
-- already at 10/10 -- the C/D/I/G fix (real Nassau CPA GIS geo+zoning) had
-- already shipped earlier in this same session (commit b0e73fed) and was
-- ULTRALOOP-audited (survived=true rows for A/B/C/D/F/G/I/J). The brief text
-- was a stale pre-session snapshot, not a live regression.
--
-- GAP FOUND: nassau had ZERO gold_standard_ultraloop_audit rows -- ever -- for
-- criteria E and H, even though both PASS on the live scoreboard. Per the
-- EVALUATOR V6 SQL CERTIFY GATE rule, zero audit rows = UNKNOWN, not passing;
-- gold_standard_certify() would have blocked nassau certification despite a
-- clean 10/10 scoreboard. okaloosa already had full 10/10 audit coverage.
--
-- ACTION: ran an ULTRALOOP measure+adversarial-refute workflow against nassau
-- E (parcel linkage) and H (freshness), independently recomputed from raw
-- multi_county_auctions rows via PostgREST (direct psql/pooler auth fails in
-- this environment -- REST with service-role key works).
--
-- H: refuter reproduced 1.5h since last_seen independently, no discrepancy.
--    Recorded as survived=true, no data change.
--
-- E: refuter reproduced the RPC's 34/34=100.0% mechanically, but caught that
--    one row (id=051f5593-9fba-4e6d-8573-735e772c3846, case
--    452026CA000050CAAXYX, 24966 CR 121 Hilliard FL) has parcel_id literally
--    equal to the string 'Property Appraiser' -- a scraped UI-link-label
--    artifact, not a real parcel identifier. This inflated the claimed metric
--    to a false 100.0%. Confirmed the SAME literal-string bug independently
--    hit 109 rows fleet-wide across other counties (mirrors shard-7's same-day
--    finding in orange, 20260702_shard7_orange_property_appraiser_dedup.sql,
--    which used the identical null-don't-fabricate fix). Only the nassau row
--    is in scope for this shard; the other 108 rows belong to other shards'
--    counties and were NOT touched.
--
-- FIX: nulled the confirmed-bogus parcel_id value rather than fabricate a
-- replacement. Attempted a live lookup of the real parcel_id via the FL
-- statewide cadastral ArcGIS FeatureServer
-- (services9.arcgis.com/.../Florida_Statewide_Cadastral/FeatureServer/0) but
-- it returned HTTP 400 on every Nassau-scoped WHERE clause tried (CO_NO=55,
-- PHY_CITY='HILLIARD') while identical query shapes worked fine for other
-- counties (CO_NO=11 Alachua). Root cause of the 400 is UNTESTED/unresolved --
-- documented rather than guessed at a parcel_id, per NEVER-LIE.
--
-- RESULT (live, post-fix): pencil_dod_evaluate_county('nassau') E moved from
-- an inflated 100.0% (34/34, including 1 ghost value) to an honest 97.1%
-- (33/34). I moved from 100.0% to 97.1% for the same reason (I depends on E's
-- parcel set). Both remain PASS at the >=95% threshold -- no scoreboard
-- regression, just a corrected number.
--
-- Both new claims (E at the honest 97.1%, H at 1.5h) recorded to
-- gold_standard_ultraloop_audit with survived=true via the live API during
-- this session (see rows id=2626, id=2627, created_at 2026-07-02T10:58Z).
-- This file documents the change for the repo history; the audit rows and the
-- data PATCH were already applied live before this file was committed.

-- Idempotent guard: only touches the one confirmed-bogus row, matched on both
-- id and the exact placeholder value, so re-running this migration is a no-op
-- once applied.
UPDATE public.multi_county_auctions
SET parcel_id = NULL
WHERE id = '051f5593-9fba-4e6d-8573-735e772c3846'
  AND parcel_id = 'Property Appraiser';
