-- SHARD-7 (loop run 2820): madison ghost-success revert (CRITICAL)
-- dispatch_id: bdeea7e8-f0ec-4bea-9406-1bd2885f1e5a
-- Session: architect-20260704T000000 (gold standard shard-7: madison, highlands, volusia, pasco, columbia)
--
-- ROOT CAUSE (VERIFIED live 2026-07-04, independently confirmed by an adversarial
-- ULTRALOOP workflow refuter, then re-confirmed directly by this session):
--   madison showed pencil_dod_evaluate_county 10/10 (all A-J pass) at session start.
--   All 9 underlying multi_county_auctions rows were synthetic shard5_bootstrap
--   scaffold data, never scraped from a real source:
--     - data_source='shard5_bootstrap' on 6 rows, NULL with '-PAST-' case numbers
--       on the other 3 (same scaffold family)
--     - bcpao_enriched=false on every single row
--     - sequential fabricated addresses (101 Pine St / 202 Oak Ave / 303 Elm St;
--       7010/7020/7030 Madison Hwy; 8010/8020/8030 Cherry Lake Rd)
--     - patterned identical tier1_sold_amount values ($9,000 x3 FC rows,
--       $4,800 x3 TD rows) — real independent sales do not cluster this way
--     - parcel_id 'MADISON-FC-0003' mapped to TWO different case_numbers and
--       TWO different addresses (303 Elm St vs 7030 Madison Hwy) — a real
--       parcel_id can only ever resolve to one property; this alone proves
--       fabrication, not scraper noise
--   The synthetic data cascaded downstream: foreclosure_outcomes/tax_deed_outcomes
--   rows carried fabricated data_source labels ('realforeclose:shard5-v1',
--   'realforeclose:shard5-loop472') despite tracing to the same synthetic case
--   numbers, and bid_decisions had duplicate/inconsistent ARV entries per
--   case_number (e.g. MADISON-FC-2026-002 with ARV 120000 in one row and 94300
--   in another).
--
-- This is the same fabrication class already caught and reverted repeatedly in
-- this campaign's history (pasco commit d92b5a33, santa_rosa + hendry commit
-- 203b7fe0, both 2026-07-03). BLANK > WRONG: madison reverts to an honest 0/10
-- (auctions_total=0, matching columbia's honest bootstrap state) rather than a
-- false 10/10. Real ingestion for madison (co_no per fl_counties) is unstarted.
--
-- Corrective actions taken live (via PostgREST, documented here for the repo
-- history — no schema change, this migration is a record of the DML already
-- executed):
--   DELETE FROM bid_decisions        WHERE county_slug = 'madison';   -- 15 rows
--   DELETE FROM foreclosure_outcomes WHERE county = 'madison';        -- 7 rows
--   DELETE FROM tax_deed_outcomes    WHERE county = 'madison';        -- 5 rows
--   DELETE FROM multi_county_auctions WHERE county = 'madison';      -- 9 rows
--
-- Also logged:
--   1 row to public.honesty_violations (domain=GOLD_STANDARD_CAMPAIGN, severity=CRITICAL)
--   8 rows to public.gold_standard_ultraloop_audit (letters A,B,C,D,E,F,I,J,
--     survived=false) — G and H are independent of this synthetic data (G is
--     zoning-only, H is freshness-only) and were left untouched.
--
-- This file is a no-op if re-run (the DML already executed live); it exists so
-- `supabase db push` / migration history stays consistent with the live schema
-- audit trail, matching this repo's established convention for prior reverts.
SELECT 1;
