-- SHARD-1 (leon/okeechobee/broward/flagler/liberty) — pass 2 on dispatch aab9f1da-a0da-4a2d-a18c-63b1a4d938da
-- (issue #11370, chat_session architect-20260710T000000). Pass 1 of this exact
-- dispatch already shipped in 20260710_shard1_broward_taxdeed_lane_okeechobee_rescrape_flag.sql
-- (commit 038d0071, session log .claude/session-logs/2026-07-10-11370.yml).
-- This is a re-fire of the same dispatch; re-verified live state first (per
-- HONESTY PROTOCOL) rather than trusting the brief's stated baseline, found
-- real organic drift since pass 1 (leon 153->162 auctions, okeechobee 30->54),
-- and shipped two more VERIFIED, non-fabricating fixes via re-invocation of
-- existing reusable, idempotent, already-precedented functions/scripts.
--
-- Diagnosis + adversarial verification done via ULTRALOOP workflow
-- wf_4a0e7e7e-801 (one diagnose + one refuter agent per county/letter).
-- Both applied fixes below were independently re-derived and confirmed by
-- this session's own live queries before execution (not just accepted from
-- the workflow), and the workflow's refuters separately confirmed no
-- fabrication risk on the underlying data (only flagged an execution-plan
-- defect on the leon C/D live-AJAX proposal, which was NOT attempted — see
-- "NOT ATTEMPTED" section below).
--
-- ═══════════════════════════════════════════════════════════════════════════
-- 1) LEON — Criterion J: ran scripts/shard5_leon_j_generator.py, scoped to
--    'leon' only (NOT the other 3 counties in that script's TARGET_COUNTIES
--    list, which belong to other shards -- invoked process_county('leon')
--    directly to respect PARALLEL-FLEET RULES). ARV computed from each row's
--    REAL assessed_value/market_value/opening_bid (all 9 gap rows used the
--    opening_bid*1.4 branch with real opening_bid values, e.g. 397823.48,
--    213441.99, ... 9255.87 -- verified, not the $175K blind fallback).
--    ml_score=0.65 is the same pre-existing INFERRED baseline already used
--    for leon's other 151 bid_decisions rows (not a new fabrication).
--
--    RESULT: 11 bid_decisions rows inserted (9 net-new gap rows + 2 more
--    incomplete rows the script found beyond this session's initial 9-row
--    diagnosis). Idempotent -- 151 already-complete rows were skipped
--    untouched, 0 patched.
--
--    VERIFIED before/after via pencil_dod_evaluate_county('leon'):
--      J: metric=93.2 (deal_complete=151 of 162) FAIL -> metric=100.0
--         (deal_complete=162 of 162) PASS
--    No other letter regressed (A/B/F/G/H unchanged PASS; C/D/E/I unchanged
--    FAIL -- see "NOT ATTEMPTED" below for why).
--
-- (No SQL to replay -- reproduce via: SUPABASE_SERVICE_ROLE_KEY=... python3 -c
--  "import sys; sys.path.insert(0,'scripts'); import shard5_leon_j_generator as g; g.process_county('leon')")
--
-- ═══════════════════════════════════════════════════════════════════════════
-- 2) OKEECHOBEE — Criterion C/D: ran scripts/shard9_okeechobee_taxsmartweb_litmus.py
--    okeechobee <22 TD-format case numbers> -- the 22 of 24 freshly-scraped
--    (2026-07-10T00:10Z calendar_sweep_mca_v3) rows in TD case-number format.
--    This hits the Okeechobee Clerk's own free/anonymous Pioneer TaxSmartWebLive
--    system directly (confirmed reachable, HTTP 200, no login/CAPTCHA) and
--    compares parcel_id + opening_bid against the real clerk record before
--    writing parity_status -- never fabricates a match.
--
--    RESULT: all 22 cases matched_clean against the live clerk record (0
--    matched_divergent, 0 not_found). The remaining 2 new rows are CA-format
--    civil-foreclosure cases; their only known litmus source (Civitek OCRS)
--    is Cloudflare-Turnstile-gated and was correctly left untouched --
--    NO_SAFE_FIX, not attempted, not fabricated.
--
--    VERIFIED before/after via pencil_dod_evaluate_county('okeechobee'):
--      C: metric=44.4 (matched_clean=24 of 54) FAIL -> metric=85.2
--         (matched_clean=46 of 54) still FAIL (2 CA rows + other pre-existing
--         gaps remain, but real, verified progress toward the 95% bar)
--      D: metric=55.6 (matched_any=30 of 54) FAIL -> metric=96.3
--         (matched_any=52 of 54) PASS
--    No other letter regressed.
--
-- (No SQL to replay -- reproduce via: SUPABASE_SERVICE_ROLE_KEY=... python3
--  scripts/shard9_okeechobee_taxsmartweb_litmus.py okeechobee 2026TD051
--  2026TD053 2026TD054 2026TD056 2026TD057 2026TD058 2026TD059 2026TD060
--  2026TD061 2026TD062 2026TD063 2026TD064 2026TD065 2026TD066 2026TD067
--  2026TD068 2026TD069 2026TD071 2026TD073 2026TD074 2026TD077 2026TD078)
--
-- ═══════════════════════════════════════════════════════════════════════════
-- NOT ATTEMPTED (flagged, not fabricated):
-- - leon C/D (9 new rows, 94.4%->94.4%, unchanged): requires a live AJAX
--   re-fetch of leon.realforeclose.com/leon.realtaxdeed.com -- confirmed
--   HTTP 403 from this sandbox (same WAF/datacenter-IP block documented in
--   SHARD4_RUN3497_SESSION_REPORT.md for other RealAuction-family hosts).
--   The workflow's own refuters additionally found the proposed script
--   (scripts/shard9_run3059_citrus_manatee_cd_parity.py:exact_match_and_promote)
--   has a real scope bug (misses case 2025 CA 001966, auction_date=today,
--   outside the proposal's date filter) and a mislabeled matched_divergent
--   code path -- so even with network access this specific reuse would need
--   a fix first, not a blind re-run.
-- - leon E/I (10/16 rows missing parcel_id/geo/value): no ArcGIS FeatureServer
--   or appraiser GIS endpoint is configured for leon in pipeline.counties
--   (parcel_data_source/parcel_data_url both NULL) and no leon-specific
--   linkage script exists in scripts/ -- genuine new-build scope, not a
--   backfill-not-triggered situation. Not attempted.
-- - okeechobee E/I/J residual (2 CA rows, 24 newly-enriched-nothing rows):
--   same story -- calendar_sweep_mca_v3 writes only case/date/status fields,
--   no address/geo/value; okeechobee has zero zoning-card coverage
--   (v_zoning_gold_standard_card zone_code count=3 countywide) and no
--   appraiser GIS wired. Real build gap, flagged not faked.
-- - broward A: pipeline.counties taxdeed lane confirmed still correctly wired
--   from pass 1. Dispatched .github/workflows/county-outcome-harvest.yml
--   (county=broward, live, run 29063256424) to attempt a real td/outcome
--   harvest -- it reached broward.realforeclose.com from the GHA runner (no
--   WAF block there) but the RealAuction login itself failed ("may have
--   failed", 0 AITEM blocks across all 6 months probed), so 0 rows were
--   added. The harvester explicitly SKIPPED its self-referential
--   ghost-success fallback paths per its own guardrail. Real attempt, real
--   (auth) failure, zero fabrication -- run log is the evidence.
-- - broward I (55/635 card gaps): fl_parcels/parcel_cache/fl_parcel_assessments
--   all return ZERO rows for Broward (co_no=6) -- confirmed by both this
--   session and the workflow's diagnose agent independently. No safe bulk
--   backfill source exists; needs a real Broward BCPA GIS/appraiser
--   ingestion pass (new build). Not attempted.
-- - flagler B/C/D/F: confirmed via git history
--   (20260703_shard1_miami_dade_matcher_reinvoke_flagler_fabrication_revert.sql)
--   that flagler's B/C/D/F PASS was previously built entirely on fabricated
--   outcome data and correctly reverted 2026-07-03. The current honest state
--   (30 sold/completed rows, sold_amount=NULL on all of them) is NOT a new
--   bug -- it is flagler's real, unfabricated ceiling until a genuine
--   headless-render scrape of the bot-blocked flagler.realforeclose.com /
--   flagler.realtaxdeed.com exists. Did not touch tax_deed_outcomes,
--   foreclosure_outcomes, sold_amount, or parity_status for flagler this
--   session. A workflow diagnose agent's claim that these hosts were
--   "confirmed HTTP-200-reachable" from this sandbox does NOT hold up --
--   independently re-curled both hosts this session and got 403, matching
--   every other RealAuction-family host tested. Flagged, not acted on.
-- - liberty: re-checked live, unchanged since pass 1 -- 1 auction
--   (case 24-CA-22), sale date 2026-07-21 (future), needs_source_rescrape
--   still false. Genuinely near-empty, not under-scraped. No action.
--
-- FLAGGED FOR FOLLOW-UP (not this session's scope to fix):
-- - scripts/shard3_broward_a_fix.py + supabase/migrations/20260626_shard3_broward_a_fix.sql
--   contain a ready-to-run data-fabrication path (synthetic tax_deed row,
--   data_source='synthetic_seed', explicitly designed to flip broward's A
--   metric with fake data). Confirmed this synthetic row does NOT currently
--   exist live in multi_county_auctions (0 matches), so no live damage --
--   but the script remains a live landmine in the repo that would fabricate
--   data if a future session naively re-ran it. Recommend quarantine/removal
--   in a dedicated cleanup pass; not modified here per K3 surgical-change
--   discipline (out of this session's stated scope).
