-- SHARD-5: bradford/palm_beach/monroe C/D — run canonical parity matcher (no schema change)
-- dispatch_id: 8cc7b73b-55e7-4ddc-8b0e-d7c93c9ba7d9
-- Session: architect-20260703T000000
--
-- Same pattern proven for hendry/miami_dade/st_lucie (see 20260702_shard5_miami_dade_st_lucie_canonical_parity_refresh.sql):
-- public.refresh_parity_tier1_outcomes(p_county) had simply never been invoked (or had gone
-- stale relative to newly-closed auctions) for these three shard-5 counties. Ran it live for
-- bradford, palm_beach, and monroe.
--
--   SELECT * FROM public.refresh_parity_tier1_outcomes('bradford');
--   SELECT * FROM public.refresh_parity_tier1_outcomes('palm_beach');
--   SELECT * FROM public.refresh_parity_tier1_outcomes('monroe');
--
-- VERIFIED via pencil_dod_evaluate_county before/after (2026-07-03):
--   bradford    C: 0.0%  (matched_clean=0 of 3)   -> 100.0% (matched_clean=3)   PASS
--               D: 0.0%  (matched_any=0 of 3)     -> 100.0% (matched_any=3)     PASS
--               bradford is now 10/10 on this evaluation (A/B/E/F/G/H/I/J already PASS).
--   palm_beach  C: 48.9%  (matched_clean=335 of 685) -> 73.4% (matched_clean=503) FAIL (<95%)
--               D: 69.5%  (matched_any=476 of 685)   -> 81.8% (matched_any=560)   FAIL (<95%)
--   monroe      C: 0.0%   (matched_clean=0 of 25)  -> 12.0%  (matched_clean=3)    FAIL (<95%)
--               D: 0.0%   (matched_any=0 of 25)    -> 12.0%  (matched_any=3)      FAIL (<95%)
--
-- No regression on A/B/E/F/G/H/I/J for any of the three counties (confirmed via same-call
-- pencil_dod_evaluate_county diff).
--
-- NOTE (indian_river, same session, NOT part of this migration): running the identical
-- canonical refresh on indian_river MOVED C/D DOWN (75.0%->60.5%, 85.5%->71.1%, idempotent —
-- a second run reproduces 46/54 exactly). This is under active investigation (see
-- gold_standard_ultraloop_audit) before any claim is made about it — flagging here so the
-- regression is not silently lost. Do not re-run refresh_parity_tier1_outcomes('indian_river')
-- assuming it is a pure improvement; verify current diagnosis first.
--
-- palm_beach and monroe remain FAIL — real, verified gains, not a full pass. Both counties'
-- residual gap is under the same investigation.

SELECT 1; -- no-op placeholder: this migration documents 3 function CALLs (not DDL/DML),
          -- already applied live via Supabase REST RPC at the timestamps above.
