-- SHARD-2 run3025 (miami_dade): E parcel_id backfill (VERIFIED) + C/D address-litmus
-- self-caught-and-reverted (would have been a ghost-success repeat)
-- dispatch_id: 0d3f71c9-addf-430c-adc2-19f399ac39ad
-- Session: architect-20260704T160000
--
-- PART 1 — E FIX (SHIPPED, VERIFIED):
-- 3 of 18 miami_dade auctions missing parcel_id had real, findable folios on
-- Miami-Dade's own ArcGIS backend (MD_PA_PropertySearch, MapServer layer 0,
-- https://gisfs.miamidade.gov/mdarcgis/rest/services/MD_PA_PropertySearch/MapServer/0/query),
-- verified independently via an adversarial-refuter subagent (byte-for-byte
-- JSON reproduction on re-query). The other 3 candidate addresses in the same
-- batch were correctly left NULL (UNVERIFIED) rather than guessed:
--   - 29490 SW 193RD AVE, Homestead: no such house number exists (confirmed
--     neighbors 29470/29500, nothing between)
--   - 8300 NW 10TH ST #K-1, Miami: base complex real (126-unit condo), but no
--     unit "K-1" exists in the county's own address index (units are 1-126)
--   - 1401 NE 195TH STREET #180, Doral: geographically inconsistent input --
--     NE-prefixed street numbering does not occur in Doral (NW-only grid);
--     NE 195 ST would fall in Aventura/North Miami Beach, not zip 33178
--
-- ACTION TAKEN (live, via Supabase Management API SQL endpoint):
--   UPDATE multi_county_auctions SET parcel_id = <verified folio>
--   WHERE county='miami_dade' AND case_number IN (
--     '2022-010471-CA-01'  -> 3411350312890  (20503 NW 11TH AVE, Miami Gardens)
--     '2025-022077-CA-01'  -> 2822030633460  (3215 NE 184 ST #206, Aventura)
--     '2025-016575-CA-01'  -> 3022320530001  (11111 Biscayne Blvd, Miami; master/parent folio)
--   ) AND parcel_id IS NULL;
--   -- 4 rows affected (2025-016575-CA-01 exists as a pre-existing duplicate
--   -- row in multi_county_auctions -- both copies updated; duplicate itself
--   -- is a separate, out-of-scope data-quality issue, flagged not fixed here).
--
-- VERIFIED via pencil_dod_evaluate_county('miami_dade') live 2026-07-04:
--   BEFORE: E=94.9%% (parcel_linked=338/356) FAIL
--   AFTER:  E=96.1%% (parcel_linked=342/356) PASS
--   None of the 3 newly-linked folios exist in v_zoning_gold_standard_card
--   (checked before shipping), so I is unaffected by this change (335/356,
--   still FAIL) -- not claimed as a side-effect win.
--
-- PART 2 — C/D SELF-REVERT (NOT SHIPPED, logged for audit trail):
-- Independently root-caused why miami_dade C/D sits at 1.4%% (5/356): 350 of
-- 356 tier1 rows have parity_status IS NULL (parity check never run), and a
-- naive address-normalization join against the 8,997 propertyonion-sourced
-- rows in the same table found 88 matches (fixing a real bug where PO
-- appends ordinal suffixes to numbered streets, e.g. "40th" vs our "40").
-- Before shipping this as parity_status='matched_clean' /
-- parity_source='tier1_po_address_litmus_shard2_run3025', found
-- 20260704_shard4_miami_dade_cd_systemic_ghost_success_revert.sql (committed
-- HOURS earlier, same day) documenting that an *identical* address-only
-- litmus pattern (94.9%% claimed, only 5/338 backed by a real
-- tax_deed_outcomes/foreclosure_outcomes row) had just been reverted to an
-- honest 1.4%%. My 88-row update would have reintroduced the exact same
-- fabrication pattern the prior session spent its session catching.
--
-- ACTION TAKEN: reverted the 88-row UPDATE in the same session, before any
-- commit. DB confirmed back at C=1.4%% D=1.4%% (matched_clean=5) via
-- pencil_dod_evaluate_county. No net change shipped for C/D this session.
--
-- Logged: gold_standard_ultraloop_audit (2 rows: E survived=true with
-- refuter evidence citing the ArcGIS source + byte-for-byte re-query;
-- C flagged survived=false documenting the self-caught near-miss).
--
-- RESIDUAL / next session: C/D genuinely require, per the established
-- canonical rule, a real tax_deed_outcomes/foreclosure_outcomes row per
-- case_number -- there is no shortcut via PropertyOnion address matching.
-- I remains at 94.1%% (335/356); the 21-row gap needs either more parcel_id
-- backfills that ALSO exist in v_zoning_gold_standard_card, or zoning
-- ingestion coverage for the specific missing folios.

SELECT 1; -- no-op placeholder: documents live UPDATE/INSERT already applied
          -- via api.supabase.com/v1/projects/mocerqjnksmhcjzxrewo/database/query
          -- with SUPABASE_ACCESS_TOKEN (verified before/after above).
