-- SHARD-6 (dispatch_id cc6bdc10-6b93-496a-bcd6-7919ff2757cf): hillsborough C/D
-- ghost-success purge + canonical rematch. Applied live via Supabase Management
-- API SQL endpoint (api.supabase.com/v1/projects/mocerqjnksmhcjzxrewo/database/query
-- with SUPABASE_ACCESS_TOKEN) -- this session had no working direct psql/pooler
-- auth (both password-auth'd hosts rejected the SUPABASE_DB_PASSWORD env value),
-- same limitation documented in 20260703_shard10_desoto_jackson_orange_volusia_cd_ghost_success_purge.sql.
--
-- ROOT CAUSE: 194 hillsborough rows carried parity_status IN
-- ('matched_clean','matched_divergent') with parity_source IN
-- ('tier1_supervisor_parity_restore_20260623', 'tier1_official_platform_open_auction_parcel',
--  'tier1_official_platform_open_auction_address', 'tier1_realforeclose_hillsborough')
-- and ZERO backing in tax_deed_outcomes/foreclosure_outcomes by
-- normalize_case_number(case_number). Two of the four labels ('tier1_supervisor_
-- parity_restore_20260623', 'tier1_realforeclose_hillsborough') have no source file
-- anywhere in the repo -- untraceable. The other two were created by
-- supabase/migrations/20260702_shard7_citrus_hillsborough_nassau_suwannee_cd_parity.sql
-- lines 58-70, whose comment claims "official-platform parcel_id/address presence"
-- but whose actual SQL condition is self-referential:
--   WHERE county='hillsborough' AND auction_status='upcoming' AND parity_status IS NULL
--     AND parcel_id IS NOT NULL AND length(parcel_id)>=8   -- (clean variant)
--   WHERE ... AND property_address IS NOT NULL AND property_address ~ '^[0-9]'  -- (divergent variant)
-- Neither condition queries any external platform -- it only checks that OUR OWN
-- row already has a parcel_id/address, then stamps a source label implying
-- independent verification. This is the exact ghost-success pattern already
-- purged today (same session-day) for jackson/orange/volusia, and directly
-- violates the pencil_dod_criteria INTEGRITY RULE (2026-06-14): "Independent-
-- source ONLY... must not be relaxed to reach a pass."
--
-- STEP 1 (BEFORE, live query): SELECT public.pencil_dod_evaluate_county('hillsborough');
--   C: pass=false matched_clean=848 metric=92.6  (fabricated -- 194 of these rows unbacked)
--   D: pass=true  matched_any=903   metric=98.6  (FALSE PASS -- fabricated)
--
-- STEP 2 (ACTION, live, this session):
--   UPDATE multi_county_auctions SET parity_status=NULL, parity_source=NULL, updated_at=now()
--   WHERE county='hillsborough' AND parity_source IN (
--     'tier1_supervisor_parity_restore_20260623',
--     'tier1_official_platform_open_auction_parcel',
--     'tier1_official_platform_open_auction_address',
--     'tier1_realforeclose_hillsborough');
--   -- 194 rows purged (110 + 59 + 10 + 15), confirmed via RETURNING count.
--
--   SELECT * FROM public.refresh_parity_tier1_outcomes('hillsborough');
--   -- existing shared canonical matcher, UNCHANGED. Rematches all closed-status
--   -- (redeemed/completed/sold/cancelled/canceled) rows against
--   -- tax_deed_outcomes/foreclosure_outcomes by case_number then parcel_id.
--
-- STEP 3 (AFTER, live query): SELECT public.pencil_dod_evaluate_county('hillsborough');
--   C: pass=false matched_clean=709 metric=77.4  (honest, down from fabricated 92.6)
--   D: pass=false matched_any=709   metric=77.4  (honest, down from FALSE PASS 98.6)
--
-- STRUCTURAL CEILING (verified independently, not just asserted): the evaluator's
-- auctions_total denominator (916) scopes to (data_source<>'propertyonion' OR
-- tier1_authoritative=true) with NO auction_status filter. Breakdown of those 916:
-- redeemed=273, cancelled=249, completed=187 (709 closed total), upcoming=207.
-- C/D can only ever be satisfied by closed-status rows, because upcoming auctions
-- have no sale outcome yet to match against by definition. A follow-up query
-- joining scope to tax_deed_outcomes/foreclosure_outcomes via
-- normalize_case_number for closed-status rows ONLY returned 709/709 backed --
-- i.e. the canonical matcher already achieves 100% coverage of the matchable
-- population. REAL CEILING = 709/916 = 77.4%, which is exactly what the AFTER
-- metric shows. C/D cannot improve further this session without the 207 upcoming
-- auctions closing over time and getting real outcome records -- not a bug, not
-- fixable by more relabeling.
--
-- Adversarially verified (independent refuter agent, same session): claim
-- SURVIVED -- live re-run reproduced 709/77.4% exactly, ghost labels confirmed
-- zero remaining, 5 spot-checked matched_clean rows confirmed backed by real
-- tax_deed_outcomes rows (data_source hillsborough_realtaxdeed_official /
-- hillsborough_realtaxdeed_sold, not '%promote%').
--
-- No other county touched by this migration. gold_standard_loop()/
-- gold_standard_certify() NOT invoked (other shards run concurrently).

SELECT 1; -- no-op placeholder: documents the live UPDATE + refresh_parity_tier1_outcomes('hillsborough')
          -- calls already applied via the Supabase Management API SQL endpoint in this session.
