-- SHARD-9: citrus/lafayette/suwannee/manatee C/D — canonical parity matcher + manatee regression forensics
-- dispatch_id: cc40d3bf-95ed-4508-8e0d-6e1c29dd101c
-- Session: architect-20260703T080000
--
-- Same lever proven for bradford/palm_beach/monroe/hendry/miami_dade/st_lucie today (see
-- 20260703_shard5_bradford_palmbeach_monroe_canonical_parity_refresh.sql):
-- public.refresh_parity_tier1_outcomes(p_county) had never been (re-)invoked for this shard's
-- 4 counties. Ran it live for all four via ULTRALOOP fix+adversarial-verify workflow (fixer
-- agent runs the RPC and captures before/after; independent refuter agent re-queries live DB
-- and checks all 10 letters for regressions before a claim survives):
--
--   SELECT * FROM public.refresh_parity_tier1_outcomes('citrus');
--   SELECT * FROM public.refresh_parity_tier1_outcomes('lafayette');
--   SELECT * FROM public.refresh_parity_tier1_outcomes('suwannee');
--   SELECT * FROM public.refresh_parity_tier1_outcomes('manatee');
--
-- VERIFIED via pencil_dod_evaluate_county before/after (2026-07-03, independently re-confirmed
-- by a refuter agent with no stake in the fixer's claim):
--
--   citrus     C: 31.0% (matched_clean=54 of 174) -> 31.6% (matched_clean=55)   FAIL
--              D: 35.1% (matched_any=61 of 174)   -> 35.1% (matched_any=61)     FAIL (unchanged)
--              Structural gap, not a bug: 114 of 174 auctions are closed-like but only 61 have
--              ANY independent outcome match today. Closing this needs more independent
--              foreclosure_outcomes/tax_deed_outcomes coverage for citrus, not another matcher run.
--   lafayette  C: 0.0% (matched_clean=0 of 2) -> 100.0% (matched_clean=2)   PASS
--              D: 0.0% (matched_any=0 of 2)   -> 100.0% (matched_any=2)     PASS
--              lafayette is now 10/10 on this evaluation (all letters PASS).
--   suwannee   C: 50.0% (matched_clean=2 of 4) -> 100.0% (matched_clean=4)  PASS
--              D: 50.0% (matched_any=2 of 4)   -> 100.0% (matched_any=4)    PASS
--              2 auctions transitioned from upcoming to closed between the shard brief snapshot
--              and this session and matched clean immediately. suwannee is now 10/10.
--   manatee    C: 40.6% (matched_clean=28 of 69) -> 26.1% (matched_clean=18)  FAIL, WORSE
--              D: 40.6% (matched_any=28 of 69)   -> 26.1% (matched_any=18)    FAIL, WORSE
--
-- MANATEE REGRESSION — ROOT-CAUSED, NOT A BUG IN THIS SESSION:
-- A concurrent shard-6 session fixed a case-sensitivity bug in refresh_parity_tier1_outcomes
-- earlier the same day (20260703_shard6_refresh_parity_case_sensitivity_fix.sql), tightening the
-- matcher. Invoking the corrected matcher for manatee reset all closed-like rows' parity_status
-- to NULL and only re-matched 5 of ~15 previously "tier1_"-labeled closed-like rows.
--
-- Investigated directly (live queries, this session): foreclosure_outcomes has exactly 5 rows
-- for manatee, ALL outcome='sold' (matching the 5 completed auctions 1:1); tax_deed_outcomes has
-- ZERO manatee rows. There is therefore NO independent outcome record for any of manatee's 16
-- cancelled auctions — none could ever have been genuinely matched via an outcomes-table join.
-- The pre-session 40.6% baseline's tier1-prefixed matched_clean labels on cancelled rows could
-- not have come from a real join; they were a ghost-success artifact (consistent with the several
-- other ghost-success corrections other shards found and reverted today: bradford, columbia,
-- franklin, escambia's E-linkage-mislabeled-as-C/D).
--
-- Attempted one restorative fix: re-applied the same clerk-supplementary pattern pre-authorized
-- 2026-06-19 for manatee (20260619_shard11_cd_clerk_supplementary.sql — "records sourced FROM the
-- official realforeclose platform ARE already clerk-verified") to the 14 newly-null cancelled
-- rows with source_platform='realforeclose' AND tier1_authoritative=true. Verified this did NOT
-- move the evaluator's C/D metric at all (confirmed by two independent live RPC calls) because
-- pencil_dod_evaluate_county was tightened on 2026-07-02
-- (20260702_shard1_pencil_dod_cd_tier1_filter.sql) to additionally require
-- `parity_source LIKE 'tier1%'` — a requirement the clerk-supplementary label never satisfied,
-- then or now. Since the label could not move the metric and does not represent genuine
-- independent third-party verification, REVERTED it (parity_status/parity_source back to NULL)
-- rather than leave a cosmetic, non-counting label on the data. BLANK > WRONG.
--
-- Current honest ceiling for manatee C/D is 26.1%, verified. Closing this gap requires either
-- (a) real independent clerk/court records confirming cancelled-auction outcomes for manatee
-- (which do not appear to exist in the tax_deed/foreclosure_outcomes tables today), or (b) an
-- architecture decision on whether "cancelled" auctions with no independent outcome record should
-- even be in the C/D denominator — flagging for AI Architect review, not deciding unilaterally.
--
-- No regression introduced on A/B/E/F/G/H/I/J for any of the four counties (confirmed via
-- same-call pencil_dod_evaluate_county diff, independently re-verified live).
--
-- All 7 claims (citrus C/D no-op-improvement, lafayette C+D pass, suwannee C+D pass, manatee
-- C+D regression-diagnosed-not-a-bug) logged to gold_standard_ultraloop_audit with survived flags
-- (true for citrus/lafayette/suwannee, false for manatee C/D pending the architecture decision
-- above).
--
-- manatee A (fc=69 td=0, tax-deed lane) and G (density 90.4%) NOT touched this session: A requires
-- inspecting/configuring pipeline.counties, which lives in the `pipeline` schema and was not
-- reachable via the REST credentials available in this sandbox (schema not exposed by PostgREST;
-- no supabase CLI installed; direct psql to the pooler with SUPABASE_DB_PASSWORD returned password
-- auth failure). Flagging as a genuine environment blocker for a future session with working
-- CLI/psql access, not attempting a fabricated fix.

SELECT 1; -- no-op placeholder: this migration documents 4 function CALLs + 1 attempted-then-
          -- reverted restorative UPDATE (already applied/reverted live via Supabase REST at the
          -- timestamps above) plus 7 gold_standard_ultraloop_audit inserts. No DDL/DML shipped
          -- via this file.
