-- SHARD-12: osceola PropertyOnion contamination cleanup
-- dispatch_id: 39e3e3d9-cc68-48ac-8a52-16d81b21bbb6
-- Session: architect-20260702T080000 (gold standard shard-12: st_lucie, osceola)
--
-- ROOT CAUSE (VERIFIED live 2026-07-02 via REST queries against multi_county_auctions):
-- Same fleet-wide pattern already documented and cleaned today for
-- escambia (20260702_shard10_escambia_propertyonion_contamination_cleanup.sql),
-- orange/marion (20260702_shard7_orange_marion_propertyonion_contamination_cleanup.sql),
-- and hillsborough/lee (20260702_shard5_evaluator_propertyonion_exclusion.sql):
-- a bulk insert on 2026-07-01 wrote data_source='propertyonion' rows into
-- multi_county_auctions under county='osceola'. This directly violates the
-- standing HARD GUARDRAIL: "PropertyOnion = litmus ONLY. Never ingest as a
-- data source."
--
-- osceola: 516 of 648 total rows (79.6%) carried data_source='propertyonion',
-- synthetic case_number ('PO-xxxxxx'), created_at='2026-07-01', and ZERO
-- sold_amount across the full 516-row sample (is_operational=true on only
-- 11/516). parity_status and parcel_id were populated on most of these rows
-- (516/516 and 507/516 respectively) but this is irrelevant to scoring --
-- pencil_dod_evaluate_county already filters data_source='propertyonion'
-- fleet-wide, confirmed by auctions_total=132 exactly equal to
-- 648-516=132 both before and after this delete. Zip distribution (33896,
-- 34772, 34759, 34743, 34747, 34758, 34741, 34744, 34769, 34746) confirms
-- genuine Osceola/Kissimmee/St Cloud/Poinciana addresses, so no cross-county
-- relabeling was needed -- pure denominator bloat in the base table only.
--
-- pencil_dod_evaluate_county already excludes data_source='propertyonion'
-- fleet-wide, so this cleanup is a no-op on evaluator metrics by design --
-- verified identical before/after JSON (both 10/10, auctions_total=132).
-- Removes the now-inert rows from the base table so future raw-count
-- audits and downstream jobs aren't fooled by them.
--
-- VERIFIED live via pencil_dod_evaluate_county before and after deletion:
--   osceola BEFORE (evaluator, filter already active): auctions_total=132,
--     A pass fc=3/td=129 (metric=3) B 100.0 C 100.0 D 100.0 E 100.0 F 100.0
--     G 100.0 H 4.2h I 100.0 J 100.0 -- all PASS (10/10).
--   osceola AFTER: identical (evaluator filter made this a no-op on metrics
--     by design); raw multi_county_auctions row count for osceola drops
--     from 648 to 132, all data_source <> 'propertyonion'.
--
-- Applied live 2026-07-02 via the PostgREST DELETE endpoint (before this
-- file was committed) -- this migration documents and reproduces that change.

DELETE FROM multi_county_auctions
WHERE lower(county) = 'osceola'
  AND data_source = 'propertyonion';
