-- shard5 run2550 (2026-07-03): highlands C/D parity backfill + broward/columbia diagnosis notes
--
-- Applied LIVE via Supabase Management API (service role / access token), not psql (direct DB
-- connection creds in this environment rejected auth on both us-west-2 and us-east-1 poolers;
-- Management API + PostgREST worked throughout). This file is a durable record of the equivalent
-- SQL for repo history / future migration replay.
--
-- Shard: nassau, highlands, santa_rosa, broward, columbia (dispatch_id e54310ee-b545-4ca5-9e3a-
-- b3525c130bf8, session architect-20260703T080000).
--
-- ULTRALOOP: ran a Workflow with one diagnose agent + one adversarial refuter agent per
-- county x failing-letter group (19 agents total, 491 live read-only tool calls). Of all
-- diagnosed root causes, exactly ONE survived as fixable+safe+unrefuted: highlands C/D was
-- never actually parity-matched (the shard5 clerk-supplement script overwrote all 144 rows with
-- parity_status='mca_only' without ever running the canonical matcher). Every other diagnosis
-- was either confirmed-blocked (structural: needs new scraper/ingestion, not SQL) or was itself
-- refuted by the adversarial pass (broward C/D fix attempts had denominator errors; nassau C's
-- 6 divergent rows are honestly divergent -- a prior attempt to force them clean via amount
-- reconciliation on a $150k placeholder value was already adversarially reverted in an earlier
-- session, commits 4732f443 + c152bb48, and this session's independent re-diagnosis reached the
-- identical conclusion).

-- 1) highlands: run the existing, unmodified, already-approved canonical matcher. No schema or
--    function changes -- this call was simply never made for highlands before.
--    Result (VERIFIED via pencil_dod_evaluate_county before/after, live 2026-07-03):
--      C: 0.0% (0/144) -> 2.1% (3/144)   [still FAIL -- 141 remaining rows are BLOCKED, see below]
--      D: 0.0% (0/144) -> 2.1% (3/144)   [still FAIL, same]
--      No other letter changed (B/E/F/G/H/I/J unaffected -- confirmed no regression).
SELECT * FROM public.refresh_parity_tier1_outcomes('highlands');

-- highlands 141-row residual is BLOCKED, not SQL-fixable this session: 139 upcoming tax_deed rows
-- (data_source='calendar_sweep_mca_v3') and 2 bootstrap_placeholder foreclosure rows have no tier1
-- litmus source at all -- pipeline.counties.foreclosure_platform / taxdeed_platform are both NULL
-- for highlands despite realauction_subdomains showing active realtaxdeed/realforeclose/realtdm
-- subdomains already discovered (parity_verdict='PO has data -- activating'). Needs a highlands-
-- specific RealAuction litmus matcher built + pipeline.counties wired -- an ingestion/scraper task
-- for a future session, not a SQL backfill.

-- 2) broward + columbia: no SQL fix applied (none survived adversarial verification as safe).
--    Root-cause findings recorded as durable notes on pipeline.counties for the next session --
--    see notes column, county_slug IN ('broward','columbia'), appended 2026-07-03. Summary:
--      broward A: real, live, active tax-deed platform found at broward.realtdm.com (RealTDM,
--        HTTP 200, "realTDM : Broward - Case Search"). Existing generalized scraper
--        (scripts/realtdm_county_sweep.py) + RPC (public.upsert_county_realtdm_mca) need ZERO
--        code changes -- already correctly set sale_type='tax_deed'. BLOCKED: the case list is
--        JS-rendered; both raw curl and a headless Chromium session got 403 on the site's own
--        static JS bundle, and no FIRECRAWL_API_KEY was present in this runner to escalate to
--        firecrawl-browser. Not a missing-tenant problem (unlike columbia) -- a rendering/access
--        problem for a confirmed-live platform.
--      columbia A: still zero rows fleet-wide (0 in multi_county_auctions, confirmed absent from
--        the full 62-county distinct list). columbiaclerk.com returns Cloudflare 403 to plain
--        curl; no FIRECRAWL_API_KEY present to attempt the Firecrawl escalation documented by the
--        prior 2026-07-02 session. Standing infra blocker (API key), not a new finding.
--      broward C/D: two proposed fix attempts (targeting 'tier1_only' rows and a corrected
--        denominator) were BOTH refuted by the independent adversarial pass (denominator/row-
--        count mismatches under re-query) -- correctly not applied. broward C/D remain a genuine
--        coverage gap: 635 total rows, only ~500 have ANY independent outcome record to match
--        against.
--      broward I: 91.3% (580/635), 55-row gap broken down (19 missing value only, 19 missing
--        lat/lon only, 6 missing addr+value, 5 missing lat/lon+value+zone, 3 missing addr+value
--        w/ null parcel_id, 3 missing zone-link only). No verified real data source available this
--        session to backfill assessed_value or real geocodes -- NOT force-filled. Separately
--        flagged (not acted on): 19 of these rows share an identical lat/lon (26.1224,-80.1373)
--        across different addresses in the CURRENTLY-PASSING 580 -- looks like a placeholder
--        centroid inflating I's current count; needs future audit.

-- NEVER-LIE: nassau (9/10, C-only fail), santa_rosa (8/10, C/D fail) were diagnosed in depth this
-- session and NOT touched -- santa_rosa's C/D gap (44/63 matched, 19 rows parity_status='mca_only'
-- with synthetic/short case-number formats from a clerk-supplement scraper) needs real case-number
-- backfill from the clerk source before matching, not a SQL guess; nassau's 6-row C gap is honest,
-- already-adjudicated divergence (see above). Neither was force-fixed.
