#!/usr/bin/env python3
"""
COLUMBIA County RealAuction Scraper
Auto-generated by SHARD-7 bootstrap - 2026-06-13

Scrapes auction listings from https://www.realauction.com/florida-auctions/columbia-county
Writes to multi_county_auctions table with source_platform=realauction

WIRING MANDATE: This scraper is scheduled via GitHub Actions workflow
"""
import os
import sys
import json
from datetime import datetime, timezone
from typing import List, Dict, Optional

try:
    import httpx
    print("✅ Using httpx for HTTP client")
except ImportError:
    try:
        import requests as httpx_fallback
        print("✅ Using requests as HTTP client fallback")
        # Create httpx-like interface with requests
        class HTTPXClient:
            def __init__(self, timeout=30):
                self.timeout = timeout
            def __enter__(self):
                return self
            def __exit__(self, *args):
                pass
            def get(self, url, headers=None):
                return httpx_fallback.get(url, headers=headers, timeout=self.timeout)
        httpx = type('httpx', (), {'Client': HTTPXClient})()
    except ImportError:
        print("❌ No HTTP client available")
        sys.exit(1)

try:
    from bs4 import BeautifulSoup
    print("✅ BeautifulSoup available")
except ImportError:
    print("❌ BeautifulSoup not available")
    sys.exit(1)

COUNTY_SLUG = "columbia"
CO_NO = 18
BASE_URL = "https://www.realauction.com/florida-auctions/columbia-county"

# Database configuration
SUPABASE_URL = "https://mocerqjnksmhcjzxrewo.supabase.co"
SUPABASE_KEY = os.environ.get("SUPABASE_KEY", "") or os.environ.get("SUPABASE_SERVICE_KEY", "")

def get_headers():
    """Get Supabase API headers"""
    return {
        "apikey": SUPABASE_KEY, 
        "Authorization": f"Bearer {SUPABASE_KEY}",
        "Content-Type": "application/json"
    }

def scrape_realauction_listings() -> List[Dict]:
    """Scrape auction listings for columbia county"""
    print(f"Starting {COUNTY_SLUG} RealAuction scrape...")
    
    try:
        # HTTP scraping setup
        headers = {
            'User-Agent': 'Mozilla/5.0 (compatible; BidDeed-Scraper/1.0)'
        }
        
        with httpx.Client(timeout=30) as client:
            response = client.get(BASE_URL, headers=headers)
            
            if response.status_code != 200:
                print(f"❌ Failed to fetch {BASE_URL}: {response.status_code}")
                return []
            
            soup = BeautifulSoup(response.text, 'html.parser')
            
            # Extract auction listings using RealAuction common patterns
            auctions = []
            
            # Look for auction listing containers
            auction_containers = soup.find_all(['div', 'tr', 'article'], 
                                             class_=lambda x: x and any(term in x.lower() for term in ['auction', 'property', 'listing', 'sale']))
            
            print(f"Found {len(auction_containers)} potential auction containers")
            
            for i, container in enumerate(auction_containers[:50]):  # Limit to first 50 for safety
                try:
                    # Extract basic auction data with fallbacks
                    auction = {
                        'county_slug': COUNTY_SLUG,
                        'co_no': CO_NO,
                        'source_platform': 'realauction',
                        'source_url': BASE_URL,
                        'case_number': f'COLUMBIA-RA-{i+1:04d}',  # Generated case number
                        'auction_date': None,
                        'property_address': None,
                        'parcel_id': None,
                        'status': 'pending_parse',
                        'scraped_at': datetime.now(timezone.utc).isoformat(),
                        'raw_html': str(container)[:1000]  # First 1000 chars for debugging
                    }
                    
                    # Try to extract date information
                    date_elements = container.find_all(text=lambda t: t and any(month in t.lower() for month in 
                                                      ['jan', 'feb', 'mar', 'apr', 'may', 'jun', 
                                                       'jul', 'aug', 'sep', 'oct', 'nov', 'dec']))
                    if date_elements:
                        auction['raw_date_text'] = date_elements[0].strip()
                    
                    # Try to extract address information
                    address_elements = container.find_all(text=lambda t: t and ('rd' in t.lower() or 'st' in t.lower() or 'ave' in t.lower()))
                    if address_elements:
                        auction['raw_address_text'] = address_elements[0].strip()
                    
                    # Add to results
                    auctions.append(auction)
                    
                except Exception as e:
                    print(f"⚠️ Error parsing auction element {i}: {e}")
                    continue
            
            print(f"✅ Parsed {len(auctions)} auction listings for {COUNTY_SLUG}")
            return auctions
            
    except Exception as e:
        print(f"❌ Error scraping {COUNTY_SLUG}: {e}")
        return []

def persist_auctions(auctions: List[Dict]) -> int:
    """Persist auctions to Supabase database"""
    if not auctions:
        print("No auctions to persist")
        return 0
        
    if not SUPABASE_KEY:
        print("❌ No SUPABASE_KEY available - cannot persist to database")
        print(f"Would have persisted {len(auctions)} auctions")
        return 0
    
    try:
        with httpx.Client(timeout=60) as client:
            # Insert auctions into multi_county_auctions table
            response = client.post(
                f"{SUPABASE_URL}/rest/v1/multi_county_auctions",
                headers=get_headers(),
                json=auctions
            )
            
            if response.status_code in [200, 201]:
                print(f"✅ Persisted {len(auctions)} auctions to database")
                return len(auctions)
            else:
                print(f"❌ Failed to persist auctions: {response.status_code} - {response.text}")
                return 0
                
    except Exception as e:
        print(f"❌ Error persisting auctions: {e}")
        return 0

def main():
    """Main scraper function"""
    print("=== COLUMBIA COUNTY REALAUCTION SCRAPER ===")
    print(f"Target URL: {BASE_URL}")
    print(f"Timestamp: {datetime.now(timezone.utc).isoformat()}")
    print()
    
    # Scrape auctions
    auctions = scrape_realauction_listings()
    
    if not auctions:
        print("No auctions found - this may indicate the need for custom selectors")
        return
    
    # Persist to database
    persisted_count = persist_auctions(auctions)
    
    print(f"\n=== SCRAPE COMPLETE ===")
    print(f"Scraped: {len(auctions)} auctions")
    print(f"Persisted: {persisted_count} auctions")
    
    # Log execution for monitoring
    if SUPABASE_KEY:
        try:
            with httpx.Client(timeout=30) as client:
                log_entry = {
                    'entity_type': 'scraper_execution',
                    'entity_id': f'{COUNTY_SLUG}_realauction',
                    'action': 'SCRAPE_COMPLETE',
                    'details': json.dumps({
                        'scraped_count': len(auctions),
                        'persisted_count': persisted_count,
                        'url': BASE_URL,
                        'timestamp': datetime.now(timezone.utc).isoformat()
                    }),
                    'created_by': 'shard7_columbia_scraper',
                    'created_at': datetime.now(timezone.utc).isoformat()
                }
                
                client.post(
                    f"{SUPABASE_URL}/rest/v1/audit_log",
                    headers=get_headers(),
                    json=log_entry
                )
        except Exception as e:
            print(f"⚠️ Could not log execution: {e}")

if __name__ == "__main__":
    main()