-- SHARD-10 (wave: clay, leon, taylor, pinellas): taylor C/D 0%->50% via canonical
-- parity matcher wiring gap
-- dispatch_id: b2e2da00-b59f-40c6-bdce-3ba8109e3ca0
-- Session: architect-20260703T080000
--
-- ROOT CAUSE (VERIFIED live 2026-07-03 via REST queries): taylor's tax_deed_outcomes
-- and foreclosure_outcomes tables already carried one genuine independent record
-- each -- data_source='taylor_clerk_inperson_official', source_url pointing at
-- https://taylorclerk.com/departments/tax-deeds/ and
-- https://taylorclerk.com/departments/clerk-of-courts/ (real Taylor County Clerk of
-- Court pages), enriched 2026-06-27 -- but public.refresh_parity_tier1_outcomes()
-- (the existing canonical matcher used successfully for hendry/pasco, see
-- 20260702_shard5_hendry_canonical_parity_refresh.sql) had never been invoked for
-- taylor, so all 4 taylor auctions sat at parity_status='mca_only'.
--
-- DRY-RUN SAFETY CHECK (done before invoking, since the function resets existing
-- parity_status for in-scope rows before rematching -- a blind invocation could
-- regress a county with better existing matches from another process): replicated
-- the function's exact parcel-then-case join logic read-only in Python for taylor,
-- leon, and pinellas.
--   taylor:   current_any=0 -> would_any=2   IMPROVEMENT -> ran it
--   leon:     current_any=112(in-scope) -> would_any=64  REGRESSION -> did NOT run
--             (leon's existing tier1_supplementary:shard3:2026-06-25 matches trace
--             to a broader/different process than the outcomes tables alone and
--             are NOT touched by this session)
--   pinellas: current_any=300(in-scope) -> would_any=50  REGRESSION -> did NOT run
--
-- Applied live via PostgREST RPC 2026-07-03:
--   SELECT * FROM public.refresh_parity_tier1_outcomes('taylor');
--   -> [{"pass":"parcel","matched_clean":2,"matched_divergent":0},
--       {"pass":"case","matched_clean":0,"matched_divergent":0}]
--
-- VERIFIED live before/after via pencil_dod_evaluate_county('taylor'):
--   BEFORE: C matched_clean=0 (0.0%) FAIL | D matched_any=0 (0.0%) FAIL
--   AFTER:  C matched_clean=2 (50.0%) FAIL | D matched_any=2 (50.0%) FAIL
-- Genuine gain, still below the 95% threshold. Structural ceiling: taylor's other 2
-- of 4 auctions (TAYLOR-FC-2026-002, TAYLOR-TD-2026-002) are auction_status='upcoming'
-- (not yet closed) so cannot be matched against an outcome yet -- not a further bug.
-- A/B/E/F/G/H/I/J confirmed unchanged before/after.
--
-- No SQL to reproduce here beyond the RPC call above (no DDL/DML authored this
-- session for taylor) -- this migration file documents the call per repo convention
-- (see 20260702_shard5_hendry_canonical_parity_refresh.sql).

SELECT 1; -- no-op placeholder: documents a function CALL, already applied live above.
