-- GOLD STANDARD SHARD-8: gilchrist, desoto, polk, hernando, glades
-- dispatch_id: c4a59f8c-8f49-4527-b52c-d31530c37b25
-- Session: architect-20260710T000000

-- ENVIRONMENT CONSTRAINT (matches every prior shard session's note): direct psql/pg8000
-- connection (pooler and db.<ref>.supabase.co, both ports, PGPASSWORD=SUPABASE_DB_PASSWORD)
-- fails with "password authentication failed for user postgres" in this sandbox, confirmed
-- via psql AND via `supabase db dump --linked` (same underlying connection). All reads/writes
-- this session went through the Supabase Management API
-- (POST /v1/projects/mocerqjnksmhcjzxrewo/database/query, Bearer SUPABASE_ACCESS_TOKEN) for
-- raw SQL, and PostgREST (SUPABASE_SERVICE_ROLE_KEY) for RPC calls to pencil_dod_evaluate_county.
--
-- NO METRIC REGRESSIONS. NO NEW MATCHED-CLEAN ROWS FABRICATED. Every letter below is either
-- already PASSING, confirmed at a genuine data ceiling, or blocked on a real, named external
-- constraint -- not worked around.
--
-- =====================================================================================
-- 1) GILCHRIST -- 10/10, no action needed
-- =====================================================================================
-- H flipped PASS between brief authoring and this session start (88.5h stale -> 1.2h fresh),
-- via the existing routine scrape cadence, not this session's action. Re-verified live:
-- A-J all PASS. auctions_total=5.
--
-- =====================================================================================
-- 2) DESOTO -- 8/10, C/D confirmed at genuine ceiling (re-verification, no new work)
-- =====================================================================================
-- matched_clean=2/6 (33.3%). All 6 desoto rows read live: the 2 matched rows carry real
-- parity_source (tier1_foreclosure_outcome / tier1_tax_deed_outcome) already spot-checked
-- against tax_deed_outcomes/foreclosure_outcomes by a prior session
-- (20260703_shard10_desoto_jackson_orange_volusia_cd_ghost_success_purge.sql, "desoto:
-- verified clean, no fabrication found"). The remaining 4 rows have auction_date 2026-07-19
-- or 2026-08-03 -- both in the future relative to today (2026-07-10) -- auction_status=
-- upcoming is correct, no outcome can exist yet. Identical finding to the 2026-07-02 session.
-- No safe action available; this is a real ceiling, not a bug.
--
-- =====================================================================================
-- 3) POLK -- 7/10, C/D near-miss (94.97%, needs 586/616) -- investigated, no safe fix found
-- =====================================================================================
-- Found 21 non-matched rows within the 616-row denominator: 10 upcoming foreclosures
-- (2026-07-07/07-08, no outcome possible) and 11 tax-deed rows from 2025-11-20/2025-12-18
-- carrying tier1_sold_amount values (label 'tier1:shard9_run3059_ajax_harvest:tax_deed:...')
-- but zero corresponding rows in tax_deed_outcomes (confirmed: SELECT count(*) FROM
-- tax_deed_outcomes WHERE lower(county)='polk' -> 0).
--
-- Backfilling tax_deed_outcomes from tier1_sold_amount would reproduce, field-for-field, the
-- EXACT fabrication pattern already caught and reverted for this same county:
-- 20260702_shard6_polk_bf_fabrication_revert.sql documents a prior session copying
-- tier1_sold_amount into sold_amount and manufacturing 218 circular outcome rows
-- (winning_bid==sold_amount, 100% circular, no real source) to fake B/F. Declined to touch
-- this data for that reason -- HARD GUARDRAIL #2 (fail-loud, no ghost success).
--
-- Instead ran the existing vetted canonical matcher live (unchanged, shared function):
--   SELECT * FROM public.refresh_parity_tier1_outcomes('polk');
--   -> [{"pass":"case","matched_clean":10,"matched_divergent":0},
--       {"pass":"parcel","matched_clean":0,"matched_divergent":0}]
-- Re-verified via pencil_dod_evaluate_county: matched_clean unchanged at 585 before and after
-- (the matcher's case-number pass reproduced 10 pre-existing matches it already owned via its
-- own reset-then-rematch logic -- net zero new rows). Confirms the residual 21-row gap is not
-- closeable via the safe/vetted matching path; tax_deed_outcomes genuinely has zero rows for
-- polk and needs a real Polk County Clerk/RealTaxDeed harvest, not a relabeling.
--
-- NOT DONE (flagged for a dedicated real-scraper session): harvest actual Polk County tax deed
-- sale results for the 2025-11-20 and 2025-12-18 dates from an independent source (clerk
-- records or RealTaxDeed authenticated result pages) and insert into tax_deed_outcomes with a
-- verifiable data_source, then re-run refresh_parity_tier1_outcomes('polk').
--
-- =====================================================================================
-- 4) HERNANDO -- 4/10, two real structural findings (neither fixed -- both out of single-
--    county-session scope, documented per Honesty Protocol rather than worked around)
-- =====================================================================================
-- (a) B/F root cause: ALL 23 hernando rows carry auction_status='upcoming', including 9 rows
--     whose auction_date (2026-06-30, 2026-07-07) is already 3-10 days in the past relative to
--     today (2026-07-10). This is a stale status-transition bug of the same class already
--     flagged (not yet fixed) for st_lucie in the 2026-07-03 diagnosis
--     (20260703_shard3_lafayette_jackson_stlucie_lee_glades_diagnosis.sql). Since B/F both key
--     off closed_sold = count(sold_amount IS NOT NULL), and sold_amount is null everywhere while
--     status never transitions off 'upcoming', both metrics are structurally null (0/0), not
--     merely low. Not fixed here -- touches shared status-transition logic outside this
--     session's county-scoped remit.
--
-- (b) E gap: 5 of 23 rows have parcel_id=NULL (2026-018TD, 2026-023TD, 2026-011TD, 2024-077TD,
--     2026-024TD). A 2026-07-02 session (20260702_shard7_hernando_e_i_taxsmart_countygis_fix.sql)
--     documents resolving parcel_id for 3 of these exact case numbers (2026-011TD, 2026-018TD,
--     2026-030TD) via the Hernando Clerk TaxSmart jqGrid endpoint -- but live data shows 2 of
--     those 3 (2026-011TD, 2026-018TD) back to NULL now (only 2026-030TD held). All 5 null rows
--     share data_source='calendar_sweep_mca_v3', a recurring ingestion tag -- consistent with a
--     periodic upsert cron re-writing these fields from a blank source value and silently
--     discarding the prior enrichment (a durability/idempotency gap, not investigated further
--     this session -- flagged for whoever owns calendar_sweep_mca_v3).
--     Re-attempted the TaxSmart endpoint live this session (both the documented GET
--     GridSearchData?SearchType=Case... form and a POST with jqGrid-standard params
--     _search/rows/page/sidx/sord): confirmed HTTP 500 / generic ASP.NET error page on every
--     variant tried, same failure class the 2026-07-02 session hit ("could not be reproduced
--     with a plain HTTP session ... needs follow-up with real browser automation"). No
--     Playwright/browser-use tool was available in this sandbox session. Not fixed.
--
-- =====================================================================================
-- 5) GLADES -- 1/10, root cause UPDATED with a more specific, actionable finding
-- =====================================================================================
-- fl_counties confirms glades (co_no=22) has total_parcels=0, appraiser_url=NULL,
-- gis_endpoint=NULL -- never onboarded. multi_county_auctions has zero glades rows.
--
-- The 2026-07-03 diagnosis (20260703_shard3_lafayette_jackson_stlucie_lee_glades_diagnosis.sql)
-- attributed this to "ERROR: All Firecrawl attempts returned nothing" on the discovery
-- workflow and called it a systemic issue affecting glades + nassau. This session re-checked
-- LIVE via `gh run list/view` against .github/workflows/discover-auction-dates.yml: the
-- workflow has failed on every one of the last 10+ consecutive dispatches (spanning
-- 2026-07-08 through 2026-07-10), and the actual failure log (run 29061293067) shows the
-- precise root cause is `firecrawl 402` (HTTP 402 Payment Required) -- reproduced identically
-- for BOTH brevard and seminole in the same run, i.e. this is a Firecrawl account
-- billing/credits exhaustion affecting the entire fleet's A-lane discovery, not a glades- or
-- county-specific block. FIRECRAWL_API_KEY is not present in this sandbox session's
-- environment, so a live credit-balance check could not be performed directly, but the 402
-- status code is unambiguous.
--
-- NOT FIXED (requires Ariel/billing action, not a code change): top up or renew the Firecrawl
-- account. This is the single highest-leverage unblock available right now -- it affects
-- glades' A-lane plus every other county whose discovery job depends on this workflow, not
-- just this shard's target.
--
-- =====================================================================================
-- VERIFIED via pencil_dod_evaluate_county() -- BEFORE (per session brief) vs AFTER (this
-- session, live RPC), no regressions, no fabricated gains:
--   gilchrist: 9/10 -> 10/10 (H flipped by routine cron between brief and session start,
--              not this session's action)
--   desoto:    8/10 -> 8/10 (unchanged, ceiling confirmed)
--   polk:      7/10 -> 7/10 (unchanged, matcher rerun was a confirmed no-op)
--   hernando:  4/10 -> 4/10 (unchanged, two real blockers documented)
--   glades:    1/10 -> 1/10 (unchanged, root cause re-diagnosed and sharpened)
--
-- Logged to gold_standard_ultraloop_audit (dispatch_id c4a59f8c-8f49-4527-b52c-d31530c37b25,
-- ultraloop_mode='fallback' -- native Workflow-tool fan-out was not used; the investigative
-- chain above was run directly against the Management API / PostgREST in this single-turn
-- session): 6 rows, all survived=true (each is a verified negative/diagnostic finding or a
-- confirmed-no-regression observation, not a PASS claim requiring adversarial refutation of a
-- positive result).
--
-- PARALLEL-FLEET NOTE: other shards were confirmed mid-flight during this session (calhoun,
-- wakulla, taylor, franklin, marion/pinellas/orange/hamilton commits landed on main during
-- this session's window) -- per the session brief's PARALLEL-FLEET RULES, gold_standard_loop()
-- and gold_standard_certify() were NOT run; per-county pencil_dod_evaluate_county() was used
-- for all verification instead.
--
-- NEXT STEPS (not done this session, flagged honestly):
--   - glades: escalate Firecrawl billing/credits to Ariel directly -- unblocks glades A plus
--     every other county queued behind the same discovery workflow.
--   - polk: needs a real Polk County Clerk/RealTaxDeed harvest for 11 tax-deed cases dated
--     2025-11-20/2025-12-18 to genuinely populate tax_deed_outcomes (not a relabeling).
--   - hernando: (1) find and fix the status-transition job/cron leaving past-due auctions
--     stuck at auction_status='upcoming' -- this alone would very likely flip B and F once
--     real sold_amount data can attach; (2) get a browser-automation tool (Playwright/
--     browser-use) into a future session to query TaxSmart for the 5 remaining unlinked
--     parcels, and separately investigate why calendar_sweep_mca_v3 appears to revert prior
--     manual parcel_id enrichments.
--   - desoto: no action needed until 2026-07-19/2026-08-03 auctions actually occur.

SELECT 1; -- no-op placeholder: all live reads/writes this session went through the Supabase
          -- Management API SQL endpoint and PostgREST (no direct psql/pooler access from this
          -- environment, consistent with every session note above). This file documents the
          -- diagnosis for repo history. The one live write this session performed --
          -- SELECT * FROM public.refresh_parity_tier1_outcomes('polk') -- is a pre-existing,
          -- unchanged, idempotent function call, confirmed net-zero effect (documented above).
