-- SHARD-5: CORRECTIVE — bradford ghost-success revert + columbia orphaned-fabrication cleanup
-- dispatch_id: 8cc7b73b-55e7-4ddc-8b0e-d7c93c9ba7d9
-- Session: architect-20260703T000000
--
-- This corrects a false claim made earlier in this same session, commit 4405f169
-- ("bradford C/D 0%->100% (10/10)"). ULTRALOOP adversarial verification (this session's
-- own diagnose+verify workflow) surfaced that all 3 bradford multi_county_auctions rows and
-- their 3 matching outcome rows are 100% fabricated bootstrap placeholder data
-- (data_source literally self-labeled "realforeclose:shard5-bootstrap-v1:placeholder" /
-- "shard5_bootstrap_run338_bradford") — already explicitly flagged in commit 685e97a3
-- (2026-07-02) as "pure bootstrap placeholder rows, no live RealAuction tenant... documented,
-- not touched." Running public.refresh_parity_tier1_outcomes('bradford') without first
-- checking provenance mechanically linked one fabricated dataset to the other and produced a
-- clean 100.0% match on entirely synthetic data. Logged as honesty_violations id
-- fb91acc5-e3e1-4066-811a-736ffafa80df (CRITICAL, resolved=true) and
-- gold_standard_ultraloop_audit id 2897 (survived=false).
--
-- ACTION TAKEN (live, this session):
--   DELETE FROM multi_county_auctions WHERE county = 'bradford';   -- 3 rows
--   DELETE FROM foreclosure_outcomes  WHERE county = 'bradford';   -- 2 rows
--   DELETE FROM tax_deed_outcomes     WHERE county = 'bradford';   -- 1 row
--
-- VERIFIED via pencil_dod_evaluate_county('bradford') after deletion:
--   auctions_total=0, every letter FAIL/null except G (zoning-only, independent of auction
--   data) — bradford's honest floor now matches columbia's, correctly reflecting that this
--   county has no real bootstrapped auction data yet and needs an actual scraper build.
--
-- SEPARATE, UNRELATED to bradford: this session's ULTRALOOP verify pass on the columbia
-- bootstrap-feasibility diagnosis found the 2026-07-02 fabrication cleanup (2 prior
-- honesty_violations rows, CRITICAL) was incomplete — it deleted the 9 fabricated rows from
-- multi_county_auctions but left 6 orphaned SYN-COL-* rows in foreclosure_outcomes and 3 in
-- tax_deed_outcomes untouched. Deleted live this session:
--   DELETE FROM foreclosure_outcomes WHERE county = 'columbia';  -- 6 rows (SYN-COL-FC-*, SYN-COL-TD-*)
--   DELETE FROM tax_deed_outcomes    WHERE county = 'columbia';  -- 3 rows (SYN-COL-TD-*)
-- Verified empty via REST GET post-delete. columbia's honest state (auctions_total=0) is
-- unchanged by this — it was already 0 in multi_county_auctions — but the orphaned outcome
-- rows would have contaminated any future real bootstrap's parity matching.
--
-- palm_beach and monroe portions of commit 4405f169 are UNAFFECTED by this correction —
-- independently re-verified this session via exhaustive adversarial checks (ULTRALOOP audit
-- ids 2899, 2900, both survived=true): both are real data-volume ceilings, not fabrication,
-- not matching-key bugs.
--
-- OPEN BUG FLAGGED, NOT FIXED (no schema/raw-SQL access available this session — REST-only,
-- no exec_sql RPC, direct psql auth fails in this environment): the ULTRALOOP verify pass on
-- indian_river found public.refresh_parity_tier1_outcomes' parcel-matching pass can cross-link
-- a row to a DIFFERENT case_number's outcome via shared parcel_id — evidenced on indian_river
-- case 2022 CA 000723 (wrongly linked to outcome row for case 2022 CA 000132) and case
-- 2024 CA 000752 (wrongly linked to outcome row 2025-0032TD). indian_river's parity_status was
-- NOT further modified this session pending a fix to the matching key (require case_number
-- confirmation, not parcel_id alone, before accepting a match as clean/divergent). Recommend
-- auditing every other county whose refresh leaned on the parcel-pass (case-pass returned 0/0)
-- before trusting its C/D numbers. Logged as gold_standard_ultraloop_audit id 2898
-- (survived=false).

SELECT 1; -- no-op placeholder: documents live DELETE statements already applied via REST,
          -- and 2 honesty_violations / 4 gold_standard_ultraloop_audit rows already logged.
