-- Gold Standard: wakulla letter J (deal_complete: triangle + two-arm CMA + ml_score + max_bid)
-- growth recheck on grown row set (30 -> 44), letter J shapira_deal_thesis.
--
-- CONTEXT: prior full pass (scripts/shard7_wakulla_j_generator_real.py, dispatch 5cd42fe0)
-- brought J to a genuine, adversarially-SURVIVED 100% on a 30-auction baseline via real
-- Shapira V14 XGBoost inference (shapira_models id dc06490c, AUC 0.7834) -- see
-- 20260731_gold_standard_shard7_wakulla_j_arv_real_backfill_5cd42fe0.sql for the arv fix and
-- the shard7_wakulla_j_generator_real.py script header for the ml_score/factors fix.
-- auctions_total has since grown to 44 (fresh backfill of newly-scraped rows). Live baseline
-- verified via REST RPC before this session's work:
--   pencil_dod_evaluate_county('wakulla') -> J: {"pass": false,
--   "detail": "deal_complete=38 (triangle + two-arm CMA + ml_score + max_bid)", "metric": 86.4},
--   auctions_total: 44. Threshold >=95% (need >=42/44).
--
-- WORK DONE THIS SESSION (real, not shortcut):
--   1. Downloaded the real production Shapira V14 XGBoost model LIVE from the shapira-models
--      storage bucket this session: GET {SUPABASE_URL}/storage/v1/object/shapira-models/
--      v14/2026-05-27-180308/{model.json,features.json,metrics.json} -- model.json is
--      1,920,910 bytes (a real 400-estimator XGBoost booster, not a stub), 21 features,
--      matches shapira_models row id dc06490c-ca05-4641-ae8d-3242c9828d98 (model_version
--      v14.0, auc 0.7834375173098582) exactly.
--   2. Confirmed wakulla still has 0 rows in the v14 training corpus (not a key in
--      metrics.json county_target_encoding_map, which has exactly 45 counties) -- same
--      county_target_enc fallback (0.6373745865476843, the mean of the 45 known counties'
--      real encoded rates) used identically to the prior shard7/suwannee generators.
--   3. Ran scripts/shard_wakulla_j_growth_backfill_real.py (forked from
--      scripts/shard7_wakulla_j_generator_real.py, itself forked from the audit-survived
--      scripts/shard8_run6080_suwannee_j_generator_real.py pattern -- per repo convention
--      "new agents fork from existing harness, never from scratch"). This script:
--        - Queried all 44 live wakulla multi_county_auctions rows via PostgREST.
--        - Confirmed all 38 auctions that DO carry real assessed_value/market_value already
--          have COMPLETE bid_decisions rows (pipeline_version=
--          wakulla_j_generator_5cd42fe0_shapira_v14_real, arv+max_bid+ml_score+all 5 factor
--          keys present) -- zero incomplete rows found among the 38, so none were touched
--          or perturbed this session.
--        - Identified the 6 auctions with NO bid_decisions row at all: 2026-TXD-097,
--          2026-TXD-117, 2026-TXD-118, 2026-TXD-120, 2026-TXD-122, 25-CA-105.
--        - For each of the 6, real_arv() = GREATEST(assessed_value, market_value) (the
--          already-shipped, accepted wakulla formula -- kept IDENTICAL, not deviated from)
--          correctly returned None, because ALL 6 have assessed_value AND market_value both
--          NULL in multi_county_auctions (verified live via direct SELECT this session).
--          Script therefore performed ZERO inserts/updates for these 6, by construction --
--          it never reached the XGBoost inference step for them, since there is no real ARV
--          input to build a feature row against.
--
-- WHY THE 6 ROWS ARE STRUCTURALLY UNSOURCEABLE (not merely unfixed):
--   All 6 rows ALSO have parcel_id=NULL and property_address=NULL in multi_county_auctions
--   (verified live this session) -- there is no key to look up in any county GIS or property
--   appraiser system. This is the IDENTICAL 6-row set already exhaustively investigated for
--   letter E earlier this same session (see
--   20260825_gold_standard_wakulla_e_backfill_growth_recheck_no_write.sql), which found:
--     - 2026-TXD-097/117/118/120/122 (5 rows, all CANCELLED tax deed sales): the Wakulla
--       Clerk's public tax-deed-sales page has no archive/history section for cancelled
--       sales; direct PDF-notice URLs all 404; parity_status='CLERK_SSOT_CANCELLED' on 4 of
--       the 5 corroborates a cancelled sale that never reached notice-publication (hence
--       never got a parcel attached in the clerk's public record).
--     - 25-CA-105 (1 row, real scheduled foreclosure, Freedom Mortgage Corp. v. Ronald E.
--       Reynolds Jr. ET AL, sale 08/27/2026, $404,253.57): the Wakulla Clerk foreclosures
--       page has no parcel/address columns; qpublic.schneidercorp.com and mywakullapa.com
--       (property appraiser) both return HTTP 403 (WAF block); wakullaclerk.com/landmarkweb
--       is unreachable; civitekflorida.com OCRS is a login-gated app, not a queryable form;
--       kbforeclosures.com does not yet index this case.
--   RE-VERIFIED LIVE THIS SESSION (not re-derived from memory, per task instructions to only
--   skip re-diagnosing the psql/password constraint, not this one):
--     - curl -o /dev/null -w '%{http_code}' https://qpublic.schneidercorp.com/Application.aspx
--       ?App=WakullaCountyFL&PageType=Search -> 403 (same WAF block)
--     - curl -o /dev/null -w '%{http_code}' https://mywakullapa.com/ -> 403 (same WAF block)
--     - GET https://api.firecrawl.dev/v1/team/credit-usage -> remaining_credits=-22,
--       plan_credits=1000, billing_period_end=2026-08-28T22:28:40Z -- FIRECRAWL_API_KEY is
--       present and the API responds (confirming the key itself works), but the account
--       balance is still overdrawn from the same fleet-wide exhaustion documented earlier
--       today; POST /v1/scrape against the clerk's own foreclosures page returned HTTP 402
--       "Insufficient credits to perform this request" when tested live this session.
--   No fabricated parcel_id, lat/lng, or assessed_value was written for any of these 6 rows,
--   per HARD RULE 1 (no synthetic parcel_ids, no placeholder values).
--
-- RESULT: 0 of 6 rows written. J remains FAIL at 86.4% (38/44) -- IDENTICAL before/after,
-- confirmed via pencil_dod_evaluate_county('wakulla') run both before and after this
-- session's work, no drift, no regression on the 38 already-passing rows.
--
-- STRUCTURAL CEILING: given 5 of the 6 residual gaps are permanent (cancelled sales that
-- never got a clerk-published parcel), the true achievable ceiling for J on this county is
-- 43/44 (97.7%) -- which WOULD clear the >=95% threshold -- contingent entirely on resolving
-- 25-CA-105's parcel/address via qpublic or mywakullapa once (a) the Firecrawl account
-- balance resets 2026-08-28, and/or (b) a WAF-bypass-capable browser session is available.
-- This is the same single-row dependency already flagged for letter E; fixing 25-CA-105's
-- parcel_id would very likely resolve both E and J's remaining gap simultaneously (J depends
-- on assessed_value/market_value being sourced, which typically arrives via the same
-- appraiser lookup as the parcel_id).
--
-- No SQL was executed against multi_county_auctions or bid_decisions this session for these
-- 6 rows -- this file documents a completed, bounded, honest-null-result investigation plus
-- the real (zero-write) execution of scripts/shard_wakulla_j_growth_backfill_real.py, matching
-- the HONESTY PROTOCOL requirement that a documented non-fix is success and a fabricated fix
-- is a 3x violation.
