-- SHARD-4 (miami_dade): C/D systemic ghost-success revert (333 of 338 unbacked)
-- dispatch_id: 428137af-dc82-4531-900a-2e54917fcbf0
-- Session: architect-20260704T080000
--
-- The live scoreboard reported miami_dade C/D=94.9%% (matched_clean=338/356),
-- with 20260703_shard11_miami_dade_cd_tier1_restamp.sql explicitly concluding
-- "legitimate real court-case matches, NOT ghost-success" based on a spot-check
-- of 10 rows plus a PropertyOnion-exclusion aggregate check. Neither check
-- tested for the one thing that actually matters: does a real row exist in
-- tax_deed_outcomes / foreclosure_outcomes for the matched case_number?
--
-- VERIFIED live this session: of the 338 matched_clean/tier1% rows, only 5 join
-- to ANY row in tax_deed_outcomes or foreclosure_outcomes by case_number. The
-- other 333 all share three properties: auction_status='upcoming' (the sale
-- has not happened yet), sold_amount IS NULL, tier1_sold_amount IS NULL. An
-- auction that has not occurred cannot have a verified sale outcome by
-- definition -- these were set matched_clean by
-- scripts/shard2_main_executor.py's run_cd_parity(), which promotes rows to
-- matched_clean based on case_number FORMAT (real court-case pattern, not a
-- PO- prefix) without ever checking for a corresponding outcome row.
-- 20260703_shard11_miami_dade_cd_tier1_restamp.sql then re-stamped
-- parity_source with a tier1_ prefix on these same rows (already
-- parity_status='matched_clean' from the executor), which is what let them
-- start counting toward C/D -- inflating the metric from an honest 1.4%% (the
-- same migration's own documented BEFORE state) back up to a fabricated 94.9%%.
--
-- ACTION TAKEN (live, via Supabase Management API SQL endpoint):
--   UPDATE multi_county_auctions SET parity_status=NULL, parity_source=NULL
--   WHERE county='miami_dade' AND parity_status='matched_clean'
--     AND parity_source LIKE 'tier1%'
--     AND NOT EXISTS (SELECT 1 FROM tax_deed_outcomes WHERE case_number=mca.case_number AND county='miami_dade')
--     AND NOT EXISTS (SELECT 1 FROM foreclosure_outcomes WHERE case_number=mca.case_number AND county='miami_dade');
--   -- 333 rows reverted; the 5 rows with real outcome-table backing (and the
--   -- 1 pre-excluded propertyonion_litmus_shard3 row) were left untouched.
--
-- VERIFIED via pencil_dod_evaluate_county('miami_dade') live 2026-07-04:
--   BEFORE: C=94.9%% (338/356) FAIL, D=94.9%% (338/356) FAIL
--   AFTER:  C=1.4%%  (5/356)   FAIL, D=1.4%%  (5/356)   FAIL
--   E (parcel_linked=338/356, 94.9%%) and I (card_complete=335/356, 94.1%%)
--   unchanged -- confirmed independent of parity_status/parity_source.
--
-- Logged: honesty_violations (2 rows, CRITICAL -- one for the miami_dade
-- metric itself resolved=true, one flagging scripts/shard2_main_executor.py's
-- run_cd_parity() as a systemic risk for OTHER counties in its COUNTIES list
-- [desoto, miami_dade, okaloosa, putnam, holmes], resolved=false, out of
-- SHARD-4 scope to patch) and gold_standard_ultraloop_audit (2 rows, C+D,
-- survived=true, dispatch_id 428137af-dc82-4531-900a-2e54917fcbf0).
--
-- CROSS-CHECK (this session): hillsborough's 709 matched_clean/tier1 rows were
-- independently verified to have 100%% real outcome-table backing (0 upcoming,
-- canonical parity_source values tier1_tax_deed_outcome/tier1_foreclosure_outcome)
-- -- hillsborough's 77.4%% C/D is a genuine ceiling, NOT fabricated.
--
-- NEXT STEPS (flagged, not done this session -- shared infra outside SHARD-4's
-- assigned counties): patch scripts/shard2_main_executor.py run_cd_parity() to
-- require a real tax_deed_outcomes/foreclosure_outcomes join before setting
-- matched_clean, then re-audit okaloosa/putnam/holmes (also in its COUNTIES
-- list) for the same fabrication pattern.

SELECT 1; -- no-op placeholder: documents live UPDATE already applied via
          -- api.supabase.com/v1/projects/mocerqjnksmhcjzxrewo/database/query
          -- with SUPABASE_ACCESS_TOKEN (verified before/after above).
