-- Gold Standard shard-2 (dispatch ffe1aa89-758e-42a2-8ac2-73ceeee9d290): SECOND
-- independent adversarial pass on nassau (10/10) + st_johns (auditing all 10
-- letters). This session made ZERO writes to multi_county_auctions,
-- parcel_zones, zoning_districts, zone_standards, or bid_decisions -- all
-- data-level fixes for this dispatch were already applied by sibling
-- migrations earlier in this same dispatch (see
-- 20260724p_gold_standard_shard2_stjohns_cdei_stub_enrichment_ffe1aa89.sql,
-- 20260724_gold_standard_shard2_stjohns_cd_parity_source_backfill.sql,
-- 20260724_gold_standard_shard2_stjohns_i_parcel_zones_backfill.sql). This
-- migration documents an INDEPENDENT re-verification pass + 25
-- gold_standard_ultraloop_audit rows already inserted live via REST (20
-- initial + 2 self-corrections + 3 late-breaking corrections after a
-- concurrent sibling fix landed mid-session, see bottom of file), plus
-- a genuine new finding (correcting an imprecise claim from an earlier
-- ultraloop row this session) and one bounded, unsuccessful attempt at
-- closing a residual (later closed anyway by a concurrent process).
--
-- ============================================================================
-- BEFORE (fresh pencil_dod_evaluate_county, this session's own calls)
-- ============================================================================
-- nassau:   A-J all PASS, auctions_total=34 (10/10, unchanged from brief)
-- st_johns: A/B/C/D/E/F/G/H PASS, I/J FAIL at 92.0% (46/50), auctions_total=50
--   (this is the brief's OWN "treat live as ground truth" instruction playing
--   out: C/D/E already moved from FAIL->PASS via the sibling migration before
--   this pass started; I/J remain genuinely blocked)
--
-- ============================================================================
-- NASSAU: independent re-verification, all 10 letters, all survived=true
-- ============================================================================
-- A: fc=29 td=5, fresh GROUP BY. B: verified=11 closed_sold=11, spot-checked
-- 3 real non-PropertyOnion data_source values (realauction_live:
-- nassau_pw_harvest_20260720), sold_amount spans $100 (genuine FL plaintiff
-- credit-bid floor) to $266,100. C/D: matched_clean=matched_any=34/34, all
-- parity_source LIKE 'tier1%'. E: parcel_linked=34/34, sampled parcel_ids are
-- real STRAP format. F: tier1_sold=11/11, sold amounts match foreclosure_
-- outcomes exactly. G (most scrutinized, freshness-urgent per brief): fresh
-- v_zoning_gold_standard_kpi_v3 confirms far_applicable_parcels=0 and
-- pk1000_applicable_parcels=0 of 34 -- genuine 0/0 N/A, not silently-excluded
-- data; density=100% of the 28 applicable parcels (6 PUD parcels correctly
-- excluded, lacking a density standard). H: last_seen 10.7h ago, inside 48h
-- SLA. I: card_complete=34/34 structurally confirmed; HONESTY NOTE (does not
-- flip pass, corroborates an earlier same-day audit row from a different
-- session at 01:51 UTC): 21/34 rows share identical lat/long
-- (30.5985,-81.7785) despite genuinely distinct real addresses across 5
-- towns -- a geocoding-fallback pattern, not fabricated/duplicate rows
-- (independently cross-checked this session via judgment_amount, which IS
-- genuinely distinct/non-round per row: $170719.76, $159700.24, $177313.71,
-- $549385.62, $264187.63, etc -- proving underlying cases are real). J:
-- deal_complete=34/34 structurally confirmed; HONESTY NOTE: 30/34 rows
-- (88%) cluster into 3 arv/max_bid/ml_score combos, root-caused THIS session
-- to multi_county_auctions.assessed_value itself being a flat placeholder
-- ($150,000 for 18 rows / $320,000 for 12 rows, assessed_value_source=NULL
-- for all 30) feeding arv_source='shapira_formula_loop65_j_gen' -- a
-- mechanical formula producing identical output from identical fake input.
-- pipeline.counties.parcel_data_source/parcel_data_url/fips_code are all
-- NULL for nassau, confirming no real per-parcel valuation source is wired
-- up yet. Real-property-with-placeholder-assessed-value gap (analytical
-- fidelity), not invented cases/addresses/parcels. Fixing requires FL GIO
-- cadastral ingestion or Nassau PA scraping -- new-scraper scope, correctly
-- out of budget this bounded pass. Disclosed, not hidden; DoD pass stands
-- because the letter tests field-presence, not per-field uniqueness.
--
-- ============================================================================
-- ST_JOHNS: independent re-verification
-- ============================================================================
-- A: fc=47 td=3. B: verified=1 closed_sold=1, foreclosure_outcomes.
-- data_source='shard6_clerk_independent:V1' (real, not PropertyOnion). C/D/E:
-- reconfirmed the drift the brief flagged -- 100.0% (50/50), the 4 formerly-
-- blocking stub rows (CA22-1233, CA25-1470, CC25-0048, CC25-2919) now carry
-- real distinct property_address/lat-long/assessed_value/parcel_id/source_url
-- per the sibling enrichment migration, parity_status=matched_clean,
-- parity_source=tier1_realforeclose_aids_st_johns. F: tier1_sold=1/1,
-- $336,187.60 exact match. G: density=100 far=100 pk1000=blank, pk1000
-- genuinely 0/45 applicable (no commercial/industrial zone codes present).
-- H: last_seen 1.6h ago, inside SLA.
--
-- I/J: STILL FAIL at 92.0% (46/50) -- reconfirmed the SAME 4 case numbers
-- (CA22-1233, CA25-1470, CC25-0048, CC25-2919) are the sole blockers, now for
-- a DIFFERENT reason than C/D/E (which is closed): these 4 parcels have no
-- row in parcel_zones (I) and no row in bid_decisions (J) at all.
--
-- CORRECTION (this migration's one genuine self-correction): an earlier
-- ultraloop_audit row logged by THIS session claimed gis.sjcfl.us "does not
-- resolve," implying the St Johns County zoning GIS source is fundamentally
-- unreachable. That was imprecise -- a SIBLING migration in this SAME
-- dispatch (20260724_gold_standard_shard2_stjohns_i_parcel_zones_backfill.sql)
-- proves gis.sjcfl.us/portal_sjcgis/rest/services is a real, live, queryable
-- ArcGIS endpoint (used successfully to zone 2 OTHER st_johns parcels:
-- 0733220860, 0263350890, confirmed live in parcel_zones with source=
-- 'gis.sjcfl.us_arcgis:shard2_run6080'). This session's own WebFetch call
-- failed with DNS ENOTFOUND (confirmed via direct nslookup: no answer from
-- resolver 127.0.0.53) -- that is THIS session's sandboxed-network
-- limitation, not proof the source is unreachable in general. Attempted to
-- route around it via the firecrawl-scrape skill (Firecrawl REST API
-- directly, since the firecrawl CLI binary is not installed in this
-- environment) -- got HTTP 402 "Insufficient credits". Per CLAUDE.md's
-- spend_over_10 STOP-and-confirm rule, did not attempt a credit top-up
-- without approval. Logged both the correction and the bounded, unsuccessful
-- attempt as separate audit rows (ids 8873, 8874) rather than silently
-- leaving the imprecise claim uncorrected.
--
-- RESULT: I and J are genuinely still blocked for these exact 4 cases,
-- precisely re-scoped: the fix (query gis.sjcfl.us zoning MapServer for
-- parcels 0288211410/2881031960/1821410080/0615191110, insert into
-- parcel_zones matching the proven pattern; separately (re-)run the external
-- bid_decisions generator for these 4 now-enriched cases) is real,
-- available, and NOT a new-scraper build -- but requires either a Firecrawl
-- credit top-up or execution from a network path with working DNS to
-- gis.sjcfl.us, neither of which this bounded pass could do without
-- exceeding scope/budget or spending without approval.
--
-- ============================================================================
-- ULTRALOOP AUDIT ROWS (23 total, already inserted live via Supabase REST
-- during this session -- documentation-only record below, idempotent)
-- ============================================================================
-- nassau:   A,B,C,D,E,F,G,H,I,J all survived=true (10 rows)
-- st_johns: A,B,C,D,E,F,G,H survived=true; I,J survived=false with precise
--           evidence (8 + 2 = 10 rows)
-- st_johns: I correction row + I final-attempt row, both survived=false
--           (2 rows, ids 8873 and 8874) -- self-correcting an earlier
--           imprecise claim from this same session, not from a prior session
--
-- Verify: SELECT county_slug, letter, survived, created_at
--   FROM gold_standard_ultraloop_audit
--   WHERE dispatch_id = 'ffe1aa89-758e-42a2-8ac2-73ceeee9d290'
--     AND created_at > '2026-07-24 03:00:00+00'
--   ORDER BY county_slug, letter, created_at;
--
-- ============================================================================
-- LATE-BREAKING DEVELOPMENT (observed live, AFTER the 22 rows above were
-- inserted, still within this same session -- st_johns moved from 8/10 to
-- 9/10 while this migration file was being written)
-- ============================================================================
-- A THIRD concurrent process in this SAME dispatch (source tag
-- 'gis.sjcfl.us_arcgis:shard2_run6080_ffe1aa89') inserted real parcel_zones
-- rows for exactly the 4 remaining I-blocking parcels (0288211410->PUD,
-- 2881031960->PUD, 1821410080->PUD, 0615191110->RG-1) while this session was
-- re-verifying. Directly observed the RG-1 zoning_districts row (id=12514)
-- transition from missing to present between two of this session's own
-- queries seconds apart -- caught the concurrent write in-flight rather than
-- silently trusting a single snapshot. This flipped I from FAIL(46/50) to
-- genuine PASS(50/50), reconfirmed stable across 2 consecutive
-- pencil_dod_evaluate_county calls ~3s apart.
--
-- The same write transiently broke G for a few seconds (RG-1's district_id
-- was momentarily NULL mid-insert, so v_zoning_gold_standard_kpi_v3's
-- COALESCE(applicability, true) default wrongly marked far/pk1000/density as
-- "applicable but no standard" for that one parcel, dropping pk1000 to
-- 0.0%). Re-queried after the concurrent write completed: G is genuinely
-- PASS again at density=97.1% far=100.0% pk1000=blank(0 applicable, legit
-- N/A) -- the 97.1% (down from the earlier 100.0%) reflects one real,
-- small, still-open gap (RG-1/district 12514 has no max_density_du_acre
-- value yet), which still clears the >=95% pass threshold.
--
-- J re-checked, and a FOURTH concurrent write landed seconds later (same
-- dispatch, arv_source='shapira_formula_stjohns_j_backfill_broker1_county_
-- median', model='shapira_v14', created_at=2026-07-24 03:34:54): all 4
-- remaining case numbers gained real bid_decisions rows. Verified this is
-- NOT a repeat of nassau's templated-placeholder pattern before accepting
-- it: all 4 new rows have DISTINCT arv values ($138,980.00 / $365,713.00 /
-- $260,374.00 / $629,231.00) that exactly equal each case's own real,
-- previously-enriched assessed_value (not a shared flat number), and each
-- factor object carries an explicit honesty_marker distinguishing
-- 'VERIFIED_INPUT_INFERRED_ARV' from 'INFERRED' components -- a materially
-- more transparent generator than the one behind nassau's J gap. J flipped
-- FAIL(46/50)->PASS(50/50), reconfirmed via fresh pencil_dod_evaluate_county
-- and stable on a second call.
--
-- FINAL ST_JOHNS SCORE THIS SESSION: 10 of 10, up from the brief's starting
-- 5/10 -- attributable to: this dispatch's own sibling migrations (C/D/E via
-- stub enrichment, 2 of the I parcels via an earlier run6080 GIS lookup)
-- PLUS two further concurrent in-session fixes (the remaining 4 I parcels,
-- then the 4 J bid_decisions rows) that this session directly observed,
-- adversarially scrutinized for fabrication risk, and reconfirmed rather
-- than passively inheriting. 4 additional gold_standard_ultraloop_audit rows
-- (ids 8907 I=true, 8908 G=true, 8909 J=false [superseded], 8924 J=true
-- [final]) were inserted live via REST documenting the full sequence of
-- this session's own live observations, including the one row (8909) that
-- was correct at the moment it was written and superseded moments later by
-- a further concurrent fix -- left in place rather than deleted, since it
-- was an honest snapshot of true state at that instant.
--
-- Verify: SELECT public.pencil_dod_evaluate_county('st_johns');
--   expect 10/10 PASS (all letters, reconfirmed stable across 2 calls)

DO $$
BEGIN
  RAISE NOTICE 'Documentation-only migration. No multi_county_auctions/parcel_zones/bid_decisions rows were written by this session (concurrent sibling sessions in the same dispatch made the parcel_zones and bid_decisions writes referenced above). 26 total ultraloop_audit rows were inserted live via REST during this session (20 initial + 2 self-corrections + 4 late-breaking corrections tracking a fast-moving concurrent fix sequence); verify with the query in the comment above.';
END $$;

-- Verification queries used this session (all read-only, run against live data):
-- SELECT public.pencil_dod_evaluate_county('nassau');   -- expect 10/10 PASS (unchanged)
-- SELECT public.pencil_dod_evaluate_county('st_johns'); -- expect 10/10 PASS (all letters)
