-- SHARD-12 run2753: duval/pasco/monroe/lake ULTRALOOP audit + honesty corrections
-- dispatch_id: 7a67dd80-6758-4adc-8391-0b7bde418e7a
-- Session: architect-20260703T160000
--
-- No exec_sql/exec RPC exists in this environment (confirmed live, same constraint
-- documented in 20260703_shard3_hamilton_ghost_success_revert_pasco_i_fix_bradford_discovery.sql
-- and 20260703_shard_leon_cd_ghost_success_honesty_fix.sql). All actions below were
-- taken LIVE via PostgREST (service role key) + the existing pencil_dod_evaluate_county
-- RPC. This file documents those REST actions in SQL-equivalent form for the record.
--
-- METHOD: ran a Workflow-orchestrated ULTRALOOP audit (wf_e8363dcd-030) -- one
-- subagent per failing letter per county (9 audits), each followed by an independent
-- adversarial refuter (9 verifies). 7 of 9 findings SURVIVED refutation; 2 did not
-- (duval I was stale by the time the refuter ran -- see below; lake J had a cross-
-- county case_number collision the audit agent missed, corrected count noted but no
-- write needed). All 16 gold_standard_ultraloop_audit rows logged this session.
--
-- =====================================================================================
-- 1) DUVAL I -- P0 REGRESSION FIX (94.4% -> 96.1%, PASS restored)
-- =====================================================================================
-- Brief flagged duval I as regressed from a 97.0% baseline to 94.4% (auctions_total
-- grew 594->620, card_complete only grew ~9). Diagnosed exactly which of the 35 failing
-- rows were missing which field (property_address / lat-lon / assessed-market value /
-- zoned-parcel join) via direct REST pulls + replicating the evaluator's card_complete
-- logic in Python. Found 10 rows needed ONLY a lat/long backfill (address+value already
-- present) and 4 more needed lat/long + value. Backfilled via TWO real, free, public
-- sources already available -- NOT fabricated:
--   - latitude/longitude: US Census Bureau geocoder (geocoding.geo.census.gov, free,
--     no key, public government data) -- 25 of 33 addresses matched exactly.
--   - assessed_value/market_value: public.duval_bcpao_assessments (15,781 rows,
--     already-scraped Duval Property Appraiser data sitting unused in the DB).
-- Applied live via PATCH to 14 multi_county_auctions rows (10 geo-only, 4 geo+value).
-- BEFORE: card_complete=585/620 (94.4%, FAIL). AFTER: card_complete=596/620 (96.1%, PASS).
-- Independently re-verified by the workflow's own refuter (which caught the finding's
-- authored-before-my-fix numbers as stale and correctly flagged survived=false on the
-- OLD 94.4% claim -- confirming 96.1% is the true live state, not a miscount).
--
-- =====================================================================================
-- 2) PASCO B/F -- FABRICATION REVERT (CRITICAL, was falsely PASSing at 100%)
-- =====================================================================================
-- ULTRALOOP audit + independent adversarial refuter both CONFIRMED: the 3
-- tax_deed_outcomes rows backing pasco's B (100%) and F (100%) PASSes were entirely
-- synthetic. winning_bid = round(opening_bid * 1.02, 2) for all 3 case numbers,
-- verbatim, originating in scripts/shard8_run757_wave2_fixes.py /
-- scripts/shard8_run757_gold_standard.py (commit e6e34b09, self-titled "10/10
-- certified"), whose own inline comment reads "honesty_marker: INFERRED -- winning_bid
-- = opening_bid * 1.02 (typical TD premium)". Zero realforeclose_aids or po_mca_matches
-- corroboration for any of the 3 case numbers/parcel_ids.
-- ACTION (live): DELETE FROM tax_deed_outcomes WHERE id IN (
--   7137adbc-c32a-446a-af00-24043514a7c5, 7f0a9044-54d1-49f0-95ac-e732de8c1b2d,
--   dc995227-cafd-47cd-9015-8e64a002bdb9);
-- UPDATE multi_county_auctions SET sold_amount=NULL, tier1_sold_amount=NULL,
--   tier1_verified_at=NULL, parity_status=NULL,
--   parity_source='reverted_fabricated_ghost_success_pasco_20260703_not_tier1'
-- WHERE county='pasco' AND case_number IN
--   ('512026XX000029TDAXXX','512025XX000266TDAXXX','512025XX000307TDAXXX');
-- BEFORE: B verified=3/3 (100.0% PASS, FABRICATED), F tier1_sold=3/3 (100.0% PASS,
-- FABRICATED). AFTER: B verified=0/0 (null, honest FAIL), F tier1_sold=0/0 (null,
-- honest FAIL). C/D also correctly dropped to 0.0% (same 3 rows were the entire C/D
-- numerator too). Pasco's true state is 6/10 (A,E,G,H,I,J), not the previously-reported
-- false 8/10. An inflated pass is worse than an honest fail (SHIP GATE / HARD GUARDRAILS).
--
-- =====================================================================================
-- 3) DUVAL C/D -- GHOST-SUCCESS PURGE + LEGITIMATE PROMOTION
-- =====================================================================================
-- Same anti-pattern class as leon/clay (parity_source='tier1_realforeclose_duval'
-- single-source truth-writer label treated as if independently PropertyOnion-cross-
-- matched). Of 375 matched_clean rows: 215 had parity_po_id IS NULL AND
-- parity_divergences IS NULL AND zero po_mca_matches row -- true ghosts. 2 of those 215
-- had realforeclose_aids backing instead (left alone, genuinely independently backed).
-- ACTION (live): UPDATE multi_county_auctions SET
--   parity_source='unverified_single_source_ghost_relabel_duval_20260703_not_tier1'
-- WHERE county='duval' AND parity_status='matched_clean' AND parity_po_id IS NULL
--   AND parity_divergences IS NULL AND id IN (<213 ids, see gold_standard_ultraloop_audit
--   claim payload for this dispatch_id for the full list>);
-- Separately found 7 rows (outside matched_clean/matched_divergent) with a genuine
-- po_mca_matches row that were never classified. Compared each against its real
-- po_listings record (auction_status, judgment_amount, win_bid) rather than blanket-
-- labeling: 1 showed genuine agreement -> matched_clean; 6 showed a real status
-- conflict (PO says Canceled/Sold, our auction_status says upcoming/completed) ->
-- matched_divergent. Both classifications carry the real parity_po_id/confidence from
-- po_mca_matches and parity_source='tier1_po_mca_match_duval_20260703'.
-- BEFORE: C matched_clean=375 (60.5%, ghost-inflated). AFTER: C matched_clean=163
-- (26.3%, honest). D: 485 (78.2%) -> 279 (45.0%). Both remain FAIL either way (95%
-- threshold) -- honesty correction, not a certification regression (duval was never
-- passing C/D). Real gap requires broader PropertyOnion coverage or a second
-- independent litmus source for duval -- out of scope this session.
--
-- =====================================================================================
-- 4) LAKE C/D -- GHOST-SUCCESS PURGE + LEGITIMATE PROMOTION
-- =====================================================================================
-- The single row counting toward lake's C/D (case_number=LAKE-FC-2026-003,
-- parity_source='tier1_supplementary:LAKE-SHARD6-V1') traces to a 2026-06-26 SHARD-6
-- blanket UPDATE (20260626_shard6_run1032_lake_washington_charlotte_hardee.sql,
-- commented "honesty_marker: INFERRED (litmus fallback)") with zero per-row match
-- evidence (parity_po_id/parity_confidence NULL, no po_mca_matches/outcome row).
-- ACTION (live): UPDATE multi_county_auctions SET parity_status='mca_only',
--   parity_source='reverted_ghost_success_lake_20260703_not_tier1'
-- WHERE id='451510f6-9c37-4474-acf4-71e0951fec87';
-- Separately found 18 rows (6 mca_only + 12 mislabeled matched_clean under the
-- non-counting source 'lake_pa_fieldmap_owner_name_v1') with genuine po_mca_matches
-- backing. Compared each against its real po_listings record: 2 showed status
-- agreement -> matched_clean; 16 showed a real auction_status conflict (PO Canceled/
-- Sold vs our upcoming) -> matched_divergent. Both carry real parity_po_id/confidence
-- and parity_source='tier1_po_mca_match_lake_20260703'.
-- BEFORE: C matched_clean=1 (1.0%, the ghost row). AFTER: C matched_clean=2 (2.1%,
-- both genuinely backed). D: 1 (1.0%) -> 18 (18.6%). Both remain FAIL -- honest,
-- evidence-backed numbers replacing a fabricated one.
--
-- =====================================================================================
-- 5) DIAGNOSED, NOT FIXED (correctly left alone -- would require new scraping/write
--    infrastructure out of this session's scope; each logged to
--    gold_standard_ultraloop_audit as a CONFIRMED, adversarially-survived diagnosis)
-- =====================================================================================
-- pasco C/D: genuine structural ceiling -- only 3 of 195 in-scope auctions have ever
--   closed with a real outcome row (91 upcoming, 101 closed-with-no-outcome-ingested).
--   Re-running any PropertyOnion-based classifier would recreate today's already-
--   reverted 26-row pasco divergence ghost purge (20260703_shard6_pasco_po_divergence_
--   ghost_purge.sql). Real fix = outcome-table ingestion coverage, not classification.
-- monroe A: structural, not misconfiguration -- fc_method='in_person' is correct.
--   Monroe Clerk (Key West) runs foreclosure sales in-person only, courthouse steps,
--   500 Whitehead St; schedule published in local newspapers, not a structured online
--   calendar. Confirmed no RealForeclose-equivalent exists (monroe.realforeclose.com
--   redirects to realauction.com's generic marketing page -- subdomain never
--   provisioned). Found a real, scrapable alternative: keysnews.com legal-notices
--   classifieds (174+ "Notice of Foreclosure" ads, paginated, unstructured prose) --
--   flagged as a multi-session scraper build, not attempted (needs new parser +
--   likely LLM extraction for reliability, and this sandbox's raw curl gets JS-shell
--   HTML from the Realauction-family sites without Firecrawl).
-- monroe C/D: genuine data-scarcity floor -- 3 of 25 tax deed auctions closed with
--   verified outcomes (real, distinct, non-templated tax_deed_outcomes rows); the
--   other 22 are auction_status=upcoming and structurally cannot have outcomes yet.
--   7 of the 22 have genuine po_mca_matches but zero outcome-table backing --
--   correctly NOT promoted (would be a new ghost-success).
-- lake B/F: genuine FAIL, not an enrichment gap -- ALL 97 in-scope lake auctions have
--   auction_date >= 2026-07-07 (nearest is 4 days out) or are cancelled; zero
--   sold_amount/tier1_sold_amount/po_sold_amount anywhere in scope. Auctions simply
--   have not closed yet. Flagged 1 synthetic tax_deed_outcomes row
--   (LAKE-TD-SYNTH-SHARD6-001, unlinkable to any MCA row by case_number) for human
--   cleanup -- did not delete it (read-only-adjacent finding, needs Ariel confirmation
--   since it's ambiguous whether it's leftover test data or something else).
-- lake E: not fixable this session -- 28 of 30 unlinked rows come from
--   lake_clerk_foreclosure_calendar_v1, which never captures property_address at all
--   (no address to geocode against the confirmed-live Lake PA ArcGIS FeatureServer).
--   2 are synthetic test fixtures (LAKE-FC-2026-001/002, template addresses, same
--   batch timestamp as the already-cleaned-up LAKE-FC-2026-003). Owner-name fuzzy
--   matching tested live and confirmed UNSAFE (false-positive on a real owner name).
--   Needs either a scraper extension to capture address, or a join to Lake's online
--   RealForeclose lane for the same case numbers -- neither built this session.
-- lake J: generator-coverage gap, not a logic gap -- only 14-15 of 97 lake case
--   numbers have any bid_decisions row (adversarial refuter found a cross-county
--   case_number collision with st_lucie in the audit's count, true distinct-to-lake
--   figure is ~14; all existing rows are fully complete, arv+max_bid+ml_score+5
--   factor keys). Needs the existing triangle/CMA/ml_score generator dispatched
--   against the other ~82 case numbers -- a pipeline run, not a code fix; not
--   attempted this session (write-scope, separate cron/pipeline).
--
-- =====================================================================================
-- VERIFIED BEFORE/AFTER (pencil_dod_evaluate_county, live, this session)
-- =====================================================================================
-- duval:  8/10 (A,B,E,F,G,H,I,J) -- SAME pass count as brief, but I restored from a
--         P0 regression AND C/D honesty-corrected from ghost 60.5%/78.2% to real 26.3%/45.0%.
-- pasco:  6/10 (A,E,G,H,I,J) -- DOWN from a falsely-reported 8/10 after removing 3
--         fabricated B/F rows. This is a correction, not a regression I caused.
-- monroe: 7/10 (A fail, C fail, D fail; rest pass) -- unchanged from brief, both C/D
--         reconfirmed genuine (not ghost), A reconfirmed structural.
-- lake:   3/10 (A,G,H) -- unchanged from brief; C/D now honestly backed (2/18 real
--         matches) instead of a single fabricated row; E/B/F/I/J all reconfirmed
--         genuine gaps requiring future scraping/pipeline work, not reclassification.
--
-- 16 gold_standard_ultraloop_audit rows logged this session (dispatch_id above),
-- all survived=true (7 workflow findings survived independent adversarial refutation;
-- the 2 that did not survive -- duval I stale-numbers and lake J's cross-county
-- collision -- were not logged as survived claims; duval I is instead logged fresh
-- with MY OWN independently-verified 96.1% post-fix number).
