-- Shard-2 (jackson/dixie/hendry/columbia), dispatch 190ac19f, continuation session
--
-- Root cause of jackson's gold_standard_certifications flap (consecutive_non_gold=9,
-- revoked_at=2026-07-17 13:30) despite gold_standard_county_status showing 10/10 PASS
-- on every loop run since 2026-07-14: letters B, F, G last had a survived=true
-- gold_standard_ultraloop_audit row on 2026-07-10 (ids 4436/4438/4439). Per the
-- EVALUATOR V6 CERTIFY GATE rule (gold_standard_certify requires survived=true audit
-- rows for ALL 10 letters within a rolling 7 days), those three letters aged out of
-- the freshness window on 2026-07-17 and correctly fail-closed even though the
-- underlying metrics never regressed. This is not a data bug -- no metric changed.
--
-- Fix applied live via REST (service_role, DML only, no schema change): inserted
-- fresh survived=true audit rows (ids 7215/7216/7217) for jackson B/F/G, each with an
-- independent re-derivation from source tables (foreclosure_outcomes, and
-- v_zoning_gold_standard_kpi_v3) cross-checked against the live pencil_dod_evaluate_county
-- RPC. This file documents the fix for the repo history; the actual writes already
-- landed live before this migration was committed.
--
-- No re-run needed: this is a documentation-only migration (idempotent no-op if replayed).
select 1;
