-- SHARD-6 (lafayette, jackson, indian_river, santa_rosa, columbia): ghost-success
-- purges + one verified real-data fix
-- dispatch_id: 8a9f3366-985c-406e-b338-01aa5ea9a76a
-- Session: architect-20260704T160000
--
-- =============================================================================
-- PART 1: lafayette -- ghost-success found + purged (CRITICAL)
-- =============================================================================
-- ROOT CAUSE (CONFIRMED live): lafayette's reported 9/10 score rested entirely
-- on 2 fabricated placeholder rows -- case_number LAFAYETTE-FC-SEED-2026 /
-- LAFAYETTE-TD-SEED-2026, parcel_id SYN-LAF-FC-001 / SYN-LAF-TD-001,
-- legal_description literally "Lafayette County foreclosure/tax deed pipeline
-- configured -- pending live scrape", provenance=pipeline_seed_lafayette_shard1_ffd85d01,
-- inserted 2026-06-25 by a prior shard1 session. A subsequent shard12 session
-- (2026-06-27) then cascade-labeled the fake rows data_source='tier1_authoritative:
-- shard12_run1113_lafayette' without ever sourcing a real courthouse/clerk record.
-- lafayette.county_auction_config has fc_method='in_person', daily_scrape_enabled=
-- false -- no automated scraper exists for this county at all, so these 2 rows were
-- the ONLY data lafayette ever had.
--
-- Same class of incident already purged for baker (2707c0af), orange (f749c834),
-- escambia (8d38f1b0).
--
-- ACTION (already applied live via REST DELETE, this file documents it):
--   DELETE FROM bid_decisions WHERE case_number IN ('LAFAYETTE-FC-SEED-2026','LAFAYETTE-TD-SEED-2026'); -- 2 rows
--   DELETE FROM foreclosure_outcomes WHERE case_number = 'LAFAYETTE-FC-SEED-2026'; -- 1 row
--   DELETE FROM tax_deed_outcomes WHERE case_number = 'LAFAYETTE-TD-SEED-2026'; -- 1 row
--   DELETE FROM multi_county_auctions WHERE case_number IN ('LAFAYETTE-FC-SEED-2026','LAFAYETTE-TD-SEED-2026'); -- 2 rows
--
-- VERIFIED live via pencil_dod_evaluate_county('lafayette'):
--   BEFORE: A/B/C/D/E/F/I/J all PASS (100%%), G PASS, H FAIL (61.4h) -- reported 9/10
--   AFTER:  auctions_total=0, only G PASS (structural) -- honest 1/10
--
-- 8 gold_standard_ultraloop_audit rows logged (survived=false, one per reverted letter).
-- No real fix attempted this session -- lafayette needs a genuine in-person-foreclosure
-- courthouse-calendar source (same class as the Brevard clerk-calendar exception) plus
-- a real tax-deed lane; out of scope for a single session, not fabricated.

-- =============================================================================
-- PART 2: santa_rosa -- ghost-success found + purged, completing a revert that
-- was left half-finished yesterday
-- =============================================================================
-- ROOT CAUSE (CONFIRMED live): 5 orphaned rows -- SANTA-ROSA-FC-2026-001/002/003,
-- SANTA-ROSA-TD-2026-001/002 -- parcel_id SAN-001/002/003, property_address literally
-- "SANTA ROSA COUNTY FL AUCTION <case_number>", parity_scope='shard9_run757_bf_seed',
-- created in one batch 2026-06-26T08:20:05. These share the exact shard9_run757 batch
-- tag as the fabrication already identified and reverted in commit 203b7fe0
-- (2026-07-03), which deleted the foreclosure_outcomes/tax_deed_outcomes half
-- (data_source='tier1_authoritative:shard9_run757_santa_rosa') but left the
-- multi_county_auctions + bid_decisions half in place. None of the 5 rows had
-- parity_status or parity_po_id ever set -- confirming they were never real
-- auctions, and distinct from santa_rosa's legitimate independent source
-- (public.realforeclose_aids, 82 real rows, correctly preserved per commit
-- a11ab113 the same day -- NOT touched here).
--
-- ACTION (already applied live via REST DELETE, this file documents it):
--   DELETE FROM bid_decisions WHERE case_number IN (
--     'SANTA-ROSA-FC-2026-001','SANTA-ROSA-FC-2026-002','SANTA-ROSA-FC-2026-003',
--     'SANTA-ROSA-TD-2026-001','SANTA-ROSA-TD-2026-002'); -- 5 rows
--   DELETE FROM multi_county_auctions WHERE case_number IN (
--     'SANTA-ROSA-FC-2026-001','SANTA-ROSA-FC-2026-002','SANTA-ROSA-FC-2026-003',
--     'SANTA-ROSA-TD-2026-001','SANTA-ROSA-TD-2026-002'); -- 5 rows
--   (foreclosure_outcomes/tax_deed_outcomes already empty for santa_rosa -- confirmed,
--    nothing to delete there)
--
-- VERIFIED live via pencil_dod_evaluate_county('santa_rosa') -- this is a genuine
-- GAIN, not just a revert: removing 5 unmatchable fake rows from the denominator
-- means C/D flip FAIL->PASS honestly (the 58 real matched_clean auctions were
-- always 100%% of the 58 REAL auctions; the 63-row denominator was polluted):
--   BEFORE: A PASS(16) B FAIL(null) C FAIL(92.1%%) D FAIL(92.1%%) E PASS(100%%)
--           F FAIL(null) G PASS H PASS I PASS(100%%) J PASS(100%%) -- 6/10
--   AFTER:  A PASS(14) B FAIL(null) C PASS(100%%) D PASS(100%%) E PASS(100%%)
--           F FAIL(null) G PASS H PASS I PASS(100%%) J PASS(100%%) -- 8/10
--
-- B/F confirmed genuinely blocked, not touched: public.realforeclose_aids (santa_rosa's
-- only vetted independent source) has NO winning-bid/sale-outcome field at all
-- (columns: judgment_amount, plaintiff_max_bid, auction_starts_at -- pre-sale only).
-- It structurally cannot populate foreclosure_outcomes/tax_deed_outcomes. Needs a real
-- post-sale outcome scraper (clerk certificate-of-title or RealForeclose result pages),
-- out of scope for a single session.
--
-- 6 gold_standard_ultraloop_audit rows logged (C/D survived=false on the old FAIL
-- claim; A/E/I/J survived=true noting denominator correction).

-- =============================================================================
-- PART 3: indian_river -- real data backfill (I letter), no ghost-success
-- =============================================================================
-- Two of indian_river's four I-gap rows (card_complete=73 of 77) were missing
-- assessed_value/market_value. Both parcel_ids resolved cleanly against the FL GIO
-- Statewide Cadastral public API (services9.arcgis.com/.../Florida_Statewide_Cadastral,
-- same source already used by scripts/ingest_county.py) with matching street address,
-- confirming genuine parcel match:
--   parcel_id 33391700001013000003.0 (case 2025 CA 000400) -> JV=453427
--   parcel_id 31391900001580000012.0 (case 2025 CA 000932) -> JV=375415
--
-- ACTION (already applied live via REST PATCH, this file documents it):
--   UPDATE multi_county_auctions SET assessed_value = 453427,
--     assessed_value_source = 'fl_gio_cadastral_jv:shard6_run3025'
--     WHERE county='indian_river' AND case_number = '2025 CA 000400';
--   UPDATE multi_county_auctions SET assessed_value = 375415,
--     assessed_value_source = 'fl_gio_cadastral_jv:shard6_run3025'
--     WHERE county='indian_river' AND case_number = '2025 CA 000932';
--
-- VERIFIED live: I metric UNCHANGED at 94.8%% (73/77) after this fix -- the audit
-- agent's assumed evaluator formula (from scripts/shard12_run1113_martin_fix.py:
-- property_address + lat/long + assessed_value + parcel_id all non-null) does NOT
-- match pencil_dod_evaluate_county's actual card-completeness gate, which per the
-- G/I dependency documented in this dispatch brief requires parcel_id to resolve in
-- v_zoning_gold_standard_card WITH a zone_code -- neither of these 2 parcels appear
-- in that view at all. Real, verified data was added (not fabricated) but did not
-- move the metric; the actual I blocker for these 2 rows is zoning/parcel_zones
-- coverage, a separate, larger build. C/D (74.0%%/84.4%%) blocked by the same
-- non-functional matcher issue as jackson below -- not touched.
--
-- =============================================================================
-- PART 4: jackson C/D and columbia A -- confirmed genuinely blocked, no fix applied
-- =============================================================================
-- jackson C/D (matched_clean=2 of 63): scripts/improve_parity_matching.py lists
-- jackson as absent from TARGET_COUNTIES (indian_river/osceola/sarasota only) AND
-- its actual PropertyOnion-matching function find_potential_matches() is an
-- unimplemented stub (`potential_matches = []`, never populated -- see docstring
-- "This is a placeholder for PropertyOnion API integration... Mock potential match
-- finding logic"). Running it would be a no-op at best and risks corrupting
-- case_number via improve_case_number_matching()'s blind normalization overwrite.
-- Not run. 3 jackson rows also carry parity_po_id=0.98-confidence values with zero
-- independent-source backing anywhere in this DB (foreclosure_outcomes/
-- tax_deed_outcomes empty) -- flagged as a latent data-quality risk but NOT
-- currently inflating the score (parity_status is null on those rows) and NOT
-- touched this session.
--
-- columbia A (fc=0 td=0): county_auction_config has columbia fully configured
-- (fc_url/td_url/calendars set, is_active=true, daily_scrape_enabled=true) but
-- .github/workflows/shard7-columbia-scraper.yml has run "successfully" every day
-- for 10+ days while both real scraper jobs are skipped -- gated behind
-- COLUMBIA_REALFORECLOSE_AUTH_CONFIGURED / COLUMBIA_REALTAXDEED_AUTH_CONFIGURED
-- repo variables that were never provisioned (confirmed via `gh variable list`:
-- empty). Even if unblocked, scripts/cairn_multi_county_scraper.py has zero
-- columbia code path. Live curl test: columbia.realforeclose.com returns 403
-- without a browser User-Agent and soft-redirects to the generic RealAuction
-- marketing homepage with one -- a genuine anti-bot block requiring either
-- registered credentials (human account provisioning) or a tested browser-session
-- scraper, neither of which is safe to build/guess in one pass. A prior fabrication
-- bootstrap for this exact county (shard7_columbia_bootstrap.py) was already
-- correctly found and quarantined by shard-8 on 2026-07-02 -- not reintroduced.
