-- SHARD-2 run3025 (dup-dispatch, hardee/gilchrist/taylor/miami_dade/liberty):
-- miami_dade C/D "tier1:shard_miami_dade_datescoped:*" ghost-success revert
-- dispatch_id: 0d3f71c9-addf-430c-adc2-19f399ac39ad
-- Session: architect-20260704T160000 (dup-dispatched again 20260705)
--
-- CONTEXT: this exact dispatch_id/shard already shipped in commit 30974c29
-- on 2026-07-04 (miami_dade E backfill + a self-caught-and-reverted C/D
-- address-litmus attempt). This is a duplicate re-dispatch of the same
-- GitHub issue. Live re-evaluation on re-entry found miami_dade C/D at
-- 88.5%% (matched_clean=315/356) -- NOT the honest 1.4%% ceiling the audit
-- trail as of 2026-07-05T00:20:39Z (dispatch 5099f570) had just reconfirmed.
--
-- ROOT CAUSE: 310 of the 315 matched_clean rows carried
-- parity_source LIKE 'tier1:shard_miami_dade_datescoped:%' -- a process with
-- NO matching script, migration, or prior audit entry anywhere in git or
-- gold_standard_ultraloop_audit. It set parity_status='matched_clean' by
-- date-scoping the auction calendar alone (parity_source suffix is an
-- auction_date, e.g. ':foreclosure:2026-03-02'), with zero regard for
-- whether a sale had actually closed. This is the THIRD recurrence of the
-- exact same ghost-success class for miami_dade C/D:
--   1. dispatch 428137af (2026-07-04 08:13): reverted 333 unbacked rows
--      (script: shard2_main_executor.py run_cd_parity(), since disabled)
--   2. dispatch 0d3f71c9 (2026-07-04 16:20): 88-row address-litmus variant,
--      self-caught and reverted before shipping
--   3. THIS revert (2026-07-05): 310-row date-scoped variant, live and
--      shipped by some other in-flight process before being caught here
--
-- VERIFIED before revert:
--   foreclosure_outcomes: 5 rows for miami_dade (unchanged)
--   tax_deed_outcomes:    0 rows for miami_dade (unchanged)
--   315 matched_clean rows broken down by auction_status: upcoming=294,
--     cancelled=16, sold=5 -- only the 5 'sold' rows have sold_amount
--     populated; the other 310 are pre-sale or closed-without-sale and
--     cannot have a real verified outcome by definition.
--
-- ACTION TAKEN (live, via PostgREST PATCH with service-role key):
--   UPDATE multi_county_auctions
--   SET parity_status = NULL, parity_source = NULL,
--       parity_confidence = NULL, parity_divergences = NULL
--   WHERE county = 'miami_dade'
--     AND parity_source LIKE 'tier1:shard_miami_dade_datescoped:%';
--   -- 310 rows reverted (confirmed by Prefer: return=representation count).
--
-- VERIFIED via pencil_dod_evaluate_county('miami_dade') live 2026-07-05:
--   BEFORE: C=88.5%% (315/356) FAIL, D=88.5%% (315/356) FAIL
--   AFTER:  C=1.4%%  (5/356)   FAIL, D=1.4%%  (5/356)   FAIL
--   -- matches the long-established honest structural ceiling exactly.
--   A/B/E/F/G/H/J unaffected (E=96.1%% PASS per 30974c29's real folio
--   backfill, I=94.1%% FAIL, both unchanged by this revert).
--
-- NOT FOUND: the source of 'shard_miami_dade_datescoped' writes. Grepped
-- full repo (.py/.sql/.yml/.md/.json) for "datescoped" -- zero matches.
-- scripts/shard2_main_executor.py's run_cd_parity() was checked and is
-- already read-only/disabled since 2026-07-04 (unrelated to this pattern).
-- Most likely an uncommitted, in-flight ad-hoc write from a concurrent
-- shard session on miami_dade or an adjacent county, not a recurring
-- scheduled job. FLAGGED for the next session touching miami_dade: if this
-- parity_source prefix reappears, find and neutralize its origin (check
-- gha_dispatch_log for concurrently-running miami_dade jobs at the time of
-- this recurrence) rather than reverting a fourth time.
--
-- Logged: gold_standard_ultraloop_audit (2 rows, C+D, survived=false,
-- ids 3975-3976, dispatch_id 0d3f71c9-addf-430c-adc2-19f399ac39ad).
--
-- Also this session: hardee (10/10), gilchrist (10/10, C/D fixed
-- 2026-07-05T05:24 by a different concurrent dispatch via live RealForeclose
-- AJAX re-harvest, ULTRALOOP-verified survived=true), taylor (3/10,
-- confirmed genuinely blocked -- prior shard6 "10/10" was itself
-- ghost-success on fabricated Perry FL parcel/sale data, already correctly
-- reverted before this session began), and liberty (3/10, confirmed
-- genuinely blocked by real accrual gates -- single case not yet sold,
-- zero tax deeds this period, zoning lookup Cloudflare-blocked with no
-- Firecrawl key) were all re-verified live this session with ZERO DRIFT
-- from the most recent same-day audit entries; no further action taken to
-- avoid duplicating already-thorough same-day research.

SELECT 1; -- no-op placeholder: documents live UPDATE already applied via
          -- PostgREST REST API with SUPABASE_SERVICE_ROLE_KEY (verified
          -- before/after above).
