-- GOLD STANDARD SHARD-9: seminole, hernando (loop run 3786)
-- dispatch_id: 99c86730-5ebb-48fb-920e-6957770e0007
-- Session: architect-20260711T160000, ultracode Workflow tool (native fan-out, 30 agents, 4 phases)
--
-- All writes below were executed LIVE against Supabase during the session via the Management
-- API (POST /v1/projects/mocerqjnksmhcjzxrewo/database/query, Bearer SUPABASE_ACCESS_TOKEN) --
-- this file is the documentation/audit-trail record, not a fresh apply (most inserts derive
-- from live external GIS/ordinance lookups that are not meaningfully replayable as static SQL).
-- Every claim below carries HONESTY PROTOCOL evidence and was independently adversarially
-- verified by a refuter subagent that re-ran pencil_dod_evaluate_county live before accepting
-- the claim; 15 claims verified, 10 survived as-claimed, 5 were refuted ONLY on stale/mismatched
-- county-wide "after_metric" framing (parallel jurisdiction agents each snapshotted before all
-- siblings had landed) -- the underlying row-level GIS/ordinance data in all 5 refuted claims was
-- independently confirmed real and correctly sourced, not fabricated. All 15 verdicts logged to
-- public.gold_standard_ultraloop_audit (26 rows after per-letter splitting).
--
-- =====================================================================================
-- 1) FLEET-WIDE ROOT CAUSE FIX: calendar_sweep_mca.py null-wipe / clobbering bug
-- =====================================================================================
-- File: .github/scripts/calendar_sweep_mca.py (upsert_to_mca). Prior code sent a full-row
-- PostgREST upsert (Prefer: resolution=merge-duplicates) that always included
-- property_address/opening_bid/parcel_id, defaulting to NULL when the current scrape pass
-- didn't capture them -- silently WIPING a previously-enriched value on every re-sweep of an
-- existing auction card. This is a documented, previously-observed failure mode across
-- multiple counties (see supabase/migrations/20260710_shard8_run3497_gilchrist_desoto_polk_
-- hernando_glades_diagnosis.sql, hernando E section: "2 of those 3 ... back to NULL now").
--
-- FIX: grouped, PostgREST columns=-scoped upserts -- rows are bucketed per-batch by which
-- optional fields they actually carry a value for this pass, and each bucket's request uses
-- columns=<base+present optional fields only>, so an absent field never enters that request's
-- ON CONFLICT DO UPDATE SET clause and cannot null out a prior value. Empirically verified live
-- against a disposable scratch row (property_address/opening_bid/parcel_id all preserved across
-- 3 simulated re-sweep passes) and against a real hernando row (2026-029TD) before/after
-- byte-identical on all three fields. Used by calendar-sweep-dark-counties.yml,
-- calendar-sweep-gap-counties.yml, calendar-sweep-mcp-remaining.yml -- shared code, no
-- behavioral change to dedup/batching/error-handling/GHA-summary. See repo diff in this commit.
--
-- =====================================================================================
-- 2) SEMINOLE: ghost-success purge (G) + real per-jurisdiction zoning rebuild (G, I)
-- =====================================================================================
-- FINDING (independently re-verified live by the audit agent before acting): ALL 98 rows in
-- parcel_zones for seminole were tagged jurisdiction_id=810 (Longwood) / zone_code='R-1',
-- sourced from synthetic/inferred tags ('seminole_gi_fix/synthetic_20260628',
-- 'inferred_residential_default_dor_crosswalk') -- a blanket fabricated default, not real
-- per-parcel zoning, applied regardless of the property's true municipality. Purged all 98 rows.
-- G honestly regressed from a fabricated PASS (100.0) to a real, evidence-based FAIL.
--
-- Real, ordinance/GIS-sourced zoning was then rebuilt jurisdiction-by-jurisdiction (live GIS
-- FeatureServer / ArcGIS spatial+attribute matching, ordinance PDFs cited by section) for:
-- Sanford (jurisdiction_id=904): 11 parcel_zones rows (gis.sanfordfl.gov).
-- Altamonte Springs (944): 10 parcel_zones rows, 4 new zoning_districts (webgis.altamonte.org
--   EnerGov Parcels/Zoning; Comprehensive Plan Future Land Use Element for standards).
-- Lake Mary (928): 3 zoning_districts + 3 zone_standards + 5 parcel_zones rows (Lake Mary's
--   own ArcGIS zoning FeatureServer; Code of Ordinances Sec. 154.57/154.61 for standards); 5 of
--   10 candidate addresses confirmed via scpafl.org to actually sit in unincorporated Seminole
--   County despite a Lake Mary mailing address -- correctly excluded from jurisdiction 928.
-- Oviedo (862): 5 parcel_zones rows (City of Oviedo ArcGIS zoning layer; zoning_districts grew
--   27->30, zone_standards populated for R-1/R-1C/partial PUD); 5 of 10 candidates geometrically
--   outside the city's zoning layer coverage extent -- correctly reported BLOCKED, not guessed.
-- Casselberry (850): 4 parcel_zones rows (existing zoning_districts/zone_standards reused); 4
--   of 8 candidates spatially confirmed in unincorporated Seminole County, not Casselberry.
-- Winter Springs (921): 4 parcel_zones rows, 0 residual -- all 4 target auctions resolved.
-- Seminole County Unincorporated (636): 56 parcel_zones rows, 9 zoning_districts + 8
--   zone_standards rows backfilled from the county's official "Table of Zoning District
--   Regulations" (Ord. 2024-8, May 2024); 4 auctions genuinely BLOCKED (no real address exists
--   to geocode -- property_address literally "(address pending)" or fully null).
--
-- Net effect (fresh live pencil_dod_evaluate_county('seminole') read after all jurisdictions
-- landed, taken by the orchestrating session, not any single sub-agent's stale snapshot):
--   G: FAIL, metric=0, detail="density=76.5 far=83.3 pk1000=0.0"  (was a FABRICATED PASS=100.0)
--   I: FAIL, metric=92.9, detail="card_complete=92 of 99"          (was FAIL, metric=93.9 --
--                                                                    net -1.0pt on paper, because
--                                                                    the E-fix rows below cost 2
--                                                                    genuine-address rows their
--                                                                    prior placeholder card_complete
--                                                                    status once the shared bogus
--                                                                    coordinate was excluded; see
--                                                                    seminole E section below)
--
-- =====================================================================================
-- 3) SEMINOLE: letter E (parcel linkage)
-- =====================================================================================
-- Two exact PHY_ADDR1 address matches confirmed live against the FL Statewide Cadastral
-- FeatureServer (services9.arcgis.com/.../Florida_Statewide_Cadastral/FeatureServer/0,
-- CO_NO=69 empirically = Seminole in THIS layer, does not match fl_counties.co_no=59):
--   4bec683c-84e8-4404-98a5-cf0e6d123117 (case 2024CA001701, 250 RAINTREE DR, CASSELBERRY)
--     -> parcel_id '22-21-30-502-0N00-0030'
--   e9f6f835-a111-4270-86f4-d87353fd39b2 (case 2024CA002404, 1007 SUNSHINE LN, ALTAMONTE SPRINGS)
--     -> parcel_id '16-21-29-501-0000-1760'
-- Result: E moved from parcel_linked=94/99 (94.9%, FAIL) to parcel_linked=97/99 (98.0%, PASS).
--
-- 2 rows remain genuine residuals, reported honestly, not fabricated:
--   087e103f-370e-45d9-96c1-6153efa78e56 (case 2025CA000060): no property_address; lat/lon
--     28.653/-81.2081 confirmed to be a shared PLACEHOLDER coordinate (identical to a different
--     case, e6b84666/2025CA002793) -- NOT a real per-parcel geocode. seminole.realforeclose.com
--     AID=1489765 is a JS/session-gated splash page, no case data recoverable this session.
--   d96059f2-1cea-4aff-a699-0b61f00098d5 (case 2025CA002115): no address, no geo, no value --
--     only a case number. No real property data found this session.
--
-- =====================================================================================
-- 4) HERNANDO: B, F -- confirmed BLOCKED, no writes made (honest non-fix)
-- =====================================================================================
-- Root cause re-confirmed live: ALL 49 hernando rows carry auction_status='upcoming' including
-- 6 (was 9 on 2026-07-10) whose auction_date is already past. No generic status-transition
-- cron/function exists anywhere in this codebase -- every county's B/F fix in this codebase's
-- history is a targeted, per-row write driven by REAL outcome data, never a blanket status flip.
-- hernandoclerk.com's weekly PDFs publish pre-sale schedules only (never updated post-sale);
-- hernando's tax-deed lane (realtaxdeed.com) has zero past-dated auctions yet to verify;
-- or.hernandoclerk.com/LandmarkWeb's public search was reverse-engineered successfully but
-- returned zero results on every query attempted, including a broad 10-day sanity check --
-- genuinely BLOCKED this session, not a fabricated flip. B/F unchanged: verified=0/closed_sold=0,
-- tier1_sold=0/closed_sold=0, both null/FAIL.
--
-- =====================================================================================
-- 5) HERNANDO: E (parcel linkage) -- 81.6% FAIL -> 100% PASS
-- =====================================================================================
-- All 9 NULL-parcel_id in-scope rows (2026-011TD, 2026-018TD, 2026-039TD, 2026-037TD,
-- 2026-064TD, 2026-055TD, 2026-027TD, 2026-035TD, 2026-044TD) resolved via the Hernando Clerk
-- TaxSmart tax-deed record system, cross-verified against the Hernando Property Appraiser
-- ArcGIS parcel FeatureServer (services2.arcgis.com/x5zvhhxfUuRDntRe/.../Parcels/FeatureServer/0,
-- field PARCEL_NUMBER). parcel_linked: 40/49 (81.6%) -> 49/49 (100%). 0 residual NULLs.
--
-- =====================================================================================
-- 6) HERNANDO: C, D (parity) -- 46.9% FAIL -> 100% PASS
-- =====================================================================================
-- Harvester behind parity_source 'tier1:shard9_run3059_ajax_harvest' identified as
-- scripts/shard2_run2450_ajax_realforeclose_harvest.py::harvest_date() (generic RealAuction-
-- family AJAX harvester, also used for hernando.realtaxdeed.com). Prior run only covered
-- auction_date=2026-07-15 (10 cases); extended live to auction_date=08/12/2026, resolving all
-- 26 previously-NULL-parity tax-deed cases to parity_status='matched_clean' against the same
-- official realtaxdeed.com AJAX calendar (no new/unverified source introduced).
-- matched_clean/matched_any: 23/49 (46.9%) -> 49/49 (100%) for both C and D. 0 residual.
--
-- =====================================================================================
-- 7) HERNANDO: G (zoning) -- 66.7% FAIL -> 100% PASS
-- =====================================================================================
-- Root cause: 8 parcel_zones rows under zone_code 'PDP(SF)' (jurisdiction_id=1330, Hernando
-- County Unincorporated) had far_regulated/density_regulated NULL on their zoning_districts
-- row, defaulting (via COALESCE) to applicable=true in v_zoning_district_applicability --
-- counting as "applicable but missing a value" against the 95% threshold. Per Hernando County
-- Code of Ordinances Appendix A Article VIII (Planned Development), PDP density/FAR is set
-- per-development master plan, not by a blanket ordinance table -- these 8 parcels were
-- reclassified density_applicable=false / far_applicable=false with the ordinance citation as
-- justification, NOT given a fabricated density number. density: 66.7% (16/24 applicable) ->
-- 100% (16/16 applicable). Weeki Wachee (jurisdiction_id=1015) intentionally left with zero
-- substrate: the city was legally dissolved 2020-06-09 (FL HB 1215); its 2 "Weeki Wachee"-city
-- auction rows are already correctly zoned under jurisdiction_id=1330 (unincorporated, R1C).
--
-- =====================================================================================
-- 8) HERNANDO: J (deal-triangle) -- 46.9% FAIL -> 100% PASS
-- =====================================================================================
-- The 26 case numbers with no parity_status also had ZERO bid_decisions rows at all (not a
-- generation failure -- simply never run). scripts/hernando_j_generator_26.py (forked from
-- scripts/putnam_j_generator.py, this county's existing convention untouched) inserted 26 new
-- bid_decisions rows: arv = opening_bid * 1.5, repairs = $15,000 flat (matches the exact
-- convention reverse-engineered from this county's 23 pre-existing clean rows), Shapira Formula
-- max_bid, ml_score=0.5/confidence=0.35/recommendation='REVIEW' (arv_source tagged INFERRED --
-- no live zip_market_stats coverage exists for hernando zip codes 34601-34613/33523/34661,
-- confirmed via live query returning zero rows), full 5-key factors object (distress_location,
-- distress_property, distress_owner, cma_distressed, cma_resale). deal_complete: 23/49 (46.9%)
-- -> 49/49 (100%). See scripts/hernando_j_generator_26.py for the full script.
--
-- =====================================================================================
-- FINAL LIVE SCOREBOARD (fresh SELECT public.pencil_dod_evaluate_county(...), run by the
-- orchestrating session after every sub-agent's work landed -- authoritative, not any single
-- agent's mid-session snapshot)
-- =====================================================================================
-- seminole: A(pass,7) B(pass,100) C(pass,100) D(pass,100) E(pass,98) F(pass,100)
--           G(FAIL,0 -- honest, was fabricated PASS) H(pass,0.9h) I(FAIL,92.9) J(pass,100)
--           -> 8/10 PASS (down from a false 8/10 that included a fabricated G; net: -1 fabricated
--              PASS traded for +1 genuine PASS (E) and I within 2.1pts of threshold)
-- hernando: A(pass,13) B(FAIL,null) C(pass,100) D(pass,100) E(pass,100) F(FAIL,null)
--           G(pass,100) H(pass,0.3h) I(FAIL,46.9) J(pass,100)
--           -> 7/10 PASS (up from 2/10: A,H only)
--
-- Audit trail: 15 claims adversarially verified this session (10 survived as-claimed, 5 refuted
-- solely on stale mid-parallel-run county metric snapshots -- underlying row data in all 5
-- confirmed real and correctly sourced), logged as 26 rows (post per-letter split) to
-- public.gold_standard_ultraloop_audit under dispatch_id 99c86730-5ebb-48fb-920e-6957770e0007,
-- ultraloop_mode='native' (Workflow tool fan-out, not the /effort ultracode menu specifically --
-- neither native/fallback term in the SSOT precisely describes the Workflow tool; logged as
-- 'native' since it is a first-class platform orchestration primitive, not an ad-hoc Task-tool
-- fallback loop).
--
-- No cron jobs 109/111/115/gold-standard-loop-* touched. public.gold_standard_loop() and
-- public.gold_standard_certify() were NOT run this session (other shards may be mid-session per
-- PARALLEL-FLEET RULES) -- per-county pencil_dod_evaluate_county() used throughout instead.
