-- Gold Standard: county manatee ONLY. Letters attempted: C, D, I.
--
-- BASELINE (VERIFIED live via rest/v1/rpc/pencil_dod_evaluate_county at
-- session start, 2026-08-01): C FAIL matched_clean=83/93 (89.2%), D FAIL
-- matched_any=83/93 (89.2%), I FAIL card_complete=83/93 (89.2%).
--
-- C/D FIX (real, exact-match, non-fabricated): reused the proven
-- scripts/shard2_run2450_ajax_realforeclose_harvest.py harvest_date()
-- mechanism (live RealAuction PREVIEW/UPDATE AJAX endpoint, an independent
-- source -- NOT PropertyOnion, NOT Firecrawl) via
-- scripts/shard9_run3059_citrus_manatee_cd_parity.py, with one correction:
-- manatee's tax_deed sales are NOT hosted on manatee.realtaxdeed.com (that
-- subdomain has been redesigned -- its AJAX endpoint now returns full HTML,
-- not the legacy JSON shape the harvester expects, VERIFIED live for both an
-- old date and a current upcoming date). manatee's tax_deed AND foreclosure
-- sales are BOTH listed on manatee.realforeclose.com (VERIFIED: all 3 old
-- tax_deed case numbers -- 2019TD000204, 2023TD000163, 2023TD000222 -- and
-- all 5 of the 2026-08-03 tax_deed cases were found there under AREA=C).
--
-- 4 exact case_number matches PATCHed parity_status='matched_clean':
--   2019TD000204   tax_deed     auction_date=2019-10-21  parcel 2091900007
--   2023TD000163   tax_deed     auction_date=2023-10-30  parcel 2419218850
--   2023TD000222   tax_deed     auction_date=2023-12-11  parcel 2091900007
--   412025CC003179CCAXMA  foreclosure  auction_date=2026-07-30  parcel 2054122659
-- parity_source='tier1:shard3_dixie_manatee_run_20260801_ajax_harvest:...'
--
-- 6 rows correctly left untouched (auction_date 2026-08-03/2026-08-04,
-- still in the future as of 2026-08-01 -- sale has not happened, cannot be
-- matched/resolved as an outcome yet): 2026TD000018/19/24/25/42,
-- 412025CA002931CAAXMA.
--
-- RESULT: C/D matched_clean/matched_any 83->87 of 93 (89.2%->93.5%). Still
-- FAIL (<95% threshold), residual gap is the 6 genuinely-future rows plus 3
-- rows below with no resolvable parcel_id (see I section).
--
-- I FIX (card_complete = property_address + lat/lng + assessed/market_value
-- + parcel_id present in v_zoning_gold_standard_card with zone_code NOT
-- NULL, per pg_get_functiondef(pencil_dod_evaluate_county)):
--
-- Diagnosed 10 gap rows (93-83). 3 have parcel_id=NULL and cannot be
-- card-completed or zone-linked at all (see BLOCKED below). The other 7 have
-- real parcel_id values; geo/value/zoning were backfilled from Manatee
-- County's own GIS parcel layer (independent source, exact PARCEL_ID match,
-- zero ambiguity):
--   https://www.mymanatee.org/gisits/rest/services/commonoperational/
--   parcellines/FeatureServer/0  (fields PARCEL_ID, PRIMARY_ADDRESS, LAT,
--   LON, ASSESVAL, ZONING -- "Manatee County GIS/Manatee County Property
--   Appraiser" per service copyrightText)
--
-- All 7 PRIMARY_ADDRESS values from the GIS query matched the
-- pre-existing property_address already on the row (independent
-- corroboration the parcel match is correct, not coincidental):
--   412025CC003179CCAXMA  2054122659  7280 83RD DR E, BRADENTON
--   2026TD000018           27100007    43550 SR 62, PARRISH
--   2026TD000019           202512000   SINGLETARY RD, MYAKKA CITY
--   2026TD000042           835112509   50 QUAIL CT, ELLENTON
--   2026TD000024           4297300109  3RD ST W, BRADENTON
--   2026TD000025           4325700005  521 10TH AVE W, BRADENTON
--   412025CA002931CAAXMA   710300609   2908 58TH WAY E, PALMETTO
--
-- UPDATE multi_county_auctions SET latitude/longitude (all 7, guarded by
-- latitude IS NULL) and assessed_value (5 of 7 that were still NULL,
-- guarded by assessed_value IS NULL) -- already executed live via PostgREST
-- this session.
--
-- ZONE LINKAGE: 5 of the 7 parcels were successfully zone-linked (INSERT
-- into parcel_zones, jurisdiction assigned from the same GIS response's
-- PROP_PLC field: 'BR' -> City of Bradenton jurisdiction_id 888, 'NCT'/'SCT'
-- (North/South unincorporated County) -> Unincorporated Manatee County
-- jurisdiction_id 1257) and matched an EXISTING zoning_districts row with a
-- real zone_standards density value, genuinely improving I:
--   2054122659  PD-R      jurisdiction 1257 (excluded from G applicability --
--                          far_regulated=false, density_regulated=false,
--                          pre-existing district row, untouched)
--   27100007    A         jurisdiction 1257 (zone_code corrected from the
--                          GIS's raw "A,CON" compound value to base code "A"
--                          + overlay_codes=['CON'], matching the existing
--                          zoning_districts.code='A' convention; has real
--                          zone_standards density=0.2 du/acre)
--   202512000   A         jurisdiction 1257 (same district as above)
--   835112509   RSMH-6    jurisdiction 1257 (real zone_standards density=6.0
--                          du/acre)
--   710300609   RSF-4.5   jurisdiction 1257 (real zone_standards density=4.5
--                          du/acre)
--
-- REVERTED (2 of 7 -- caused a real G regression, see below):
--   4297300109 (case 2026TD000024) zone_code BR_T4-R, jurisdiction 888
--   4325700005 (case 2026TD000025) zone_code BR_T4-O, jurisdiction 888
-- City of Bradenton's zoning_districts substrate only has ONE form-based-
-- code row (BR_T4-R, id 11258, itself flagged "INFERRED mapping ...
-- ordinance section unconfirmed" by a prior session) and it has ZERO
-- zone_standards row; BR_T4-O has no zoning_districts row at all. Inserting
-- parcel_zones rows against these dragged G (density/far/pk1000 of
-- applicable zones) from PASS 96.3% down to FAIL 94.4% -- BR_T4-R's
-- density_applicable=true with no zone_standards value counted as a miss.
-- G is NOT one of this task's assigned letters (C/D/I only) and was PASSING
-- before this session; researching Bradenton's full form-based-code
-- transect-zone density table (Municode returns HTTP 403 to automated
-- fetch) to legitimately backfill zone_standards was out of scope and would
-- have risked fabricating a density number under time pressure. DELETEd
-- both parcel_zones rows (ids 851388, 851389) to restore G to its exact
-- original passing state (VERIFIED byte-identical: density=96.3 far=100.0
-- pk1000=100.0, matches pre-session baseline exactly). This is a deliberate
-- reversion, not a silent regression -- I is left below its achievable
-- ceiling (88/93 instead of a possible 90/93) rather than break a passing,
-- out-of-scope letter.
--
-- RESULT: I card_complete 83->88 of 93 (89.2%->94.6%). Still FAIL (just
-- under the 95%/89-of-93 threshold). G unchanged PASS (96.3%, zero
-- regression from baseline). No other letter regressed (A/B/E/F/H/J
-- unchanged pass=true; C/D improved but still FAIL, documented above).
--
-- BLOCKED / residual gaps (VERIFIED, NOT written/guessed):
--   1. 3 rows with parcel_id=NULL, cannot be card-completed or zone-linked:
--      412019CA003996CAAXMA (auction_date 2026-03-25, already past --
--        RealAuction calendar's own parcel field literally renders
--        "Property Appraiser" (a hyperlink label) instead of a parcel_id
--        for this case -- source data itself has no clean parcel_id)
--      412024CA000409CAAXMA (auction_date 2026-05-05, already past -- has
--        property_address "12220 SR 62, PARRISH, FL- 34219" but this does
--        NOT exact-match any PRIMARY_ADDRESS in the Manatee GIS parcel
--        layer; state-road-numbered addresses often don't correspond 1:1
--        to the county's named-street address database. Refused to guess a
--        parcel_id from a fuzzy/partial address match -- house-number-only
--        query returned multiple non-matching candidates.)
--      412025CA001790CAAXMA (auction_date 2026-07-01, already past -- source
--        calendar's own parcel field literally says "MULTIPLE PARCELS",
--        i.e. genuinely not a single-parcel case)
--   2. 6 rows with real parcel_id but auction_date still in the future
--      (2026-08-03 x5, 2026-08-04 x1, "today" for this session = 2026-08-01)
--      -- correctly left unmatched for C/D (sale hasn't happened) per task
--      instructions; their geo/value/zone data WAS backfilled for I
--      (property facts, independent of sale outcome) where a clean
--      zoning_districts match existed.
--   3. 2 rows (BR_T4-R / BR_T4-O, City of Bradenton form-based code) have
--      real, verified zone_code values from the county GIS but the
--      jurisdiction's zoning_districts/zone_standards substrate is
--      incomplete for form-based-code zones; fixing requires dedicated
--      ordinance research (Municode blocks automated fetch, HTTP 403) and
--      was deliberately left undone this session to protect G.
--
-- No SQL statements to apply in this file -- all PATCH/INSERT/DELETE
-- operations were already executed live via PostgREST during this session,
-- verified with pencil_dod_evaluate_county before/after snapshots (pasted
-- above). This file is the provenance record only, consistent with this
-- repo's convention for data-only backfill migrations (see
-- 20260731b_shard3_dixie_i_arcgis_geo_value_backfill.sql for the pattern).
