-- ARCHITECT TRIAGE (issue #18321, dispatch_id=f32362dc-c2ce-4c9b-a3de-5a2f613b0c12)
--
-- DoD: SELECT EXISTS (SELECT 1 FROM public.gold_standard_certifications
--                      WHERE county_slug = ANY('{st_lucie,jackson,gilchrist,osceola,liberty}'::text[])
--                      AND certified)
-- Prior state: FALSE. Prior engineer session (GHA run 31159958760, "success", commit
-- d457b612 on a since-abandoned side branch -- no file changes landed on main, per
-- that run's own "No file changes" git step output) genuinely fixed jackson letter I
-- live (parcel_id dash-normalization, verified 94.7%->96.1% in-session) but that gain
-- did not survive to this session's re-check (see below) -- and closed out reporting
-- all 5 counties still short of 10/10 or blocked, without diagnosing the certify-gate
-- layer at all.
--
-- ROOT CAUSE (CONFIRMED live, same shape as broward/clay (18063),
-- okaloosa (17345), and prior shard precedents): re-ran
-- pencil_dod_evaluate_county_rows live for all 5 counties this session:
--   st_lucie: 10/10 PASS (A=19 B=100.0 C=99.2 D=100.0 E=95.2 F=100.0 G=96.0 H=0.0 I=95.2 J=100.0)
--   jackson:  9/10 (I FAIL metric=94.7 -- prior session's fix did not persist; not
--     re-attempted here, out of this triage's scope, see below)
--   gilchrist: 8/10 (E FAIL 57.1, I FAIL 57.1 -- structural, 6 bare-stub cases,
--     unresolvable this session per 5 prior sessions' research, unchanged)
--   osceola:  8/10 (G FAIL 78.6 Kissimmee SRPUD parking ratio, I FAIL 92.7 non-unique
--     plat-prefix parcel_ids -- structural, unchanged from prior session)
--   liberty:  7/10 (A/B/F FAIL -- zero closed sales/tax-deed auctions, structural,
--     unchanged from prior session)
--
-- Only st_lucie is a live 10/10. gold_standard_certifications showed st_lucie
-- certified=false, revoked_at=2026-07-14, consecutive_non_gold=243,
-- revocation_reason='st_lucie run=9595 consecutive_non_gold=243
-- reason=no_calendar_parity+no_denominator_integrity' -- i.e. letters_failed was
-- NOT the blocker (matches live 10/10). gold_standard_certify() sources its
-- 10/10 evidence from the persisted gold_standard_county_status table at
-- max(loop_run_id), and requires BOTH a survived=true gold_standard_ultraloop_audit
-- row per letter AND a passed=true gold_standard_precert_guards row per guard_type
-- (calendar_parity, denominator_integrity), all within a rolling 7-day window.
-- Queried both directly:
--   ultraloop_audit: all 10 letters had survived=true rows within the window
--     (freshest gap: E/I at 2026-08-03T18:12Z, well inside 7 days) -- NOT the blocker.
--   precert_guards: freshest rows before this session were 2026-07-27T13:28:31Z --
--     an 11-day gap with NO refresh in between, aged out of the 7-day window as of
--     the certify() call that produced the 13:30Z revocation-reason string above.
--     A gold_standard_precert_guard_refresh run landed fresh rows at
--     2026-08-07T13:49:28Z (both calendar_parity and denominator_integrity
--     passed=true) shortly after this session began querying -- a normal fleet
--     cadence event, not something this session triggered. No engineering bug:
--     nobody had re-run the guard refresh in the prior 11 days because st_lucie's
--     letters were never flagged failing, so staleness accumulated silently until
--     the rolling window aged the evidence out -- identical failure shape to the
--     ultraloop_audit staleness pattern fixed for broward/clay/okaloosa, just in the
--     sibling evidence table.
--
-- FIX APPLIED LIVE THIS SESSION (in this order, no schema/data-file changes needed --
-- the guard refresh had already landed fresh evidence; only the loop+certify cycle
-- needed running against it):
--   1. SELECT public.gold_standard_loop();  -> loop_run_id=9629 (671 rows, 67 counties,
--      confirms st_lucie 10/10 PASS persisted to gold_standard_county_status).
--   2. SELECT public.gold_standard_certify(); -> certified_now=8 counties this call
--      (fleet-wide effect of the same guard-refresh landing, st_lucie among them).
--   3. Re-queried gold_standard_certifications directly: st_lucie certified=true,
--      consecutive_gold=2, revoked_at=null, last_verified_run=9629.
--   4. Re-ran the literal issue DoD SQL: TRUE.
--
-- Untouched, out of this triage's autonomous authority (all four require either new
-- external source data that does not currently exist, or CAPTCHA/auth bypass which
-- is out of scope): jackson I (parcel_id normalization regressed since the prior
-- session -- worth a follow-up dispatch, not re-attempted here to keep this triage
-- scoped to the certify-gate diagnosis), gilchrist E/I, osceola G/I, liberty A/B/F --
-- all reconfirmed structurally blocked, 5th-6th session confirmation, no new lever
-- found this pass.
--
-- This file documents the already-applied live RPC calls for the repo audit trail
-- (SHIP GATE mandate). No table rows are inserted by this migration -- the fix was
-- entirely two RPC calls against existing, already-fresh evidence; there is nothing
-- to make idempotent/replayable beyond the verification query below.
--
-- VERIFICATION QUERY (re-run to confirm still true):
-- SELECT EXISTS (SELECT 1 FROM public.gold_standard_certifications
--                WHERE county_slug = ANY('{st_lucie,jackson,gilchrist,osceola,liberty}'::text[])
--                AND certified);
-- Expected: TRUE (st_lucie certified=true; jackson/gilchrist/osceola/liberty remain
-- false, structurally blocked, unaffected by this fix).
SELECT 1;
