-- Jefferson County: honest diagnosis session (no data fabrication) + stale
-- precert_guards purge (real DDL below, not a no-op).
-- Session: this diagnosis session, 2026-07-04
--
-- CONTEXT: jefferson had 100% fabricated multi_county_auctions data (2 synthetic rows)
-- purged live on 2026-07-03 (see 20260703_shard8_jefferson_fabrication_purge_and_bay_lee_cd_correction.sql,
-- honesty_violations id add80a91-84e0-46ec-b744-a73396bff9ed). This session verifies the
-- CURRENT state (1 real row, appeared after the purge from a genuine scrape) and confirms
-- there is no honest lever this session to move beyond 2/10 (G, H pass only).
--
-- 1) LIVE ROW VERIFICATION (VERIFIED, no fabrication):
--    multi_county_auctions has exactly 1 jefferson row (id 64081291-f126-44b2-b1c1-1f1f4b47c6d1):
--      case_number=25-CA-164, sale_type=foreclosure, auction_date=2026-06-25,
--      plaintiff="THE BANK OF NEW YORK F/K/A THE BANK OF NEW YORK AS TRUSTEE FOR NATIONSTAR
--      HOME EQUITY LOAN", judgment_amount=86285.09, property_address="340 MARVIN ST
--      MONTICELLO, FL. 32344", data_source='jefferson_clerk_official:jeffersonclerk.com',
--      source_url=clerk S3 PDF, created_at=2026-07-03T16:20:33Z (i.e. created AFTER the
--      fabrication purge, by a real scrape run, not a leftover).
--    Cross-checked against the live PDF (https://jeffersonclerk.s3.amazonaws.com/uploads/
--    2026/06/22073402/Foreclosure-Sales.pdf, fetched fresh this session and text-extracted):
--    every field matches exactly (case #, date, plaintiff, defendant, judgment amount,
--    address). This row is REAL, not fabricated. This is a single-case document -- there is
--    no second case to add.
--
-- 2) TAX DEED PLATFORM RESEARCH (VERIFIED via WebFetch of jeffersonclerk.com live pages
--    this session):
--    - Jefferson County tax deed sales are conducted IN-PERSON ONLY. Clerk's own tax-deed
--      page states bidders "must be physically present," no online platform (realtaxdeed.com,
--      Bid4Assets, etc.) is mentioned or linked anywhere on the Clerk's site.
--    - jefferson.realtaxdeed.com returns HTTP 403 (same RealAuction shared-ELB bot wall
--      previously observed) -- this is NOT evidence of a hidden real online platform Jefferson
--      actually uses; the Clerk's own authoritative page says explicitly there is no online
--      platform. Treating the 403 as "maybe it's real, just blocked" (as the purged
--      fabrication scripts did) would repeat the exact failure mode that caused the CRITICAL
--      honesty violation on 2026-07-03. Not repeating it here.
--    - The Clerk's "Upcoming Tax Deed Sales" section was fetched live and is genuinely EMPTY
--      (no dates/case numbers/parcel numbers) -- td=0 in the DB is an honest reflection of
--      zero currently-scheduled tax deed sales, not a scrape failure.
--    - Foreclosure sales are ALSO in-person (11:00am Thursdays, courthouse North Door),
--      confirming county_auction_config's fc_method='in_person' is CORRECT and should not be
--      changed to 'online' -- there is no real online FC platform for Jefferson either.
--      Jefferson is structurally similar to Brevard's in-person exception but is legitimately
--      NOT documented in the COUNTY EXCEPTIONS list; this session does not add it there since
--      that's a config/docs decision belonging to a different scope, not a data-correction one.
--
-- 3) PARCEL LINKAGE (E) ATTEMPT: jeffersonpa.net (and www.jeffersonpa.net) both returned
--    HTTP 403 to WebFetch this session -- no automated parcel_id lookup available via this
--    tool for the property_address on the 1 real row. Fabricating a parcel_id (as the purged
--    20260626 migration did: '1200650000CA2025001', a constructed non-standard format) is
--    exactly the failure mode already penalized (honesty_violations
--    add80a91-84e0-46ec-b744-a73396bff9ed) -- NOT repeated here. No E gain this session.
--
-- 4) STALE PRECERT_GUARDS PURGE (real DDL, applied live before this file was written):
--    gold_standard_precert_guards had 2 leftover rows for jefferson (ids 196, 197) written
--    2026-06-28 during the fabricated-data era, asserting "auctions_total":2 and
--    "matched_clean_count":2 -- both now factually false (live auctions_total=1, matched_clean=0).
--    These rows would let a future gold_standard_certify() call for jefferson pass guards
--    using stale/fabricated-era numbers even though the underlying data was purged. Deleted:
--      DELETE FROM gold_standard_precert_guards WHERE county_slug = 'jefferson';
--    gold_standard_certifications.jefferson was already certified=false, consecutive_gold=0,
--    revoked_at=2026-07-02 (revoked prior to this session, independently honest) -- untouched,
--    no change needed there.
--
-- 5) VERDICT: jefferson is honestly 2/10 (G, H pass). auctions_total=1 is a real, verified
--    row. No online tax-deed or foreclosure platform exists for this county (confirmed via
--    the Clerk's own site, not just a scraper 403) -- Jefferson is a genuine tiny
--    rural in-person-only county (~14,700 population), not a scraper gap. No honest lever
--    exists this session to move C/D/E/F/I/J off zero from a 1-row real base without either
--    (a) a working parcel-appraiser lookup tool (jeffersonpa.net blocked WebFetch) or
--    (b) a second real auction appearing in a future clerk PDF scrape. Both are out of scope
--    for this session's tooling. No rows added, no values fabricated.
--
-- Verification re-run live before and after the guard purge (no data-metric change expected
-- or observed, since precert_guards do not feed pencil_dod_evaluate_county):
--   SELECT * FROM public.pencil_dod_evaluate_county('jefferson');
--   -- BEFORE: {"A":false(fc=1,td=0),"B":false,"C":false(0.0),"D":false(0.0),"E":false(0.0),
--   --          "F":false,"G":true(100.0),"H":true(15.9h),"I":false(0/1),"J":false,
--   --          "auctions_total":1}
--   -- AFTER:  identical except H=16.0h (clock advance only) -- confirms guard purge was
--   --          data-metric-neutral, as expected.

SELECT 1; -- no-op placeholder in-file: the actual DELETE against
          -- gold_standard_precert_guards was executed live via the Supabase Management API
          -- SQL endpoint before this file was authored (see section 4 above for the exact
          -- statement and returned rows: ids 196, 197).
