-- SHARD-5: miami_dade + st_lucie C/D — run canonical parity matcher (no schema change)
-- dispatch_id: bec9a9b3-ce1c-4a46-b7e0-a861096f5ffb
-- Session: architect-20260702T160000
--
-- Earlier this session (commit d235a19d) miami_dade/st_lucie C/D were correctly dropped to an
-- honest floor after removing mislabeled PropertyOnion-litmus data. That left an open question:
-- had the canonical matcher (public.refresh_parity_tier1_outcomes, already proven for hendry
-- in this same session) ever actually been run for these two counties, or was the floor purely
-- a data-volume ceiling? VERIFIED live 2026-07-02: it had NOT — miami_dade had zero
-- parity_status rows populated at all (1000+ sampled rows all NULL) despite 5 independently
-- verified outcomes existing (B/F already pass at 100%).
--
-- Applied live: SELECT * FROM public.refresh_parity_tier1_outcomes('miami_dade');
--               SELECT * FROM public.refresh_parity_tier1_outcomes('st_lucie');
--
-- VERIFIED via pencil_dod_evaluate_county before/after:
--   miami_dade D: 0.0% (matched_any=0 of 355)  -> 1.4% (matched_any=5, all matched_divergent -
--     amounts not yet confirmed equal). C stays 0.0% (no exact-amount matches found).
--   st_lucie   C: 0.0% (matched_clean=0 of 72) -> 2.8% (matched_clean=2, amounts confirmed
--     equal - the same 2 rows previously counted toward D via an older litmus-derived status
--     are now genuinely clean). D unchanged at 2.8%.
--   A/B/E/F/G/H/I/J unaffected on both counties (confirmed no regression).
--
-- Structural ceiling unchanged: miami_dade has only 5 closed_sold auctions of 355 total (the
-- other 350 are still upcoming with no clerk outcome to match against yet); st_lucie has 2
-- closed_sold of 72. Neither can reach 95% without a much larger volume of auctions actually
-- closing and being independently harvested - this is a genuine data-volume gap, not a further
-- wiring bug. Logged to gold_standard_ultraloop_audit (ids 2895-2896, survived=true).

SELECT 1; -- no-op placeholder: this migration documents 2 function CALLs (not DDL/DML),
          -- already applied live via Supabase REST RPC at the timestamp above.
