-- GOLD STANDARD shard-6: polk
-- Session: architect-20260711T000000
--
-- BASELINE (freshly re-verified via pencil_dod_evaluate_county at session start, after
-- auctions_total regrew 616->679 since the prior 2026-07-10 shard8 polk session):
--   A=PASS B=PASS C=FAIL(89.1%,matched_clean=605) D=FAIL(89.1%,matched_any=605) E=PASS(99.9%)
--   F=PASS G=PASS H=PASS I=FAIL(90.4%,card_complete=614/679) J=FAIL(88.8%,deal_complete=603)
--   -> 7/10
--
-- ROOT CAUSE (VERIFIED live via SQL, matches the dispatch brief exactly):
--   SELECT data_source, tier1_authoritative, parity_status, count(*) FROM multi_county_auctions
--   WHERE lower(county)='polk' AND (data_source<>'propertyonion' OR tier1_authoritative=true)
--   GROUP BY 1,2,3;
--   -> 74 in-scope rows with parity_status IS NULL: 63 data_source='calendar_sweep_mca_v3'
--      (6 foreclosure 07/14-07/15, 57 tax_deed 07/16-08/20) + 11 data_source='realforeclose'
--      (foreclosure, 07/07-07/08). ALL 74 carry auction_status='upcoming' (VERIFIED: 100%).
--   The existing refresh_parity_tier1_outcomes('polk') matcher only promotes rows whose
--   auction_status IN ('redeemed','completed','sold','cancelled','canceled') against
--   tax_deed_outcomes/foreclosure_outcomes -- structurally a no-op for 74 upcoming rows
--   (confirmed by the prior 2026-07-10 session's rerun: matched_clean unchanged at 585).
--   The correct tool is the live AJAX RealAuction/RealTaxDeed CALENDAR harvest (not an
--   outcome match) -- same pattern as scripts/gold_standard_shard11_leon_cd_i_ajax_harvest.py.
--
-- FIX 1 (C/D): scripts/gold_standard_shard6_polk_cd_i_ajax_harvest.py -- forked from the
--   leon template, reuses scripts/shard2_run2450_ajax_realforeclose_harvest.py's harvest_date().
--   Ran live against polk.realforeclose.com / polk.realtaxdeed.com for the 6 distinct
--   (sale_type, auction_date) pairs covering all 74 gap rows:
--     polk foreclosure 2026-07-07: 16 calendar items -> parity=10
--     polk foreclosure 2026-07-08: 2 calendar items  -> parity=1
--     polk foreclosure 2026-07-14: 3 calendar items  -> parity=2
--     polk foreclosure 2026-07-15: 4 calendar items  -> parity=4
--     polk tax_deed    2026-07-16: 1 calendar item   -> parity=1
--     polk tax_deed    2026-08-20: 40 calendar items -> parity=36
--   TOTALS: parity_promoted=54, card_backfilled=6. Wrote parity_status='matched_clean',
--   parity_source='tier1:shard6_run3645_ajax_harvest:<sale_type>:<date>' -- a genuine tier1
--   live-calendar match, not a fabrication. Residual 20 rows on 2026-08-20 tax_deed
--   (case_numbers 00039-00050/00072-00082/00086-2026) are NOT on the live public calendar as
--   of this session (re-verified via raw AJAX pagination trace: both AREA=W and AREA=C exhaust
--   with an end-of-results repeat signal at exactly 40 total items parsed, matching the DB
--   insert count exactly -- not a pagination bug). Left NULL, not fabricated.
--   C: matched_clean 605->659 (97.1%) PASS. D: matched_any 605->659 (97.1%) PASS.
--
-- FIX 2 (J): scripts/shard6_polk_j_gap_backfill.py -- added 'polk' to COUNTY_CONFIG in
--   scripts/shard9_j_generator.py with arv=165478 derived from a LIVE median, VERIFIED this
--   session:
--     SELECT percentile_cont(0.5) WITHIN GROUP (ORDER BY COALESCE(market_value,assessed_value))
--     FROM multi_county_auctions WHERE lower(county)='polk' AND COALESCE(market_value,
--     assessed_value) IS NOT NULL -- n=4526 real-valued rows -> median=165478.
--   Reused build_bid_decision() (Shapira Formula, ARV*70% - repairs - $10K - MIN($25K,15%*ARV))
--   verbatim -- same shape/labels as every prior J-generator run this project, factors dict
--   carries pre-existing 'honesty_marker':'INFERRED' tags on the triangle/CMA risk scores
--   (formula-derived, not fabricated transaction data). Targeted ONLY the 76 in-scope polk
--   rows with no qualifying bid_decisions row (VERIFIED 76 missing before, 0 after) -- polk's
--   pre-existing 10,128 bid_decisions rows were NOT touched (existing case_numbers skipped).
--   Inserted=76, errors=0, skipped_existing=603.
--   J: deal_complete 603->679 (100.0%) PASS.
--
-- I (NOT FIXED -- confirmed genuine ceiling, not a bug): card_complete stayed at 614/679
--   (90.4%) before AND after both fixes above. Diagnosed live: ALL 65 remaining I-gap rows
--   (100%, VERIFIED via SQL: zone_matched_but_other_gap=0 of 65) fail solely because their
--   parcel_id has ZERO matching row in parcel_zones under ANY jurisdiction, in either the
--   appraiser-hyphenated format or the hyphen-stripped 18-digit fl_parcels format:
--     WITH gap AS (...) SELECT count(*) gap_rows,
--       count(*) FILTER (WHERE stripped IN (SELECT parcel_id FROM parcel_zones)) AS zone_row_exists
--     -> gap_rows=63, zone_row_exists=0
--   This is NOT the parcel_id-format mismatch it first appeared to be (fl_parcels co_no=63
--   uses a clean 18-digit format that IS the appraiser format with hyphens stripped -- VERIFIED
--   -- but parcel_zones for polk is itself only 1001 zone_code-populated rows total, spanning
--   inconsistent 9/12/16/18-digit formats across different jurisdiction_ids, and simply does
--   not contain these specific (mostly newer 2026 tax-deed) parcels in ANY format). Fixing this
--   requires a real zoning ingestion pass for these parcels into parcel_zones -- shared
--   ZoneWise infrastructure, out of this session's safe single-county-backfill scope. No
--   fabrication attempted (per HARD GUARDRAIL: a genuine data ceiling reported honestly, not
--   forced to look otherwise).
--
-- VERIFIED via pencil_dod_evaluate_county('polk') -- BEFORE vs AFTER, no regressions:
--   A: PASS -> PASS (unchanged)              F: PASS -> PASS (unchanged, tier1_sold=10/10)
--   B: PASS -> PASS (unchanged, 10/10)        G: PASS -> PASS (unchanged, 100.0)
--   C: FAIL(89.1%) -> PASS(97.1%)             H: PASS -> PASS (unchanged, 2.8h)
--   D: FAIL(89.1%) -> PASS(97.1%)             I: FAIL(90.4%) -> FAIL(90.4%) (confirmed ceiling)
--   E: PASS(99.9%) -> PASS(99.9%) (unchanged) J: FAIL(88.8%) -> PASS(100.0%)
--   7/10 -> 9/10
-- Original 605 pre-existing tier1-matched rows confirmed untouched/intact (VERIFIED: SELECT
-- count(*) FILTER (WHERE NOT parity_source LIKE 'tier1:shard6_run3645_ajax_harvest:%')
-- FROM multi_county_auctions WHERE county='polk' AND matched_clean AND parity_source LIKE
-- 'tier1%' -> 605, unchanged). Existing 10 B/F closed_sold rows untouched (still 10/10).
--
-- Environment: direct psql/pooler auth fails in this sandbox (matches every prior shard
-- session's note) -- all reads/writes this session went through the Supabase Management API
-- (POST /v1/projects/mocerqjnksmhcjzxrewo/database/query) for raw SQL and PostgREST
-- (SUPABASE_SERVICE_ROLE_KEY) for REST GET/PATCH/POST and the pencil_dod_evaluate_county RPC.
--
-- NEXT STEPS (not done this session, flagged honestly):
--   - polk: zoning ingestion for the ~63 (mostly 2026 tax-deed) parcels absent from
--     parcel_zones -- needs a real polk GIS/appraiser zoning scrape, not a relabeling. This
--     is the only remaining path to I passing for polk.
--   - polk: the 20 residual C/D-gap case_numbers on the 2026-08-20 tax_deed calendar
--     (00039-00050/00072-00082/00086-2026) may reappear on the live calendar closer to the
--     sale date -- worth a re-run of gold_standard_shard6_polk_cd_i_ajax_harvest.py nearer
--     08/20/2026 if they resurface.

SELECT 1; -- no-op placeholder: every live read/write this session went through the Supabase
          -- Management API SQL endpoint and PostgREST (no direct psql/pooler access from this
          -- environment). This file documents the diagnosis and fix for repo history. The
          -- actual writes were performed by scripts/gold_standard_shard6_polk_cd_i_ajax_harvest.py
          -- and scripts/shard6_polk_j_gap_backfill.py (both committed alongside this file).
