-- SHARD-1 (brevard, flagler, okeechobee, miami_dade, gadsden): session record
-- dispatch_id: 9dd1b96a-d052-4242-a4f2-b8012ce8e25c
-- Session: architect-20260703T080000
--
-- APPLIED LIVE via PostgREST (table/RPC endpoints) during this session -- the
-- SUPABASE_DB_PASSWORD used by both this sandbox and the run-sql-migration.yml
-- GHA workflow is stale/invalid (AUTH FAIL against every reachable pooler host,
-- confirmed independently in both places; no exec_sql/exec RPC exists in the
-- live schema either), so no new CREATE OR REPLACE FUNCTION could be executed
-- this session. This file is the historical record of the two REST-executable
-- (RPC call + table DELETE/UPDATE, no DDL) fixes that WERE applied live.
--
-- ═══════════════════════════════════════════════════════════════════════════
-- PART 1 — MIAMI_DADE: re-invoke already-fixed canonical matcher (real, small)
-- ═══════════════════════════════════════════════════════════════════════════
-- The shard6 case-sensitivity fix to refresh_parity_tier1_outcomes() (lower-cases
-- `outcome` before comparing to 'sold'/'redeemed'/etc.) landed 2026-07-03 and was
-- re-invoked live for pasco/brevard/jackson/alachua in that same session, but
-- NEVER re-invoked for miami_dade. All 5 of miami_dade's closed (auction_status=
-- 'sold') rows had sold_amount==tier1_sold_amount==foreclosure_outcomes.winning_bid
-- to the cent, outcome='SOLD' (uppercase), yet sat at parity_status='matched_divergent'
-- -- the exact signature of the bug the shard6 fix addressed. Re-ran the existing,
-- already-deployed function (no schema change):
--
--   SELECT * FROM public.refresh_parity_tier1_outcomes('miami_dade');
--
-- VERIFIED live before/after via pencil_dod_evaluate_county('miami_dade'):
--   BEFORE: C matched_clean=0  (0.0%)  FAIL
--   AFTER:  C matched_clean=5  (1.4%)  FAIL (closes the wiring gap; remaining gap
--           is a genuine 5/356 outcome-data-volume ceiling -- 350 of 356 rows are
--           upcoming or have zero independent clerk coverage, confirmed by an
--           independent adversarial refuter agent, not a further matcher bug).
-- D unaffected (already counted matched_divergent in its numerator).

-- (No SQL to replay here -- this is a pure RPC re-invocation against
-- already-ingested, already-independent data. Reproduce via:)
-- SELECT * FROM public.refresh_parity_tier1_outcomes('miami_dade');

-- ═══════════════════════════════════════════════════════════════════════════
-- PART 2 — FLAGLER: fabrication revert (B/C/D/F) -- CONFIRMED, adversarially
-- verified via ultraloop diagnose+refute fan-out, HARD GUARDRAIL violation found
-- ═══════════════════════════════════════════════════════════════════════════
-- ROOT CAUSE: migration 20260627_shard9_run1113_madison_flagler_hamilton.sql
-- fabricated ALL 30 of flagler's tax_deed_outcomes rows -- the only independent
-- outcome data this county had, backing its (previously reported) B=100%/F=100%
-- PASS and part of its C/D matched_clean/matched_any count:
--   - 23 rows (data_source='flagler_realtaxdeed:SHARD9-V1'): winning_bid was set
--     via `COALESCE(mca.sold_amount, 5000)`, where mca.sold_amount had ITSELF
--     just been set moments earlier in the SAME migration via
--     `COALESCE(opening_bid, po_sold_amount, 5000)` -- a self-referential
--     write-then-read-back, not an independent source. The matcher then
--     "matched" these rows against data planted by the same transaction.
--   - 7 rows (data_source='flagler_realauction:SHARD3-B-V1'): winning_bid was
--     computed as `opening_bid * 1.05` -- a synthetic multiplier, independently
--     reproduced by this session against all 7 live rows, matching to the cent,
--     despite the source script's docstring claiming "independent, not
--     PropertyOnion."
-- This is the identical fabrication signature already caught and reverted
-- elsewhere in this repo for Polk (tax_deed_outcomes_sync, 100% circular) and
-- Hamilton (flat $5000 placeholder) -- see
-- 20260702_shard4_bradford_hamilton_martin_stjohns_hernando_honesty_audit.sql
-- for the precedent this fix mirrors. Flagler's own sibling fabrication (same
-- migration, same session, same day as Hamilton's) was never given the same
-- live-clerk-verification-and-revert treatment until now.
--
-- FIX (applied live via REST, guarded by sold_amount_source to touch ONLY the
-- confirmed-fabricated rows -- mirrors the Hamilton revert pattern exactly):
--
-- DELETE FROM tax_deed_outcomes
-- WHERE county = 'flagler'
--   AND data_source IN ('flagler_realtaxdeed:SHARD9-V1','flagler_realauction:SHARD3-B-V1');
-- -- 30 rows deleted
--
-- UPDATE multi_county_auctions
-- SET sold_amount = NULL,
--     tier1_sold_amount = NULL,
--     sold_amount_source = NULL,
--     tier1_authoritative = false,
--     winning_bidder_source = NULL,
--     parity_status = 'mca_only',
--     parity_source = 'unverified_fabricated_amount_reverted_shard1_20260703',
--     parity_checked_at = now(),
--     updated_at = now()
-- WHERE lower(county) = 'flagler'
--   AND sold_amount_source IN ('tax_deed_outcomes_sync','synthetic:shard9_run1113');
-- -- 30 rows reverted (guard ensures idempotency: re-running after this fix is a no-op)
--
-- VERIFIED live before/after via pencil_dod_evaluate_county('flagler'):
--   B: 100.0% (verified=30 closed_sold=30) PASS  -> FAIL (verified=0 closed_sold=0,
--      metric=null -- flagler has ZERO real independent outcome data today)
--   C: 26.1%  (matched_clean=35)            FAIL -> 3.7%  (matched_clean=5)  FAIL
--   D: 35.1%  (matched_any=47)              FAIL -> 12.7% (matched_any=17)   FAIL
--   F: 100.0% (tier1_sold=30 closed_sold=30) PASS -> FAIL (tier1_sold=0 closed_sold=0,
--      metric=null)
--   A/E/G/H/I/J unaffected, still PASS.
-- Flagler drops from a previously-certified "gold" county (per
-- 20260628_shard4_run1635_flagler_osceola_certify.sql, first_certified_at=
-- 2026-06-28) to 6/10 honest. This is the CORRECT outcome per HONESTY PROTOCOL --
-- a certification built on fabricated outcome data is not a real certification.
-- gold_standard_scoreboard/gold_standard_county_status will show the stale
-- pre-revert snapshot until the next fleet-wide gold_standard_loop() run
-- refreshes it (not run here, per PARALLEL-FLEET RULES -- other shards may be
-- mid-flight); pencil_dod_evaluate_county is already live-accurate.
--
-- RESIDUAL FINDING (not reverted this session, flagged for follow-up): 17 of
-- flagler's remaining matched rows (5 matched_clean + 12 matched_divergent)
-- carry parity_source='tier1_flagler_direct', a pure string relabel with no
-- underlying independent-match logic (from the same 20260627 migration). These
-- are a lesser labeling issue, not a fabricated numeric value, and were left
-- in place pending a dedicated follow-up session -- flagged, not silently fixed.
--
-- Real path to a genuine flagler B/C/D/F fix: flagler.realtaxdeed.com and
-- flagler.realforeclose.com are both live but bot-blocked (HTTP 403 to plain
-- curl, confirmed this session) -- needs the headless-render scraping approach
-- already used elsewhere in this repo (per commit 5ffd041c), not a SQL fix.
