-- SHARD-2: marion/glades/orange/monroe/lake — gold standard session
-- dispatch_id: 5c84f9a8-513b-426a-bc93-86650bed8f26
-- Session: architect-20260703T080000
--
-- All statements below were already executed live via the Supabase Management
-- API (database/query) at the timestamps implied by this commit. This file is
-- the audit trail, not a script to re-run blind (the lake_e_parcel_linkage.py
-- call and the glades purge are NOT idempotent no-ops — see notes).
--
-- ============================================================================
-- 1) LAKE — criterion E parcel linkage (scripts/lake_e_parcel_linkage.py)
-- ============================================================================
-- Ran the existing Lake County PA FieldMap ArcGIS matcher against all lake rows
-- with parcel_id IS NULL (699 rows). Result: matched=526, ambiguous_skipped=37,
-- no_match=80, unparsed_address=56, errors=0.
--
-- CRITICAL BUG FOUND AND CORRECTED IN THE SAME SESSION: the script unconditionally
-- overwrote data_source='lake_pa_fieldmap_v1' on every matched row, including rows
-- whose data_source was 'propertyonion'. Because pencil_dod_evaluate_county's
-- population filter is `data_source <> 'propertyonion' OR tier1_authoritative`,
-- this silently smuggled 525 PropertyOnion-sourced auction rows into the scored
-- population (auctions_total 97 -> 622; E metric falsely jumped 68.0% -> 95.2%,
-- a false PASS). Confirmed via case_number: 525 of the 526 newly-labeled rows
-- matched the PO-xxxxxx PropertyOnion ID pattern.
--
-- Reverted live:
--   UPDATE multi_county_auctions SET data_source='propertyonion'
--   WHERE lower(county)='lake' AND data_source='lake_pa_fieldmap_v1'
--     AND case_number LIKE 'PO-%';                                  -- 525 rows
--
-- parcel_id/owner_name were KEPT for all 526 (the ArcGIS match itself is real and
-- independent of the auction record's provenance) — only the canon-gating
-- data_source label was reverted.
--
-- Fixed scripts/lake_e_parcel_linkage.py so this cannot recur: it now only stamps
-- data_source when the row previously had none (see enrichment_body()). Any other
-- county that has ever run this same script pattern should be audited for the
-- same contamination signature (data_source relabeled + case_number LIKE 'PO-%')
-- — NOT done here, out of this shard's assigned counties.
--
-- VERIFIED before/after (pencil_dod_evaluate_county, 2026-07-03):
--   lake E: 68.0% (parcel_linked=66 of 97) -> 69.1% (parcel_linked=67 of 97)   FAIL
--   (honest +1 gain, not the false +526)
--
-- ============================================================================
-- 2) GLADES — ghost-success purge (entire county was fabricated seed data)
-- ============================================================================
-- glades' only 2 auction rows were case_number='GLADES-FC-SEED-2026' /
-- 'GLADES-TD-SEED-2026', parcel_id='SYN-GLD-FC-001'/'SYN-GLD-TD-001'
-- (data_source null on the auctions, 'realforeclose:glades:shard9' on the
-- outcome row) — a SHARD-9 bootstrap seed (2026-06-24), not real auction data.
-- This fabrication was propagating through foreclosure_outcomes (1 row) and
-- bid_decisions (2 rows), making B/E/F/G/H/I/J all show false PASS on 100%-fake
-- inputs (prior brief showed glades 8/10).
--
--   DELETE FROM bid_decisions WHERE case_number IN
--     ('GLADES-FC-SEED-2026','GLADES-TD-SEED-2026');                -- 2 rows
--   DELETE FROM foreclosure_outcomes WHERE case_number IN
--     ('GLADES-FC-SEED-2026','GLADES-TD-SEED-2026');                -- 1 row
--   DELETE FROM multi_county_auctions WHERE case_number IN
--     ('GLADES-FC-SEED-2026','GLADES-TD-SEED-2026');                -- 2 rows
--
-- VERIFIED after (2026-07-03): glades auctions_total=0, all letters FAIL/null
-- except G (zoning KPI view, unrelated to auction rows). This is a REGRESSION
-- from the false 8/10 to an honest 1/10 (G only) — required by canon: fabricated
-- PASSes are not PASSes. glades.realforeclose.com/.realtaxdeed.com are already
-- configured live in pipeline.counties (pipeline_status='active') and need a
-- REAL harvest run — not attempted this session (see monroe note below on why
-- the CALENDAR-page date discovery approach failed and needs the AJAX path).
--
-- ============================================================================
-- 3) MONROE — pipeline.counties wiring gap (criterion A)
-- ============================================================================
-- monroe had foreclosure_platform/foreclosure_url/taxdeed_platform/taxdeed_url
-- all NULL in pipeline.counties (auto-seeded 2026-05-20, pipeline_status
-- 'pending') despite 25 real tax_deed rows already present in
-- multi_county_auctions via some other ingestion path. fc=0 td=25 confirmed A
-- FAIL. Verified live with a browser User-Agent (bare curl gets a WAF 403):
--   monroe.realforeclose.com -> 200, monroe.realtaxdeed.com -> 200
--
--   UPDATE pipeline.counties SET
--     foreclosure_platform='realforeclose',
--     foreclosure_url='https://monroe.realforeclose.com/index.cfm?zaction=USER&zmethod=CALENDAR',
--     taxdeed_platform='realtaxdeed',
--     taxdeed_url='https://monroe.realtaxdeed.com/index.cfm?zaction=USER&zmethod=CALENDAR'
--   WHERE county_slug='monroe';
--
-- This closes the config/wiring gap only — it does NOT move the A metric by
-- itself, because A counts sale_type='foreclosure' rows in multi_county_auctions,
-- which requires an actual calendar harvest to run. Attempted live: the
-- ?zaction=USER&zmethod=CALENDAR page returns a generic cross-Realauction
-- marketing page with unrelated out-of-state dates (e.g. Bellmawr NJ), not a
-- monroe-specific date list — the real calendar is populated client-side via the
-- same AJAX mechanism used by scripts/shard2_run2450_ajax_realforeclose_harvest.py
-- (PREVIEW+AJAX UPDATE against a real AUCTIONDATE), which needs a genuine
-- upcoming date discovered first, not guessed. NOT built this session — documented
-- honestly per the same "genuine scraper-build needs" pattern as orange's residual
-- C/D gap (see 20260703_shard10_desoto_jackson_orange_volusia_cd_ghost_success_purge.sql).
--
-- ============================================================================
-- 4) ORANGE — C/D/I confirmed at genuine structural ceiling, no action taken
-- ============================================================================
-- C/D: tax_deed_outcomes for orange = 206 rows, ALL already consumed by the
-- existing matched_clean=206 (post shard10 ghost-success purge this morning).
-- foreclosure_outcomes for orange = 0 rows. Re-running
-- refresh_parity_tier1_outcomes('orange') would find zero new matches (confirmed
-- by inspecting eligible_unset=453 rows against 0 available foreclosure_outcomes
-- and already-exhausted tax_deed_outcomes) — the gap requires new outcome
-- ingestion (Orange Clerk/RealAuction result harvest), a scraper-build task, not
-- a matcher-run task. NOT attempted blind.
-- I: the 59-row gap (796/855 -> need 95%) is dominated by 43 rows with
-- property_address IS NULL, of which the majority are timeshare foreclosures
-- (parcel_id='TIMESHARE' placeholder, identical lat/long centroid across many
-- rows) that structurally lack a conventional situs address in the court filing.
-- Fabricating an address would be a canon violation. NOT attempted.
--
-- marion: independently re-verified 10/10 PASS this session, no action needed.
