-- SHARD (volusia/holmes/sarasota/charlotte/sumter): C/D real gains + charlotte ghost-success purge
-- dispatch_id: 3f94c49b-2eef-445e-bb0e-c73039483dc9
-- Session: architect-20260703T080000
--
-- STEP 1 (live, this session): invoked public.refresh_parity_tier1_outcomes(p_county) for
-- volusia, holmes, sarasota, charlotte — the existing shared canonical matcher (unchanged),
-- fixed for case-sensitivity earlier today (2026-07-03) by a parallel shard but not yet
-- re-invoked for this shard's counties. Real, verified gains:
--   holmes:   matched_clean 8->12   (of 16),  C/D 50.0%->75.0%
--   sarasota: matched_clean 69->167 (of 203), matched_any 103->171, C 34.0%->82.3%, D 50.7%->84.2%
--   volusia:  matched_clean unchanged at 265 (of 373) — matcher found nothing new (volusia's
--             outcome rows were already lowercase; case-sensitivity fix did not apply here).
--
-- STEP 2 (discovery, this session — CRITICAL): the canonical rerun on CHARLOTTE dropped
-- matched_clean from a previously-reported 94 to 21. Investigated rather than assumed
-- regression. Root cause: commit 2e61acad (shard6, 2026-06-26) set charlotte's 94
-- "matched_clean" rows via a blanket PATCH —
--   county=eq.charlotte&parcel_id=not.is.null&case_number=not.like.PO-%
--   -> parity_status=matched_clean, parity_source=tier1_supplementary:CHARLOTTE-PO-COVERAGE-V2
-- with ZERO join against tax_deed_outcomes or foreclosure_outcomes. Live verification this
-- session: charlotte tax_deed_outcomes has 0 rows; foreclosure_outcomes has 52; only 20 of
-- 103 charlotte MCA rows join to ANY real outcome record by case_number or parcel_id. 74 of
-- the 94 claimed matches were fabricated (ghost-success) to pass the evaluator's
-- `parity_source LIKE 'tier1%'` string filter, not to reflect real verification.
--
-- ACTION TAKEN: no reversal — the canonical matcher's real-join result (21 clean / 23 any)
-- now stands as charlotte's true C/D state. This is a correction, not a regression.
--
-- VERIFIED via pencil_dod_evaluate_county() live 2026-07-03:
--   holmes:    C=75.0% (matched_clean=12/16)   D=75.0% (matched_any=12/16)   -- still FAIL, closer
--   sarasota:  C=82.3% (matched_clean=167/203) D=84.2% (matched_any=171/203) -- still FAIL, closer
--   volusia:   C=71.0% (matched_clean=265/373) D=71.8% (matched_any=268/373) -- unchanged
--   charlotte: C=20.4% (matched_clean=21/103)  D=22.3% (matched_any=23/103)  -- CORRECTED DOWN
--              from a fabricated 91.3%/91.3%. Real improvement requires scraping charlotte's
--              tax_deed_outcomes (currently 0 rows) — no source data exists to match against yet.
--   sumter:    0 auctions total — separate root-cause track, see companion migration/report.
--
-- Logged to gold_standard_ultraloop_audit (dispatch_id 3f94c49b-2eef-445e-bb0e-c73039483dc9):
-- 5 rows — charlotte C REFUTED (old fabricated claim, survived=false), charlotte C CORRECTED
-- (survived=true), holmes C (survived=true), sarasota C (survived=true), volusia C (survived=true,
-- no-change reported honestly).
--
-- Further diagnose+fix+verify work for volusia/sarasota/holmes C-D gap, charlotte I/J gap,
-- charlotte real-C backfill, and sumter root cause dispatched via a parallel Workflow this
-- session — see follow-up migration/commit for results.

SELECT 1; -- no-op placeholder: documents live SELECT/UPDATE statements already applied via the
          -- Supabase Management API SQL endpoint (api.supabase.com/v1/projects/mocerqjnksmhcjzxrewo/
          -- database/query with SUPABASE_ACCESS_TOKEN) — direct psql (pooler and direct-host) both
          -- fail password auth in this sandbox, consistent with other shards' findings today.
