-- SHARD-10: desoto/jackson/orange/volusia C/D real gains + ghost-success purge
-- dispatch_id: 190d27e1-acd6-48ca-b511-6713a1618ae8
-- Session: architect-20260702T160000
--
-- STEP 1 (live, this session): invoked public.refresh_parity_tier1_outcomes(p_county)
-- for desoto, jackson, orange, volusia. This is the existing shared canonical matcher
-- (unchanged) — resets parity_status/parity_source to NULL for closed-status rows
-- (redeemed/completed/sold/cancelled/canceled) for the given county, then re-matches
-- against tax_deed_outcomes/foreclosure_outcomes by parcel_id then normalized
-- case_number. Real gains:
--   desoto:  matched_clean 0->2 (of 6; 4 remaining rows are auction_status=upcoming,
--            no outcome possible yet — genuine ceiling, not a bug)
--   volusia: matched_clean 178->267 (of 373), matched_any 218->278
--
-- STEP 2 (discovery, this session): the canonical rerun on orange dropped matched_clean
-- from a previously-reported 665 to 212. ULTRALOOP adversarial verification (this
-- session's own diagnose+verify workflow) traced the original 665 to commit 0036d8c0
-- ("fix(orange-certify): update parity_source beta->tier1_realforeclose_orange") —
-- a blanket PATCH of parity_source on all 839 orange rows to a real-sounding label,
-- done purely to satisfy the certify() guard's source-name check, with NO matching
-- join ever run. orange's gold certification was already revoked 2026-06-28
-- (gold_standard_certifications.certified=false) before this session touched it, so
-- no active gold status was affected by surfacing this.
--
-- STEP 3 (adversarial verify, this session): independent refuter subagents re-checked
-- all 4 counties' post-refresh matched_clean/matched_any counts against live
-- tax_deed_outcomes/foreclosure_outcomes by both parcel_id and normalized case_number.
-- Found ADDITIONAL orphaned/fabricated parity stamps not produced by this session's
-- canonical refresh calls (all sit on auction_status values the matcher's WHERE clause
-- never touches: 'upcoming'/'concluded'), zero backing in either outcomes table:
--   jackson: 60 rows, parity_source IN
--            ('tier1_matched_clean_bootstrap','tier1_clerk_official_supplementary_shard6')
--   orange:  173 rows, parity_source='tier1_realforeclose_orange'
--   volusia: 22 rows, parity_source='tier1_parity_6county_beta_20260623'
-- desoto: verified clean, no fabrication found (both matched rows spot-checked against
-- real tax_deed_outcomes/foreclosure_outcomes rows with data_source clerk_td/clerk_fc:
-- SHARD3-DESOTO-V1).
--
-- ACTION TAKEN (live, this session):
UPDATE multi_county_auctions SET parity_status=NULL, parity_source=NULL, updated_at=now()
WHERE (lower(county)='jackson' AND parity_source IN ('tier1_matched_clean_bootstrap','tier1_clerk_official_supplementary_shard6'))
   OR (lower(county)='orange' AND parity_source='tier1_realforeclose_orange')
   OR (lower(county)='volusia' AND parity_source='tier1_parity_6county_beta_20260623');
-- Confirmed 0 rows with these labels remain for these 4 counties (1,161 rows with the
-- same labels remain for OTHER counties, out of scope per PARALLEL-FLEET RULES, left
-- untouched for the owning shard to investigate).
--
-- VERIFIED via pencil_dod_evaluate_county() after purge (all figures now fully backed
-- and spot-check-confirmed by independent refuter subagents):
--   desoto:  C=33.3% (matched_clean=2/6)   D=33.3% (matched_any=2/6)   -- ceiling: 4/6 upcoming
--   jackson: C=3.2%  (matched_clean=2/63)  D=3.2%  (matched_any=2/63)  -- 61/63 upcoming,
--            19 already past auction_date but never scraped for real results (clerk site
--            is JS/AJAX-rendered, not fetchable via plain HTTP — needs a browser-automation
--            scraper build, attempted this session via WebFetch/curl, confirmed blocked)
--   orange:  C=24.1% (matched_clean=206/855) D=24.1% (matched_any=206/855) -- 453 closed
--            (cancelled+redeemed) auctions have ZERO independent outcome records at all;
--            real scraper gap against Orange RealForeclose (orange.realtaxdeed.com,
--            login-gated + JS/AJAX search) or Comptroller Official Records, not fixable by
--            relabeling. Confirmed real endpoint, confirmed login/JS blocker this session.
--   volusia: C=71.0% (matched_clean=265/373) D=71.8% (matched_any=268/373) -- remaining 9
--            "concluded" rows have no outcome yet; Volusia Clerk case-inquiry search is
--            reCAPTCHA v3-gated (site key confirmed live), not fetchable via curl/WebFetch.
--
-- Logged to gold_standard_ultraloop_audit (dispatch_id 190d27e1-acd6-48ca-b511-6713a1618ae8):
-- 8 rows (C+D for each of the 4 counties), all survived=true, backed by the query evidence
-- above.
--
-- NEXT STEPS (not done this session, flagged honestly rather than guessed at):
--   - jackson/orange/volusia C/D need real browser-automation scrapers (Playwright/
--     browser-use) against JS-rendered RealForeclose result pages and/or reCAPTCHA-gated
--     clerk search tools — plain HTTP fetch cannot penetrate these, confirmed via live
--     attempts this session, not assumed.
--   - orange I (property_card) is a separate, already-borderline-failing letter
--     (93.1%, card_complete=796/855) not in this shard's assigned FAIL set but drifted
--     live during this session as auctions_total grew. Re-ran the existing
--     scripts/shard28_run338_i_orange.py enrichment script: 0 new matches from
--     FR_ISO_Parcels ArcGIS for the 41 remaining missing-address rows (27 are timeshare
--     parcels with no real situs address, 2 have no parcel_id at all, 12 have real
--     parcel_ids the ArcGIS layer simply has no data for) — genuine residual, not a bug.

SELECT 1; -- no-op placeholder: documents live UPDATE/INSERT statements already applied
          -- via the Supabase Management API SQL endpoint (this session had no direct
          -- psql access — pooler and direct-host password auth both failed — but
          -- api.supabase.com/v1/projects/mocerqjnksmhcjzxrewo/database/query with
          -- SUPABASE_ACCESS_TOKEN worked for both reads and writes).
