-- SHARD-3 continuation: hamilton — ULTRALOOP adversarial verification results + E ghost-pass fix
-- dispatch_id: 09e317ef-d722-4e29-a310-77593b6e8658
-- Session: architect-20260703T080000
--
-- Per this session's ultracode opt-in and the ULTRALOOP PROTOCOL, the hamilton claims from
-- 20260703_shard3_hamilton_real_taxdeed_ingestion_pasco_palmbeach_ceiling_confirmed.sql were
-- run through 3 independent adversarial refuter subagents (Workflow run wf_986144a0-1a1,
-- dispatch background task w1zrorxhx). Results, logged live to gold_standard_ultraloop_audit:
--
--   A (fc=6,td=10, PASS):        REFUTED (survived=false)
--   C (matched_clean=7, 43.8%):  REFUTED (survived=false)
--   D (matched_any=7, 43.8%):    REFUTED (survived=false)
--   I (dilution, honest):        SURVIVED (survived=true)
--   J (dilution, honest):        SURVIVED (survived=true)
--
-- The refuter for A/C/D independently re-scraped hamiltonclerk.com/tax-deeds/ live and
-- confirmed the 7 outcome-backed rows match the source exactly to the cent (parcel_id,
-- cert_number, opening_bid, redeemed status) -- it did not find fabricated values. It
-- refuted on two grounds: (1) the claim said "10 real tax_deed rows" while only 7 have
-- tax_deed_outcomes evidence (the other 3 are genuinely still-active/unresolved certs per
-- the live page, same as any other pending auction -- expected, not fabrication, but the
-- claim's wording did not make this distinction clearly enough), and (2) the same 10 cert
-- numbers were the subject of a CRITICAL ghost-success revert ~92 minutes earlier in this
-- same session, and the refuter could not rule out that this was a repeat rather than a
-- genuine re-fetch, despite its own independent verification supporting authenticity.
--
-- DISPOSITION: per protocol ("refuted = false positive: log it, do not count it, do not
-- certify on it"), hamilton's A/C/D gains from that migration are NOT counted toward
-- certification this session, despite the claiming agent's continued belief (backed by the
-- refuter's own re-scrape) that the underlying data is genuine. This is intentional: the
-- adversarial gate does not require the claimant's agreement to hold.
--
-- REAL, CONFIRMED FINDING from the same refuter pass (not a pre-registered claim, a
-- discovery): 5 of hamilton's original 6 real foreclosure rows (case_number 2024-CA-19,
-- 2023-CA-41, 2025-CA-66, 2025-CA-46, 2025-CA-37) still carried synthetic 'HAM-SYN-00X'
-- placeholder parcel_ids from the 2026-06-25 bootstrap script. The earlier same-day
-- ghost-success revert deleted fabricated ROWS but never corrected this fabricated FIELD on
-- the rows it kept (those rows are real cases, just with a placeholder parcel_id). This
-- inflated E to a false 100% PASS (16 of 16 "parcel_linked").
--
-- ACTION TAKEN (live, this session):
--   UPDATE multi_county_auctions SET parcel_id=NULL WHERE county='hamilton' AND
--     parcel_id LIKE 'HAM-SYN-%';  -- 5 rows corrected
--
-- VERIFIED via pencil_dod_evaluate_county('hamilton') after the fix:
--   E: 100.0% (16 of 16, FALSE PASS) -> 68.8% (11 of 16, honest FAIL)
--   I: 37.5% -> 6.3% (further honest drop; I's card_complete requires a real parcel_id
--      match against the zoning card view, which these 5 rows no longer satisfy)
--
-- HAMILTON FINAL HONEST STATE this session: 3/10 (A, G, H pass). This is LOWER than the
-- 5/10 this migration's predecessor reported, because that predecessor's E was itself a
-- ghost-pass -- caught here by the adversarial process, not missed by inaction. auctions_total
-- grew from 6 to 16 (real growth: 10 genuine tax-deed cases added), but three separate
-- honesty gates (A/C/D certification, E parcel-linkage) now correctly reflect a harder,
-- more accurate picture than any single-agent pass produced today.
--
-- gold_standard_ultraloop_audit rows for this correction: dispatch_id
-- 09e317ef-d722-4e29-a310-77593b6e8658, county_slug=hamilton, letter=E, survived=true
-- (the correction itself, not the original inflated claim).

SELECT 1; -- no-op placeholder: documents the live UPDATE and 6 gold_standard_ultraloop_audit
          -- INSERTs already applied via the Supabase Management API at the timestamps above.
