-- SHARD-11 (dispatch_id d0b9d16b-4554-4e5a-ae0f-5247fe6abe4d): dixie C/D
-- ghost-success purge + canonical rematch. Applied live via Supabase Management
-- API SQL endpoint (api.supabase.com/v1/projects/mocerqjnksmhcjzxrewo/database/query
-- with SUPABASE_ACCESS_TOKEN) -- this runner has no working direct psql/pooler
-- auth, same limitation documented in prior shard migrations (e.g.
-- 20260703_shard6_madison_cd_canonical_rematch.sql).
--
-- ROOT CAUSE (CONFIRMED): 11 dixie rows carried parity_source=
-- 'tier1_dixie_clerk_scrape_shard6' -- 8 as parity_status='matched_clean' and
-- 3 as parity_status='mca_only' -- with ZERO backing in tax_deed_outcomes or
-- foreclosure_outcomes by normalize_case_number(case_number) (verified by LEFT
-- JOIN against both tables for lower(county)='dixie', all 11 returned NULL on
-- both sides; also checked by parcel_id, same null result). This is the exact
-- ghost-success / pre-existing-label-blocks-canonical-rematch pattern already
-- purged today for hillsborough/madison/wakulla (commit 06f36caf,
-- 20260703_shard6_hillsborough_cd_ghost_success_purge.sql): a stale/fabricated
-- parity_source occupies the column so refresh_parity_tier1_outcomes()'s reset
-- clause (only clears parity_source to NULL for closed-status rows whose
-- parity_source IS the function's own labels) never touches these rows, and the
-- pre-stamped 'matched_clean' status counts toward C/D's numerator without any
-- real independent-source verification.
--
-- Breakdown of the 11 unbacked rows (by auction_status):
--   cancelled  (9): 7x matched_clean, 2x mca_only -- all case_number pattern
--                   'DIXIE-SYNTH-<parcel>' with zero tax_deed_outcomes/
--                   foreclosure_outcomes row for dixie under that case_number
--                   or parcel_id. No real sale outcome exists for these.
--   scheduled  (1): mca_only, auction_date=2026-07-13 (future) -- genuinely
--                   cannot have a sale outcome yet.
--   upcoming   (1): matched_clean, case_number='15-2023-CA-57',
--                   auction_date=2026-07-21 (future) -- also genuinely cannot
--                   have a sale outcome yet, so its pre-existing 'matched_clean'
--                   label was impossible on its face (an upcoming auction has
--                   no closed sale to match).
--
-- Sanity check (CONFIRMED): the 21 rows under parity_source=
-- 'tier1_tax_deed_outcome' (the ones NOT touched by this migration) were
-- independently verified backed -- each has a matching tax_deed_outcomes row
-- by case_number with data_source='shard6_clerk_independent:V1' (a real
-- independent scraper tag, not a self-referential/promote label). These are
-- left untouched.
--
-- STEP 1 (BEFORE, live query): SELECT public.pencil_dod_evaluate_county('dixie');
--   C: pass=false matched_clean=29 metric=90.6  (fabricated -- 8 of these rows unbacked)
--   D: pass=false matched_any=29   metric=90.6  (fabricated, same 8 rows)
--
-- STEP 2 (ACTION, live, this session):
--   UPDATE public.multi_county_auctions
--   SET parity_status = NULL, parity_source = NULL, updated_at = now()
--   WHERE county = 'dixie' AND parity_source = 'tier1_dixie_clerk_scrape_shard6';
--   -- 11 rows purged, confirmed via RETURNING case_number (7 matched_clean
--   -- cancelled + 2 mca_only cancelled + 1 mca_only scheduled + 1 matched_clean
--   -- upcoming = 11 total).
--
--   SELECT * FROM public.refresh_parity_tier1_outcomes('dixie');
--   -- existing shared canonical matcher, UNCHANGED. Result: case-number pass
--   -- matched_clean=21, matched_divergent=0 (the pre-existing 21
--   -- tier1_tax_deed_outcome rows, untouched by the purge); parcel-id pass
--   -- matched_clean=0, matched_divergent=0 -- none of the 11 purged rows found
--   -- any real backing by case_number or parcel_id. Confirms they are
--   -- genuinely unmatchable, not blocked by a bug.
--
-- STEP 3 (AFTER, live query): SELECT public.pencil_dod_evaluate_county('dixie');
--   C: pass=false matched_clean=21 metric=65.6  (honest, down from fabricated 90.6)
--   D: pass=false matched_any=21   metric=65.6  (honest, down from fabricated 90.6)
--   All other letters (A/B/E/F/G/H/I/J) unaffected, still PASS.
--
-- STRUCTURAL CEILING (verified, not just asserted): dixie has 32 auctions total.
-- Of the 11 non-tax_deed-backed rows, 9 are cancelled 'DIXIE-SYNTH-' rows with
-- no real sale outcome ever recorded for them in tax_deed_outcomes or
-- foreclosure_outcomes (dixie has exactly 21 tax_deed_outcomes rows, all
-- already matched), and 2 are genuinely future (scheduled/upcoming) auctions
-- that cannot have a sale outcome by definition. REAL CEILING = 21/32 = 65.6%.
-- This is NOT fixable by more relabeling or rematching this session -- it
-- requires either (a) the 2 future auctions closing and getting real outcome
-- records over time, or (b) a real clerk-scrape data source for the 9
-- cancelled synthetic rows, which does not currently exist in this database
-- (the label claiming to be that source, 'tier1_dixie_clerk_scrape_shard6',
-- was fabricated/self-referential and has been purged).
--
-- No other county touched by this migration. gold_standard_loop()/
-- gold_standard_certify() NOT invoked (other shards may run concurrently,
-- per PARALLEL-FLEET RULES).

SELECT 1; -- no-op placeholder: documents the live UPDATE + refresh_parity_tier1_outcomes('dixie')
          -- calls already applied via the Supabase Management API SQL endpoint in this session.
