-- SHARD-4: canonical C/D parity refresh (hillsborough/hendry/polk/alachua) + alachua E linkage
-- dispatch_id: 2f288479-0e2f-49d1-bb61-c152405430c0
-- Session: architect-20260703T080000
-- Shard counties: hillsborough, hendry, polk, alachua, collier
--
-- APPLIED LIVE via Supabase Management API (psql pooler auth fails in this sandbox;
-- no exec() RPC available -- same environment constraint documented by the concurrent
-- shard-9 session today). All statements below were executed against production.
--
-- ═══════════════════════════════════════════════════════════════════════════════
-- STEP 1: canonical parity matcher re-run (C/D)
-- ═══════════════════════════════════════════════════════════════════════════════
-- Ran the existing public.refresh_parity_tier1_outcomes(p_county) function (defined in
-- 20260703_shard6_refresh_parity_case_sensitivity_fix.sql, NOT modified here) for all
-- four data-bearing shard counties. This function resets parity_status/parity_source to
-- NULL for closed-status rows, then rematches against tax_deed_outcomes/foreclosure_outcomes
-- by parcel_id then case_number.
--
--   SELECT * FROM public.refresh_parity_tier1_outcomes('hillsborough');
--   SELECT * FROM public.refresh_parity_tier1_outcomes('hendry');
--   SELECT * FROM public.refresh_parity_tier1_outcomes('polk');
--   SELECT * FROM public.refresh_parity_tier1_outcomes('alachua');
--
-- RESULTS (pencil_dod_evaluate_county before -> after, live-verified):
--   hillsborough: C 92.6% (848/916) -> 92.6% (848/916) NO CHANGE. D 98.6%->98.6% NO CHANGE.
--                 Baseline was already genuine tier1-sourced; re-run reproduced identical state.
--   hendry:       C/D 5.3% (1/19) -> 5.3% (1/19) NO CHANGE. Only 1 closed hendry auction has
--                 ever had an independent outcome record; structural ceiling, not a bug.
--   alachua:      C/D 35.0% (14/40) -> 35.0% (14/40) NO CHANGE. Baseline already genuine.
--   polk:         C matched_clean 410->91 of 616 (66.6%->14.8%). D matched_any 499->128
--                 (81.0%->20.8%). THIS IS A GHOST-SUCCESS PURGE, NOT A REGRESSION -- see below.
--
-- ═══════════════════════════════════════════════════════════════════════════════
-- POLK FINDING: pre-existing C/D baseline was fabricated (adversarially verified)
-- ═══════════════════════════════════════════════════════════════════════════════
-- Root cause: supabase/migrations/20260628_polk_tier1_prefix_cd_parity.sql STEP 3 executed:
--   UPDATE multi_county_auctions SET parity_status='matched_clean',
--     parity_source='tier1_clerk_polk_retrofix_run1636', ...
--   WHERE lower(county)='polk' AND parity_status IS NULL AND case_number IS NOT NULL
--     AND case_number NOT LIKE 'PO-%' AND case_number NOT LIKE 'PO\_%' ESCAPE '\';
-- This labeled ANY polk row with a non-PropertyOnion-style case number as tier1-prefixed
-- matched_clean -- with NO join to tax_deed_outcomes or foreclosure_outcomes, i.e. no actual
-- independent verification. It inflated C/D by ~319 rows. This is the same failure class as
-- the ALREADY-DOCUMENTED polk B/F fabrication reverted in
-- 20260702_shard6_polk_bf_fabrication_revert.sql (a different session, same county, same
-- underlying discipline gap).
--
-- Live verification at time of this session: tax_deed_outcomes has 0 rows for polk,
-- foreclosure_outcomes has 10 rows for polk, despite 96 tax-deed + 520 foreclosure polk
-- auctions -- i.e. polk has almost no genuine independent outcome coverage yet. The canonical
-- refresh_parity_tier1_outcomes() run reset the fabricated STEP-3 labels (closed-status rows
-- only) and rebuilt matched_clean from the 10 real foreclosure_outcomes rows + pre-existing
-- shard11 clerk-supplementary rows (76, untouched because their auction_status was not in the
-- closed-status reset list) = 91 genuine matched_clean rows. Verified live: zero
-- 'tier1_clerk_polk_retrofix_run1636' / 'tier1_fallback_polk_retrofix_run1636' sourced rows
-- remain with any matched status post-refresh.
--
-- DECISION: do NOT restore the fabricated numbers. 14.8%/20.8% is polk's honest current C/D
-- ceiling. Closing the real gap requires genuine tax_deed_outcomes/foreclosure_outcomes
-- ingestion for polk (near-zero coverage today), not another parity-matcher run. Adversarially
-- verified via ULTRALOOP workflow this session -- see gold_standard_ultraloop_audit rows for
-- dispatch_id above.
--
-- ═══════════════════════════════════════════════════════════════════════════════
-- STEP 2: alachua E fix -- one real, address-verified parcel_id link
-- ═══════════════════════════════════════════════════════════════════════════════
-- 7 of 40 alachua auctions had NULL parcel_id. 6 of 7 carry a generic placeholder
-- property_address ("ALACHUA COUNTY FL", no street) with no legitimate source to link from
-- in this sandbox -- left NULL, not fabricated. The 7th had a real street address, matched
-- exactly (street + city + zip) against Alachua County Property Appraiser data (fl_parcels
-- co_no=11, confirmed as alachua's real DOR county number from existing linked rows; also
-- cross-checked against fl_parcels_addr_lookup normalized index):
--
--   fl_parcels: parcel_id='02578-003-001', phy_addr1='4516 SW 266TH ST',
--               phy_city='NEWBERRY', phy_zipcd='32669'
--   auction:    case_number='01 2025 CA 001229',
--               property_address='4516 SW 266TH ST, NEWBERRY, FL- 32669'

UPDATE multi_county_auctions
SET parcel_id = '02578-003-001', updated_at = now()
WHERE lower(county) = 'alachua'
  AND case_number = '01 2025 CA 001229'
  AND parcel_id IS NULL;

-- RESULT: alachua E (parcel linkage) 82.5% (33/40) -> 85.0% (34/40). Still below 95% threshold
-- -- the remaining 6 rows need deeper case-document research (no usable address in this
-- sandbox), not another SQL join.
--
-- ═══════════════════════════════════════════════════════════════════════════════
-- COLLIER (1/10): NOT TOUCHED -- genuine environment blocker, documented not fabricated
-- ═══════════════════════════════════════════════════════════════════════════════
-- pipeline.counties shows collier foreclosure_platform=NULL, taxdeed_platform=NULL,
-- pipeline_status='pending', pipeline_health='inactive' -- county has never been onboarded.
-- multi_county_auctions has 0 collier rows. Real onboarding requires the Firecrawl-based
-- scraper (.github/scripts/scrape_realauction_county.py) against collier.realforeclose.com /
-- collier.realtaxdeed.com; both return HTTP 403 to direct (non-Firecrawl) requests, and
-- FIRECRAWL_API_KEY is not present in this sandbox's environment. scripts/shard5_a_lane_collier.py
-- exists from a prior session but its "bootstrap rows" step would fabricate auction data --
-- explicitly NOT run, per HARD GUARDRAIL #2 and this repo's own history of purging exactly
-- this pattern (see calhoun/monroe/sumter/highlands synthetic_bootstrap_cleanup,
-- okeechobee bootstrap_finding, polk B/F fabrication_revert above). Collier A remains blocked
-- pending either a FIRECRAWL_API_KEY-equipped session or a different real data source.
--
-- ═══════════════════════════════════════════════════════════════════════════════
-- HILLSBOROUGH I (95.0%, 870/916 -- needs exactly +1 row to cross 95% threshold): investigated,
-- NOT fixed. The 46-row card_complete gap splits into 20 rows missing parcel_id (already
-- counted in E's gap) and 25-26 rows with parcel_id but missing geo/assessed-value. Checked
-- fl_parcels and fl_parcel_assessments (co_no=29) for those parcel_ids -- zero matches; HCPA's
-- own public ArcGIS services (gis.hcpafl.org/arcgis/rest/services/Webmaps/HillsboroughFL_WebParcels)
-- DO resolve the parcel geometry/address (confirmed live: strap match found for one sample
-- parcel_id) but expose no assessed-value field -- valuation lives behind HCPA's property
-- record-card search UI, which requires JS-rendered scraping (Firecrawl) unavailable in this
-- sandbox. Same class of blocker as collier A. Not force-fixed with placeholder values.
