-- SHARD-14 (duval/sarasota/holmes/union) run3025: ultracode workflow diagnose+verify+apply+reverify
-- dispatch_id: 9e70dcd7-f9cd-4c17-b3a1-596a9da4b20f
-- Session: architect-20260704T160000
--
-- ENVIRONMENT NOTE (confirmed live this session, consistent with other shards' 2026-07-04 findings):
-- direct psql and the Supabase Management API SQL endpoint (api.supabase.com/.../database/query) both
-- fail in this sandbox (Cloudflare error 1010 on the Management API; password auth fails on psql).
-- All live reads/writes this session went through PostgREST (/rest/v1/<table> GET/PATCH) and RPC calls
-- to EXISTING functions (pencil_dod_evaluate_county, refresh_parity_tier1_outcomes). No new SQL
-- functions were created live; this migration file documents what was actually applied via REST.
-- No Firecrawl/scraping capability this session (FIRECRAWL_API_KEY absent from env; direct fetch to
-- unionclerk.com returns HTTP 403, bot-blocked) -- all work below is derived from data already in the DB.
--
-- Ran an ultracode Workflow: 4 diagnose agents (one per county work item) -> 2 adversarial-refute
-- agents (duval-fc, duval-td candidate batches) -> 1 apply agent (only for survived candidates) -> 4
-- reverify agents (fresh pencil_dod_evaluate_county call per county). 11 agents total, 58 tool calls.
--
-- ── DUVAL ── (C/D real, small, adversarially-verified gain)
-- Calling the canonical matcher public.refresh_parity_tier1_outcomes(p_county='duval') as routine
-- step-1 maintenance (per established SOP from prior shards) corrected a stale cached count: C dropped
-- from a pre-session 26.3% (163/620) to a freshly-recomputed 14.2% (88/620); D rose slightly 45.0%->
-- 48.4% (279->300). This is a correction (the canonical matcher is the source of truth), not a
-- regression -- 18 of the previously-counted rows already carried a parity_source explicitly labeled
-- 'unverified_single_source_ghost_relabel_duval_20260703_not_tier1' by a prior shard (already excluded
-- from the tier1% filter); the remainder reflects the matcher's honest rejoin against current outcome
-- tables.
--
-- Diagnosed the two structural gaps behind duval's low C/D within its 620-row certification scope
-- (data_source<>'propertyonion' or null, or tier1_authoritative=true):
--   - 255 unmatched sale_type='foreclosure' rows (auction_status='completed', parity_status IS NULL):
--     matched against duval_clerk_grantor_recordings_staging's conveyance_class='FORECLOSURE_CERT_OF_TITLE'
--     subset (113 rows, real recorded-document data scraped from or.duvalclerk.com/SearchTypeName).
--     ROOT CAUSE: only 4 of 113 CoT staging rows have a non-null parcel_pin_extracted -- the other 109
--     failed upstream PIN extraction (their doc_legal_description has no 'PIN ...' prefix, e.g.
--     'L6 B15 LINDSEY SUBDIVISION'). Of the 4 PIN-bearing rows, exactly 1 has a real, unique,
--     unambiguous parcel_id match in the unmatched set (067600), independently corroborated by an
--     EXACT consideration/tier1_sold_amount match ($137,800, an already-populated, independently-
--     sourced field) and a sane record-after-sale date gap (11 days). The other 3 CoT PINs
--     (013861-0380, 009866-0000, 131558-0000) have zero corresponding parcel_id anywhere in duval's
--     foreclosure auction data -- genuine gaps, not forced. This is NOT a viable path to close the
--     255-row gap at scale as-is; the real bottleneck is upstream PIN extraction from
--     doc_legal_description (109 rows have parseable lot/block/subdivision text that would need a
--     plat-lookup capability this session does not have -- flagged for a future session, not built
--     here to avoid a forced/fuzzy-match ghost-success).
--   - 14 unmatched sale_type='tax_deed' rows: matched against the full 702-row
--     duval_tax_deed_recordings_staging table via three independent strategies (parcel_pin equality,
--     embedded-PIN regex scan of doc_legal_description, record-date proximity to auction_date). Zero
--     legitimate hits. A naive street-name token search surfaced only generic-word coincidences,
--     explicitly rejected as the exact false-positive pattern the campaign's prior ghost-success
--     purges (santa_rosa, holmes, charlotte) already caught and reverted. All 14 remain honest,
--     reported gaps.
--
-- APPLIED (1 row, adversarially re-verified by an independent agent that re-queried both sides live
-- before confirming): case_number 16-2024-CA-002368-AXXX-MA, county=duval ->
--   parity_status='matched_clean', parity_source='tier1_acclaim_ct_duval_fc_v1',
--   parity_checked_at=2026-07-04T16:18:57Z
-- Live PATCH response (HTTP 200, return=representation) confirmed exactly 1 row changed, matching
-- MCA id 2bfba49e-b582-4066-9a6f-795b75c0b21d.
--
-- VERIFIED before/after (live pencil_dod_evaluate_county('duval'), p_county param):
--   BEFORE (post-refresh, pre-apply): C=14.2%% (matched_clean=88)   D=48.4%% (matched_any=300)
--   AFTER  (post-apply):              C=14.4%% (matched_clean=89)  D=48.5%% (matched_any=301)
--   (pre-session cached/stale reading was C=26.3%%(163) D=45.0%%(279) -- see correction note above)
-- Both still FAIL. This is a small, real, adversarially-confirmed gain, not a scale fix -- duval C/D
-- remains far from 95%% and requires either upstream PIN-extraction improvement on the CoT staging
-- pipeline (foreclosure side) or new clerk-source data (tax deed side) to move materially.
--
-- ── SARASOTA ── (confirmed hard ceiling, no writes made)
-- The 165/203 matched_clean figure was independently re-confirmed genuine this session (calling
-- refresh_parity_tier1_outcomes(p_county='sarasota') returns matched_clean=165, matching the live
-- evaluator exactly -- no ghost-success here, unlike several neighboring counties in this campaign).
-- The full 38-row gap was diagnosed exhaustively: cross-tab of auction_status x parity_status forms
-- an exact clean partition (completed/matched_clean=78, redeemed/matched_clean=70,
-- cancelled/matched_clean=17, upcoming/NULL=37, upcoming/tier1_only=1; sums to 203). ALL 38 unmatched
-- rows are auction_status='upcoming' (sale has not happened yet) -- zero closed-but-unmatched rows,
-- zero format-mismatch bugs found. Re-running refresh_parity_tier1_outcomes a second time returned an
-- identical 165 (idempotent, no missed matches). CONCLUSION: sarasota's 81.3%% C/D is a genuine, current
-- hard ceiling with no fixable gap today -- correctly left alone (BLANK > WRONG) rather than forced.
--
-- VERIFIED (live pencil_dod_evaluate_county('sarasota'), unchanged before/after, no write attempted):
--   C=81.3%% (matched_clean=165)  D=81.3%% (matched_any=165)  -- both still FAIL, honest ceiling
--
-- ── HOLMES ── (honest floor re-confirmed, no regression, no new data)
-- Re-verified live: tax_deed_outcomes/foreclosure_outcomes for holmes unchanged (0 / 1 rows) since the
-- 2026-07-04T00:00Z purge (dispatch 1745c67a). The sole surviving matched row
-- (HOLMES-LEGACY-123a1bd5-1ea3-4bb4-98ad-a7fc86853e49, data_source=holmes_clerk_direct, real
-- source_url) is intact and unchanged. No new outcome data has landed. No writes made.
--
-- VERIFIED (live pencil_dod_evaluate_county('holmes'), unchanged before/after):
--   B=null (0/0)  C=7.7%% (1/13)  D=7.7%% (1/13)  F=null (0/0) -- all still FAIL, honest floor holds
--
-- ── UNION ── (still structurally blocked; one new data-hygiene finding, not fixed this session)
-- Re-verified live: tax_deed_outcomes/foreclosure_outcomes for union remain 0 rows county-wide; all 3
-- multi_county_auctions rows remain auction_status='upcoming', exactly as SHARD-10 (commits
-- bd2ff6f5/f749c834, 2026-07-03) documented. No scraping was attempted (no FIRECRAWL_API_KEY this
-- session; direct fetch to unionclerk.com returns HTTP 403, confirmed both by main session and by the
-- workflow's diagnose agent).
-- NEW FINDING (not remediated this session -- flagged for a future write-enabled/scraping-capable
-- session): case_number UNION-TD-CERT223 (id c67336ae-ac78-4bf0-ba9c-ed242cbdadac) has
-- auction_date=2026-03-12, ~114 days in the past relative to today, yet auction_status is still
-- 'upcoming' and needs_source_rescrape=false (never queued for re-check) despite the row's scrape
-- metadata having been touched as recently as 2026-07-04T12:21:45Z (a metadata-only refresh that never
-- resolves or flags the stale status). This is a genuine scraper/staleness gap independent of the
-- gold-standard letters -- worth a `needs_source_rescrape=true` flag or a stale-auction-status
-- heuristic in a future session with real unionclerk.com access.
--
-- VERIFIED (live pencil_dod_evaluate_county('union'), unchanged before/after, no write made):
--   B=null (0/0)  C=0.0%% (0/3)  D=0.0%% (0/3)  F=null (0/0)  I=0.0%% (0/3)  J=0.0%% (0/3)
--   -- all still FAIL, structurally blocked pending a real sale + independent clerk verification
--
-- Logged to gold_standard_ultraloop_audit (dispatch_id 9e70dcd7-f9cd-4c17-b3a1-596a9da4b20f): 6 rows,
-- all survived=true (1 real applied gain for duval C, 1 genuine-gap confirmation for duval C bulk
-- attempt, 1 genuine-gap confirmation for duval D tax-deed attempt, 1 hard-ceiling confirmation for
-- sarasota, 1 no-change confirmation for holmes, 1 no-change-plus-new-finding for union).
--
-- gold_standard_loop()/gold_standard_certify() were NOT run this session per PARALLEL-FLEET RULES
-- (other shards may be mid-flight on other counties concurrently) -- per-county
-- pencil_dod_evaluate_county reports above are the verification record for this dispatch.

SELECT 1; -- no-op placeholder: all live reads/writes this session were applied via PostgREST
          -- (/rest/v1/multi_county_auctions PATCH, /rest/v1/gold_standard_ultraloop_audit POST) and RPC
          -- calls (pencil_dod_evaluate_county, refresh_parity_tier1_outcomes) using
          -- SUPABASE_SERVICE_ROLE_KEY -- direct psql/Management API SQL are blocked in this sandbox,
          -- consistent with other shards' 2026-07-04 findings. This file documents them for the repo
          -- history; the actual mutation already landed live (see PATCH response quoted above).
