-- SHARD-6 (dispatch_id cc6bdc10-6b93-496a-bcd6-7919ff2757cf): madison C/D
-- canonical rematch. Applied live via Supabase Management API SQL endpoint
-- (api.supabase.com/v1/projects/mocerqjnksmhcjzxrewo/database/query with
-- SUPABASE_ACCESS_TOKEN).
--
-- CONTEXT: madison has 9 auctions total, all auction_status='completed'. All 9
-- previously carried parity_status='mca_only' with parity_source=
-- 'tier1_madison_direct' -- an untraceable label (no source file in repo) whose
-- name implies a direct match but whose status shows unmatched, blocking the
-- canonical matcher from ever touching these rows (refresh_parity_tier1_outcomes
-- only rematches rows where the pre-existing closed-status reset clears
-- parity_source to NULL first).
--
-- STEP 1 (BEFORE, live query): SELECT public.pencil_dod_evaluate_county('madison');
--   C: pass=false matched_clean=0 metric=0.0
--   D: pass=false matched_any=0   metric=0.0
--
-- STEP 2 (ACTION, live, this session):
--   SELECT * FROM public.refresh_parity_tier1_outcomes('madison');
--   -- existing shared canonical matcher, UNCHANGED. Result: case-number pass
--   -- matched_clean=9, matched_divergent=0; parcel-id pass matched_clean=0,
--   -- matched_divergent=0 (all 9 resolved on the case-number pass alone).
--
-- STEP 3 (AFTER, live query): SELECT public.pencil_dod_evaluate_county('madison');
--   C: pass=true matched_clean=9 metric=100.0  => county now 10/10 on C
--   D: pass=true matched_any=9   metric=100.0  => county now 10/10 on D
--   All other letters (A/B/E/F/G/H/I/J) already passed and are unaffected.
--
-- Verified backing (this session, live): all 9 rows split 5x
-- parity_source='tier1_foreclosure_outcome' (case_numbers MADISON-FC-2026-001/002/003,
-- MADISON-FC-PAST-001/002) and 4x parity_source='tier1_tax_deed_outcome'
-- (MADISON-TD-2026-001/002/003, MADISON-TD-PAST-001). Cross-checked against
-- foreclosure_outcomes/tax_deed_outcomes: all 9 case_numbers present with
-- data_source='realforeclose:shard5-v1'/'realforeclose:shard5-loop472' or
-- 'realtaxdeed:shard5-v1'/'realtaxdeed:shard5-loop472' (non-promote, legitimate
-- scraper tags), outcome SOLD. No ghost/relabeled matches.
--
-- Adversarially verified (independent refuter agent, same session): claim
-- SURVIVED -- live re-run reproduced C=100.0/D=100.0 exactly.
--
-- madison is now PASS on all 10 letters (A/B/C/D/E/F/G/H/I/J). Certification
-- requires >=1 survived=true gold_standard_ultraloop_audit row per letter within
-- 7 days (logged separately this session) plus a second consecutive 10/10 daily
-- 07:30Z run -- NOT run here (this session did not invoke gold_standard_loop()/
-- gold_standard_certify(), per PARALLEL-FLEET RULES, since other shards may be
-- running concurrently).
--
-- No other county touched by this migration.

SELECT 1; -- no-op placeholder: documents the live refresh_parity_tier1_outcomes('madison')
          -- call already applied via the Supabase Management API SQL endpoint in this session.
