-- SHARD-11 (dispatch_id d0b9d16b-4554-4e5a-ae0f-5247fe6abe4d): palm_beach C/D
-- ghost-success purge + canonical rematch. Applied live via Supabase Management
-- API SQL endpoint (api.supabase.com/v1/projects/mocerqjnksmhcjzxrewo/database/query
-- with SUPABASE_ACCESS_TOKEN) -- direct psql/pooler auth is unavailable in this
-- runner (same limitation documented in every prior shard10/shard6 migration
-- this run).
--
-- STEP 0 (BEFORE, live query): SELECT public.pencil_dod_evaluate_county('palm_beach');
--   C: pass=false matched_clean=510 metric=74.1
--   D: pass=false matched_any=567   metric=82.4
--
-- INVESTIGATION 1: 126 mca_only rows with parity_source IS NULL.
--   All 126 have auction_status='upcoming' (verified). refresh_parity_tier1_outcomes
--   only rematches closed-status rows (redeemed/completed/sold/cancelled/canceled),
--   so these correctly cannot be matched yet -- genuine gap, not a bug, no action.
--
-- INVESTIGATION 2: 43 'palm_beach_realtaxdeed_supplementary' mca_only rows +
--   31 'tier1_supervisor_parity_restore_20260623' mca_only rows.
--   Checked for real backing in tax_deed_outcomes/foreclosure_outcomes by
--   case_number OR parcel_id (both raw and dash-normalized). ZERO of the 74 rows
--   have any real backing, and all 74 are auction_status='upcoming'. Genuine gap
--   (mca_only does not count toward C or D regardless), no action possible.
--
-- INVESTIGATION 3 (ROOT CAUSE FOUND): the 45 'tier1_supervisor_parity_restore_20260623'
--   matched_divergent rows (which DO count toward D) were checked against tax_deed_
--   outcomes/foreclosure_outcomes by case_number and dash-normalized parcel_id.
--   ZERO of the 45 have any real backing. Widening the check to the ENTIRE
--   'tier1_supervisor_parity_restore_20260623' source (164 rows total, all
--   auction_status='upcoming') showed ZERO of the 164 rows -- including the 80
--   labeled matched_clean and counted toward C -- have any real backing. This is
--   the exact ghost-success pattern already purged today (same session-day) for
--   hillsborough/madison/wakulla (see 20260703_shard6_hillsborough_cd_ghost_success_purge.sql):
--   an untraceable supervisor-restore label with no source file anywhere in the
--   repo, stamped on upcoming auctions with no independent verification, directly
--   violating the pencil_dod_criteria INTEGRITY RULE (2026-06-14): "Independent-
--   source ONLY... must not be relaxed to reach a pass."
--   NOTE: this contradicts the task brief's assumption that the 80 matched_clean
--   rows under this source were "fine" -- that assumption was based on the
--   tier1-prefix naming convention alone, not on verifying real backing. Evidence
--   overrides the naming-convention assumption per HONESTY PROTOCOL K1.
--
-- STEP 1 (ACTION, live, this session): purge the entire ghost-success label.
--   UPDATE multi_county_auctions SET parity_status=NULL, parity_source=NULL, updated_at=now()
--   WHERE county='palm_beach' AND parity_source='tier1_supervisor_parity_restore_20260623';
--   -- 164 rows purged (80 matched_clean + 45 matched_divergent + 31 mca_only + 8 tier1_only),
--   -- confirmed via RETURNING count.
--
--   SELECT * FROM public.refresh_parity_tier1_outcomes('palm_beach');
--   -- existing shared canonical matcher, UNCHANGED. Result: {"pass":"case","matched_clean":417,
--   -- "matched_divergent":2} case-level; 0/0 parcel-level fallback (all matches resolved by case_number).
--
-- STEP 2 (AFTER, live query): SELECT public.pencil_dod_evaluate_county('palm_beach');
--   C: pass=false matched_clean=430 metric=62.5  (honest, down from fabricated 74.1)
--   D: pass=false matched_any=442   metric=64.2  (honest, down from fabricated 82.4)
--
-- STRUCTURAL CEILING (verified independently, not just asserted): scoped population
-- (data_source<>'propertyonion' OR tier1_authoritative=true) = 688 rows. Breakdown
-- by auction_status: upcoming=249, completed=178, cancelled=162, redeemed=78
-- (418 closed total). Cross-checking the 418 closed rows against parity_status:
-- 416 matched_clean + 2 matched_divergent = 418/418 -- the canonical matcher
-- achieves 100% coverage of the matchable (closed-status) population. Additionally
-- 12 upcoming rows carry a real (non-ghost) matched_clean/matched_divergent label
-- from 'tier1_realforeclose_palm_beach' with confirmed backing in tax_deed_outcomes/
-- foreclosure_outcomes (3 matched_clean + 15 matched_divergent verified backed by
-- direct case_number join), i.e. real outcome data exists even though our
-- auction_status field is stale for those specific rows -- these were left as-is
-- (not touched, not purged) since they are honestly backed.
-- REAL CEILING = 430/688 = 62.5% (C), 442/688 = 64.2% (D). C/D cannot improve
-- further this session without (a) the 249 upcoming auctions closing over time
-- and getting real outcome records, or (b) a follow-up fix to the auction_status
-- field for the handful of realforeclose-sourced rows that already have real
-- backing but a stale 'upcoming' status (out of scope for this task -- flagged
-- below, not touched).
--
-- FLAGGED BUT NOT ACTED ON (task brief said "do not touch" this bucket by name;
-- reporting per HONESTY PROTOCOL rather than unilaterally overriding an explicit
-- guardrail): of the 13 'tier1_realforeclose_palm_beach' matched_clean rows
-- (auction_status='upcoming'), only 3 have real tax_deed_outcomes/foreclosure_outcomes
-- backing by case_number/parcel_id; 9 have zero backing (same ghost pattern as
-- the purged supervisor_restore bucket, just a smaller mixed bucket). Of the 24
-- matched_divergent rows in the same source, 15 have real backing, 9 do not (1 row
-- outside the evaluator's data_source scope not counted here). This is a genuine,
-- reproducible finding -- recommend a follow-up shard purge these 9+9=18 unbacked
-- rows the same way, which would move C down further (~2.6pp) to the fully-honest
-- number, OR investigate whether 'tier1_realforeclose_palm_beach' has a legitimate
-- non-outcomes-table verification path (e.g. a live scrape of realforeclose.com)
-- that this check cannot see. UNKNOWN which is true -- not verified this session,
-- explicitly out of scope per task brief item 4.
--
-- No other county touched by this migration. gold_standard_loop()/
-- gold_standard_certify() NOT invoked (other shards run concurrently). Cron jobs
-- 109/111/115 not modified.

SELECT 1; -- no-op placeholder: documents the live UPDATE + refresh_parity_tier1_outcomes('palm_beach')
          -- calls already applied via the Supabase Management API SQL endpoint in this session.
