// S5 Shapira Formula — $25/call, gate: pro tier + CERT REQUIRED
//
// GTM-22 S5 REPORT ENGINE (issue #12853): the deliverable is now the
// 17-section + SECTION ZW + CMA property intelligence report (src/report/
// composer.js), matching the report the owner generated by hand at the
// 2026-07-20 live Marion courthouse sale. Billing, the cert gate, and the
// pricing/tier config are UNCHANGED — this only replaces what the handler
// returns once the gate has already cleared.
import { get, insert } from '../supabase.js';
import { buildReport } from '../report/composer.js';
import { renderReportPdf } from '../report/pdf.js';
import { checkSellability } from '../report/sellability.js';

export const schemas = [
  {
    name: 'predict_auction_outcome',
    description: 'Get the full BidDeed property intelligence report for a foreclosure/tax-deed auction — the "should I bid on this?" / "what\'s the outlook for this property?" call. Returns a 17-section report (BID/REVIEW/SKIP verdict, Shapira Max Bid, county clearance priors, ZoneWise land & zoning pairing, comparable sales, red flags, full provenance) as both structured JSON and a branded PDF. $25/call. CERT REQUIRED: the county must currently pass BidDeed Gold Standard certification — call search_auctions ($0.05/call) first to discover cases and confirm certification for your county.',
    annotations: { readOnlyHint: true, destructiveHint: false, idempotentHint: true, openWorldHint: false },
    inputSchema: {
      type: 'object',
      properties: {
        case_number: { type: 'string', description: 'Auction case number' },
        county:      { type: 'string', description: 'FL county (must be Gold Standard certified)' },
        arv:         { type: 'number', description: 'Your After Repair Value estimate (optional — the report\'s own anchor-based value estimate is used by default)' },
        strategy:    { type: 'string', enum: ['rental', 'flip', 'brrrr'], description: 'Exit strategy (informational — does not change the anchor-based verdict)' },
      },
      required: ['case_number', 'county'],
    },
  },
];

export async function predict_auction_outcome({ case_number, county }) {
  // GTM-22F — the CERT_REQUIRED gate for this tool runs centrally in
  // server.js (evaluateCertGate, before the charge decision) against the
  // canonical v_certified_counties view. By the time this handler runs,
  // county is guaranteed certified.
  const rows = await get(
    `multi_county_auctions?case_number=eq.${encodeURIComponent(case_number)}&limit=1`
  ).catch(() => []);

  if (!rows.length) {
    return { error: 'AUCTION_NOT_FOUND', case_number, county, message: 'Auction not found in database.' };
  }

  const auction = rows[0];
  const report = await buildReport(auction, { get });

  // Sellability render-gate (Aug 14 2026, issue #19079) - runs BEFORE PDF
  // rendering and BEFORE the caller's billing wrapper sees a successful
  // return. A failing report throws here instead of returning - the tool
  // call errors out, nothing is billed, nothing reaches the customer.
  const sellability = checkSellability(report);
  if (!sellability.sellable) {
    const reason = sellability.reasons.join('; ');
    try {
      await insert('agent_ops_log', {
        dispatch_id: 's5-sellability-gate',
        task: `predict_auction_outcome case=${case_number} county=${county}`,
        status: 'BLOCKED',
        severity: 'blocker',
        evidence: reason.slice(0, 2000),
      });
    } catch (_) { /* logging failure must never mask the real gate error thrown below */ }
    throw new Error(`REPORT_FAILED_SELLABILITY_GATE: ${reason}`);
  }

  const pdf = await renderReportPdf(report);

  return {
    case_number,
    county,
    cert_status: 'certified',
    model_version: report.context_layers?.ml_model?.model_version || null,
    report,
    pdf_base64: pdf.toString('base64'),
    billing_note: '$25 charged to your account. View billing at biddeed.ai/dashboard/billing.',
  };
}
